export const rawTSVCohort2 = `Emp.Code	Vi Name	Eng Name	Site	Location	Department	Section	Position	Title	Job Duty	R Rating	Top Opportunity	Comments	Way Forward	Timeline	Note	Source_File	Mapped Need	Competency Focus	Training Category	Action	Proposed Program	Owner
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Coaching & Mentoring	R2	(blank)	Willing but lacks coaching method	Apply the GROW Model or TWI (Training Within Industry) 4-step method for better results.	Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Coaching / Mentoring	Coaching Skills	Soft Skill	Add to Training Plan	Coaching & Mentoring	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Continuous Improvement (Kaizen / Lean)	R2	(blank)	Participates but rarely leads CI	Lead 1 CI project / quarter	Q2–Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Cross-functional Coordination	R2	(blank)	Cooperates well; needs stronger influencing	Lead cross-department meetings	Q2–Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Daily Production Communication	R3	X	Clear daily briefing & follow-up	Implement a visual tracking board for real-time gap analysis during the shift.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Communication / Presentation	Communication Skills	Soft Skill	Add to Training Plan	Communication & Presentation	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Employee Engagement & Retention	R2	(blank)	Good engagement; limited data analysis	Monitor monthly Turnover/Absenteeism Trends to identify and address root causes of dissatisfaction.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Employee Relations / Engagement	Employee Relations	Functional	Department Follow-up	Employee Relations Follow-up	HRBP / Department
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Manpower Allocation & Attendance Control	R3	(blank)	Strong control of workforce utilization	Create a Multi-Skill Matrix to improve workforce flexibility during absenteeism or surges.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Performance Management	R3	X	Manages performance effectively	Adopt Visual Management (Hourly Boards) to enable real-time reaction to performance gaps.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Personal Development (Sharpen the Saw)	R3	(blank)	Development activities not structured	Define an Individual Development Plan (IDP) with at least one new skill or management book per quarter.	Q3-Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	People Development / IDP	People Development	People Development	Add to Training Plan	People Development / IDP & Skill Matrix	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Problem Escalation & Decision Making	R2	X	Escalates timely; decisions aligned	Develop a Delegation Matrix to expedite decision-making for recurring operational issues.	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Business Acumen / Decision Making	Business Acumen	Business Acumen	Need Validation	Business Acumen & Decision Making	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Process Knowledge	R3	(blank)	Limited in whole process understanding	Mentor new supervisors	Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Technical / Functional	Functional Skills	Functional	Department Follow-up	Function-specific Development Plan	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Execution & Output Control	R3	X	Consistently meets output & efficiency target	Mentor weaker lines by sharing "Best Practice" techniques and output control methods.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Planning & Line Balancing	R3	X	Good daily planning; limited long-term capacity view	Develop a weekly/monthly Capacity Forecast to proactively manage manpower and equipment	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Quality Control & Defect Reduction	R2	(blank)	Knows defects; limited root cause depth	Strengthen RCA & defect trend analysis	Q2–Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Safety Awareness & PPE Compliance	R2	(blank)	Enforces safety rules effectively	Lead by example by conducting daily 5-minute safety talks and empowering Line Leaders to perform "Safety Spot Checks" to move from enforcement to a self-sustaining safety culture	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	SOP & Work Instruction Compliance	R2	(blank)	Ensures standard work compliance	Implement Peer Audits between sections to sustain high discipline and identify blind spots.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Supervisor & Line Leader Development	R2	(blank)	On-job coaching; not structured	Establish a Structured Training Roadmap for each Line Leader position to ensure consistency	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Team Leadership & Discipline	R2	(blank)	Commands respect; fair discipline	Attend Influential Leadership training to transition from "compliance" to "commitment.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Khiêm	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	WIP & Throughput Control	R2	(blank)	Controls WIP but reactive at times	Apply pull system / visual WIP control	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Coaching & Mentoring	R2	(blank)	High willingness to coach; lacks a structured coaching approach	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Coaching / Mentoring	Coaching Skills	Soft Skill	Add to Training Plan	Coaching & Mentoring	L&D + HRBP
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Continuous Improvement / Kaizen	R3	(blank)	Participates in CI activities; influence across teams is limited	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Cross-Functional Communication (IE, QA, Maintenance)	R3	X	Able to raise issues; influencing outcomes across functions is limited	Improve clarity and confidence when proposing solutions cross-functionally	Q2–Q3	Influence without authority	Ed Template with Examples_Edward Leipart	Communication / Presentation	Communication Skills	Soft Skill	Add to Training Plan	Communication & Presentation	L&D + HRBP
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Employee Engagement & Retention	R3	X	Good engagement level; messages are sometimes inconsistent	Align communication messages with department and factory goals	Q3	(blank)	Ed Template with Examples_Edward Leipart	Employee Relations / Engagement	Employee Relations	Functional	Department Follow-up	Employee Relations Follow-up	HRBP / Department
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Manpower Allocation & Attendance Control	R4	(blank)	Strong manpower control; communication tends to be reactive	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Personal Development (Sharpen the Saw)	R4	(blank)	Willing to study about customer expectations and try to make it happens	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	People Development / IDP	People Development	People Development	Add to Training Plan	People Development / IDP & Skill Matrix	L&D + HRBP
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Problem Escalation & Decision Communication	R4	(blank)	Well awarenees and analysis about problem impacting and take actions quickly.	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Communication / Presentation	Communication Skills	Soft Skill	Add to Training Plan	Communication & Presentation	L&D + HRBP
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Process Knowledge	R3	(blank)	Strong end-to-end process understanding	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Technical / Functional	Functional Skills	Functional	Department Follow-up	Function-specific Development Plan	Department / Functional SME
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Execution & Output Control	R4	(blank)	Consistently achieves output targets; communication style is mainly directive	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Planning & Line Balancing	R4	(blank)	Strong daily planning control; long-term priorities and rationale are not always clearly communicated	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Quality Control & Defect Reduction	R3	(blank)	Good technical analysis; communication not fully linked to business impact	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Safety Communication	R3	X	Clearly communicates safety rules and expectations	Reinforce safety messages through practical examples and lessons learned	Ongoing	Safety leadership	Ed Template with Examples_Edward Leipart	Communication / Presentation	Communication Skills	Soft Skill	Add to Training Plan	Communication & Presentation	L&D + HRBP
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Supervisor & Line Leader Development	R3	X	Provides guidance; feedback and coaching are not yet structured	Conduct regular coaching and structured feedback sessions	Q2–Q3	Succession readiness	Ed Template with Examples_Edward Leipart	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Team Leadership & Discipline	R3	X	Strong discipline and control; communication style can be rigid	Balance authority with motivational and engagement-focused communication	Ongoing	(blank)	Ed Template with Examples_Edward Leipart	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Lệ	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	WIP & Throughput Control	R3	(blank)	Controls WIP effectively; impact is not always clearly explained to the team	(blank)	(blank)	(blank)	Ed Template with Examples_Edward Leipart	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Coaching & Mentoring	R2	(blank)	Willing but lacks coaching method	Apply the GROW Model or TWI (Training Within Industry) 4-step method for better results.	Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Coaching / Mentoring	Coaching Skills	Soft Skill	Add to Training Plan	Coaching & Mentoring	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Continuous Improvement (Kaizen / Lean)	R3	(blank)	Participates but rarely leads CI	Lead 1 CI project / quarter	Q2–Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Cross-functional Coordination	R3	(blank)	Cooperates well; needs stronger influencing	Lead cross-department meetings	Q2–Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Daily Production Communication	R4	X	Clear daily briefing & follow-up	Implement a visual tracking board for real-time gap analysis during the shift.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Communication / Presentation	Communication Skills	Soft Skill	Add to Training Plan	Communication & Presentation	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Employee Engagement & Retention	R3	(blank)	Good engagement; limited data analysis	Monitor monthly Turnover/Absenteeism Trends to identify and address root causes of dissatisfaction.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Employee Relations / Engagement	Employee Relations	Functional	Department Follow-up	Employee Relations Follow-up	HRBP / Department
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Manpower Allocation & Attendance Control	R4	X	Strong control of workforce utilization	Create a Multi-Skill Matrix to improve workforce flexibility during absenteeism or surges.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Performance Management	R4	(blank)	Manages performance effectively	Adopt Visual Management (Hourly Boards) to enable real-time reaction to performance gaps.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Personal Development (Sharpen the Saw)	R3	X	Development activities not structured	Define an Individual Development Plan (IDP) with at least one new skill or management book per quarter.	Q3-Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	People Development / IDP	People Development	People Development	Add to Training Plan	People Development / IDP & Skill Matrix	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Problem Escalation & Decision Making	R3	X	Escalates timely; decisions aligned	Develop a Delegation Matrix to expedite decision-making for recurring operational issues.	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Business Acumen / Decision Making	Business Acumen	Business Acumen	Need Validation	Business Acumen & Decision Making	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Process Knowledge	R3	(blank)	Limited in whole process understanding	Mentor new supervisors	Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Technical / Functional	Functional Skills	Functional	Department Follow-up	Function-specific Development Plan	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Execution & Output Control	R4	(blank)	Consistently meets output & efficiency target	Mentor weaker lines by sharing "Best Practice" techniques and output control methods.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Planning & Line Balancing	R3	(blank)	Good daily planning; limited long-term capacity view	Develop a weekly/monthly Capacity Forecast to proactively manage manpower and equipment	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Quality Control & Defect Reduction	R3	X	Knows defects; limited root cause depth	Strengthen RCA & defect trend analysis	Q2–Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Safety Awareness & PPE Compliance	R3	(blank)	Enforces safety rules effectively	Lead by example by conducting daily 5-minute safety talks and empowering Line Leaders to perform "Safety Spot Checks" to move from enforcement to a self-sustaining safety culture	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	SOP & Work Instruction Compliance	R4	(blank)	Ensures standard work compliance	Implement Peer Audits between sections to sustain high discipline and identify blind spots.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Supervisor & Line Leader Development	R3	(blank)	On-job coaching; not structured	Establish a Structured Training Roadmap for each Line Leader position to ensure consistency	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Team Leadership & Discipline	R4	(blank)	Commands respect; fair discipline	Attend Influential Leadership training to transition from "compliance" to "commitment.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Liễu	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	WIP & Throughput Control	R2	(blank)	Controls WIP but reactive at times	Apply pull system / visual WIP control	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Coaching & Mentoring	R2	X	Willing but lacks coaching method	Apply the GROW Model or TWI (Training Within Industry) 4-step method for better results.	Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Coaching / Mentoring	Coaching Skills	Soft Skill	Add to Training Plan	Coaching & Mentoring	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Continuous Improvement (Kaizen / Lean)	R3	(blank)	Participates but rarely leads CI	Lead 1 CI project / quarter	Q2–Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Cross-functional Coordination	R3	(blank)	Cooperates well; needs stronger influencing	Lead cross-department meetings	Q2–Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Daily Production Communication	R4	X	Clear daily briefing & follow-up	Implement a visual tracking board for real-time gap analysis during the shift.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Communication / Presentation	Communication Skills	Soft Skill	Add to Training Plan	Communication & Presentation	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Employee Engagement & Retention	R3	(blank)	Good engagement; limited data analysis	Monitor monthly Turnover/Absenteeism Trends to identify and address root causes of dissatisfaction.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Employee Relations / Engagement	Employee Relations	Functional	Department Follow-up	Employee Relations Follow-up	HRBP / Department
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Manpower Allocation & Attendance Control	R4	X	Strong control of workforce utilization	Create a Multi-Skill Matrix to improve workforce flexibility during absenteeism or surges.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Performance Management	R4	(blank)	Manages performance effectively	Adopt Visual Management (Hourly Boards) to enable real-time reaction to performance gaps.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Personal Development (Sharpen the Saw)	R3	(blank)	Development activities not structured	Define an Individual Development Plan (IDP) with at least one new skill or management book per quarter.	Q3-Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	People Development / IDP	People Development	People Development	Add to Training Plan	People Development / IDP & Skill Matrix	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Problem Escalation & Decision Making	R3	X	Escalates timely; decisions aligned	Develop a Delegation Matrix to expedite decision-making for recurring operational issues.	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Business Acumen / Decision Making	Business Acumen	Business Acumen	Need Validation	Business Acumen & Decision Making	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Process Knowledge	R3	(blank)	Limited in whole process understanding	Mentor new supervisors	Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Technical / Functional	Functional Skills	Functional	Department Follow-up	Function-specific Development Plan	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Execution & Output Control	R4	(blank)	Consistently meets output & efficiency target	Mentor weaker lines by sharing "Best Practice" techniques and output control methods.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Planning & Line Balancing	R3	(blank)	Good daily planning; limited long-term capacity view	Develop a weekly/monthly Capacity Forecast to proactively manage manpower and equipment	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Quality Control & Defect Reduction	R3	(blank)	Knows defects; limited root cause depth	Strengthen RCA & defect trend analysis	Q2–Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Safety Awareness & PPE Compliance	R3	(blank)	Enforces safety rules effectively	Lead by example by conducting daily 5-minute safety talks and empowering Line Leaders to perform "Safety Spot Checks" to move from enforcement to a self-sustaining safety culture	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	SOP & Work Instruction Compliance	R4	(blank)	Ensures standard work compliance	Implement Peer Audits between sections to sustain high discipline and identify blind spots.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Supervisor & Line Leader Development	R3	(blank)	On-job coaching; not structured	Establish a Structured Training Roadmap for each Line Leader position to ensure consistency	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Team Leadership & Discipline	R4	(blank)	Commands respect; fair discipline	Attend Influential Leadership training to transition from "compliance" to "commitment.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Nhung	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	WIP & Throughput Control	R2	(blank)	Controls WIP but reactive at times	Apply pull system / visual WIP control	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Coaching & Mentoring	R3	(blank)	Willing but lacks coaching method	Apply the GROW Model or TWI (Training Within Industry) 4-step method for better results.	Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Coaching / Mentoring	Coaching Skills	Soft Skill	Add to Training Plan	Coaching & Mentoring	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Continuous Improvement (Kaizen / Lean)	R3	(blank)	Participates but rarely leads CI	Lead 1 CI project / quarter	Q2–Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Cross-functional Coordination	R3	(blank)	Cooperates well; needs stronger influencing	Lead cross-department meetings	Q2–Q3	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Daily Production Communication	R3	X	Clear daily briefing & follow-up	Implement a visual tracking board for real-time gap analysis during the shift.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Communication / Presentation	Communication Skills	Soft Skill	Add to Training Plan	Communication & Presentation	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Employee Engagement & Retention	R2	(blank)	Good engagement; limited data analysis	Monitor monthly Turnover/Absenteeism Trends to identify and address root causes of dissatisfaction.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Employee Relations / Engagement	Employee Relations	Functional	Department Follow-up	Employee Relations Follow-up	HRBP / Department
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Manpower Allocation & Attendance Control	R3	X	Strong control of workforce utilization	Create a Multi-Skill Matrix to improve workforce flexibility during absenteeism or surges.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Performance Management	R3	(blank)	Manages performance effectively	Adopt Visual Management (Hourly Boards) to enable real-time reaction to performance gaps.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Personal Development (Sharpen the Saw)	R3	X	Development activities not structured	Define an Individual Development Plan (IDP) with at least one new skill or management book per quarter.	Q3-Q4	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	People Development / IDP	People Development	People Development	Add to Training Plan	People Development / IDP & Skill Matrix	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Problem Escalation & Decision Making	R3	X	Escalates timely; decisions aligned	Develop a Delegation Matrix to expedite decision-making for recurring operational issues.	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Business Acumen / Decision Making	Business Acumen	Business Acumen	Need Validation	Business Acumen & Decision Making	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Process Knowledge	R3	(blank)	Limited in whole process understanding	Mentor new supervisors	Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Technical / Functional	Functional Skills	Functional	Department Follow-up	Function-specific Development Plan	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Execution & Output Control	R3	X	Consistently meets output & efficiency target	Mentor weaker lines by sharing "Best Practice" techniques and output control methods.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Production Planning & Line Balancing	R3	(blank)	Good daily planning; limited long-term capacity view	Develop a weekly/monthly Capacity Forecast to proactively manage manpower and equipment	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Quality Control & Defect Reduction	R3	(blank)	Knows defects; limited root cause depth	Strengthen RCA & defect trend analysis	Q2–Q3	Use Pareto	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Quality / RCA / CI	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Safety Awareness & PPE Compliance	R3	(blank)	Enforces safety rules effectively	Lead by example by conducting daily 5-minute safety talks and empowering Line Leaders to perform "Safety Spot Checks" to move from enforcement to a self-sustaining safety culture	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	SOP & Work Instruction Compliance	R3	(blank)	Ensures standard work compliance	Implement Peer Audits between sections to sustain high discipline and identify blind spots.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Compliance / Safety / Admin	Process & Compliance	Process / Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Supervisor & Line Leader Development	R3	(blank)	On-job coaching; not structured	Establish a Structured Training Roadmap for each Line Leader position to ensure consistency	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	Team Leadership & Discipline	R3	(blank)	Commands respect; fair discipline	Attend Influential Leadership training to transition from "compliance" to "commitment.	Ongoing	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Leadership / Stakeholder / Culture	Leadership Skills	Leadership	Add to Training Plan	Servant Leadership	L&D + HRBP
(blank)	Quân	(blank)	Millennium	MLN	(blank)	(blank)	(blank)	(blank)	WIP & Throughput Control	R3	(blank)	Controls WIP but reactive at times	Apply pull system / visual WIP control	Q2	(blank)	RICARDO_CUT&SEW_TRSP_Thao Nguyen	Resource / Workforce Planning	Workforce Planning	Functional	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME
`;
