export const rawAshIDPTSV = `Emp Code	Person Name	Department	Critical Role	Job Duty	R Rating	Top Opp.	Comments	Way Forward	Timeline	Notes	Training Category	Competency Focus	Action	Proposed Program	Program Owner	Source Owner
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Ramp Plan Development	R3		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Ramp Plan Execution	R3		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Resource Management (Human)	R3		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Resource Development (Human)	R3		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Budget development & management	R3	X	Confident in budgeting; needs stronger cost optimization mindset and scenario planning	Lead cost optimization initiatives; propose budget scenarios	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Building and Promoting a Company Culture	R3		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2–Q3	Use GROW model	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Lisa
50010	Lisa Nguyen	HUMAN RESOURCES	HR Specialist	Employee Relations Improvement	R3	X	Handles ER cases effectively	Lead complex and sensitive ER cases	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Readiness Development Pl-Lisa
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Ramp Plan Development	R3		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Ramp Plan Execution	R3		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Resource Management (Human)	R3		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Resource Development (Human)	R3		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Budget development & management	R3		Confident in recruitment budgeting; needs stronger cost-per-hire optimization mindset	Optimize hiring cost and channel efficiency	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead and gradually own succession planning	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Recruitment Plan Development	R3	X	Strong execution; needs stronger strategic workforce planning and forecasting	Build annual recruitment plan aligned with manpower and business growth	Q2–Q3	Align with manpower plan	Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Recruitment Execution	R3	X	Executes hiring well; needs stronger data-driven decision making and funnel optimization	Build recruitment dashboard; optimize conversion funnel	Q3		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	HR Market Analysis	R3	X	Good market understanding; needs proactive talent mapping and competitor benchmarking	Build talent pipeline and market intelligence report	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Personal Development (Sharpen the Saw)	R3		Development activities not fully structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Building and Promoting a Company Culture	R3		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development Pl-Ellie
50443	Ellie Tran	HUMAN RESOURCES	HR Specialist	Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Apply coaching in real cases; track team performance improvement	Q2–Q3	Use GROW model	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl-Ellie
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Financial Strategy & Planning	R3	X	Capable in budgeting; needs more involvement in long-term (10-year) financial strategy.	Participate in regional strategic planning sessions with Mr. Bob.	Q2–Q4	Focus on CCA Debt Strategy project.	Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Ha
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Internal Control & Compliance	R4		Highly proficient in internal controls and accounting compliance.	Stay updated on changes in tax laws and auditing standards.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Ha
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Team Leadership & Management	R3	X	Strong operational management; needs to enhance independent decision-making at Manager level.	Take over as Interim Manager during the FA Manager’s absence.	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Readiness Development-Ha
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Stakeholder Management	R3		Effective communication; needs to polish reporting style for C-level executives.	Practice designing professional financial dashboards for monthly meetings.	Q2–Q3	Refine slides for Executive presentation.	Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Readiness Development-Ha
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Risk Management	R4		Strong ability to identify financial risks (as shown in Risk Assessment).	Mentor the team on proactive risk mitigation strategies.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Ha
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Succession Planning	R2	X	Understands the concept; needs to build a structured development path for successors.	Initiate a formal development plan for Maya (direct successor).	Q3–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development-Ha
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Business English Communication	R3	X	Improving steadily; needs more confidence and fluency in high-stake presentations.	Maintain daily learning schedule; lead more English-based meetings.	Q1–Q4	Focus on speaking reflexes.	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Ha
	Ha Nguyen	FINANCE & ACCOUNTING	Assistant FA manager	Driving Innovation	R3		Reliable in execution; should proactively propose digital transformation or automation.	Propose one process automation project within this quarter.	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Ha
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Strategic Financial Leadership	R3	X	"Strong in operations; needs to transition from ""managing"" to ""shaping"" corporate strategy."	Partner with Global/HQ Finance on long-term capital allocation plans.	Q2–Q4		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Board & HQ Relations	R3	X	"Provides accurate reports; needs to enhance ""storytelling"" with data for Board members."	Lead quarterly business reviews (QBR) directly with HQ stakeholders.	Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	High-Level Risk Mitigation	R4		Excellent at identifying operational risks and managing audit compliance.	Standardize risk frameworks across all business units.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Mergers & Acquisitions (M&A)	R2	X	Limited experience in valuation or due diligence for expansion projects.	Shadow the FD during factory expansion (Phase 2) financial modeling.	Q2–Q3	Project June 2026.	Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Succession Management	R3	X	Has identified successors (Ha/Maya); needs to focus on delegating high-level tasks.	Formally mentor Ha Nguyen for full FA Manager responsibilities.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Global Compliance & Tax Strategy	R4		Expert in local CIT, PIT, and VAT; strong grasp of international standards.	Oversee the 2024 AFS restatements and 2025 audit finalization.	Q1–Q2	Completed/Ongoing.	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Change Management	R3		Good at managing stable teams; needs to lead through major organizational shifts.	Drive the financial integration of new ERP or DLP security systems.	Q3–Q4		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Executive Communication	R3	X	"Clear and professional; needs to focus on ""influencing"" rather than just ""informing."""	Attend executive leadership coaching to refine negotiation skills.	Q2–Q4		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development-Windy
50280	Windy Sy	FINANCE & ACCOUNTING	FA manager	Investment & Treasury	R4		Proven track record in managing loan compliance and cash flow forecasting.	Optimize interest rate hedging and debt repayment strategies.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Windy
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Advanced Business Analysis	R4		Excellent at performance analysis and data interpretation.	Lead the development of the new financial dashboard for 2026.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Maya
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Tax & Compliance Management	R4		High proficiency in VAT, PIT, CIT, and WHT declarations.	Act as the primary point of contact for external auditors (PwC/EY).	Q1–Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Maya
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Fixed Assets & Inventory Control	R4		Strong grasp of MRO and asset management processes.	Streamline the inventory tracking process for the factory expansion.	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Maya
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Assistant Management Tasks	R2	X	Great technical skills but needs more experience in overseeing the whole finance ops.	Shadow Ha Nguyen in reviewing internal controls and daily operations.	Q2–Q4	Succession focus.	Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Maya
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Intercompany Loan & Interest	R3	X	Familiar with the process; needs more autonomy in managing complex renewals.	Take full ownership of the intercompany loan documentation for Q3.	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Maya
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Problem Solving & Decision Making	R3	X	Capable of solving technical issues; needs to improve speed in operational decisions.	Handle lower-level operational approvals under Ha's supervision.	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Readiness Development-Maya
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Strategic Communication	R3	X	Clear in reporting; needs to adapt communication style for cross-departmental leaders.	Present the monthly Business Performance analysis to Mr. Karl/Bob.	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Maya
50462	Maya Nguyen	FINANCE & ACCOUNTING	BA	Team Collaboration & Support	R4		Very supportive; plays a key role in connecting different finance sections.	Lead the cross-training sessions for Helen and Cheryl on Tax basics.	Q3		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Maya
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	General Ledger & Month-end Close	R4		Highly efficient in managing accruals and salary variance recording.	Lead the month-end closing process for the entire Finance Ops team.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	Payroll & Operating Expenses	R4		Primary for local charges; ensures accuracy in payroll accounting.	Standardize payroll reconciliation templates for faster processing.	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	E-invoicing & AP/AR Reconciliation	R4		Very strong in managing AP/AR and issuing e-invoices.	Train Cheryl as a backup for this function to reduce dependency.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	Tax Declaration Support	R2	X	Familiar with basic tax, but needs to learn VAT/PIT/CIT filing from Maya.	Shadow Maya during the next quarterly tax declaration cycle.	Q2–Q3	Succession focus.	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	Financial Analysis (Basic)	R2	X	Strong with numbers; needs to develop skills in analyzing variance trends.	Assist Maya in preparing the Business Performance monthly deck.	Q3		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	Internal Process Improvement	R3	X	Consistently follows SOPs; should identify ways to automate routine GL tasks.	Propose a more efficient way to track and record monthly accruals.	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	Cross-functional Coordination	R3	X	Communicates well with other departments; needs to lead inter-departmental meetings.	Act as the primary finance contact for the HR and Admin departments.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	Mentoring & Training	R2	X	Great technical performer; needs to build confidence in coaching junior members.	"Develop a ""Quick Guide"" for GL accounting for the rest of the team."	Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development-Helen
50842	Helen Ngo	FINANCE & ACCOUNTING	GL Accountant	Technical English (Accounting)	R3		Competent in reading terms; needs to practice speaking for professional emails.	Practice drafting financial summaries in English for the Assistant Manager.	Q1–Q4		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Helen
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Payment Execution & Management	R4		High precision in executing payments and managing loan documentation.	Standardize the intercompany loan renewal tracking system.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Cash Flow Forecasting	R4		Strong ability to predict short-term cash needs and treasury reporting.	Integrate factory expansion (Phase 2) requirements into the cash forecast.	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	AFE Projects & Vendor Master Data	R4		Expert in managing project spending and vendor information.	Develop a dashboard to track AFE spending vs. budget in real-time.	Q2–Q3		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Business Performance Analysis	R2	X	Good with numbers; needs to learn how to translate data into business insights.	Shadow Maya to learn how to analyze ROI for new projects.	Q3–Q4	Succession focus.	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Financial Modeling (Basic)	R2	X	Familiar with Excel; needs to build models for long-term debt or investment.	Assist the Assistant Manager in updating the 10-year debt strategy file.	Q2–Q3		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Inventory & Fixed Assets Support	R3	X	Understands basic concepts; needs to handle MRO and asset counts independently.	Cross-train with Maya on monthly inventory reconciliation processes.	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Audit Preparation & Support	R3		Reliable in providing documents; needs to lead specific audit areas (e.g., AP/Cash).	Take lead responsibility for the Cash and Bank section in the 2025 audit.	Q1–Q2	Ongoing.	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Communication & Negotiating	R3	X	Communicates clearly; needs to practice negotiation with vendors or banks.	Lead discussions with banks regarding loan documentation and renewals.	Q3–Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development-Cheryl
50630	Cheryl Nguyen	FINANCE & ACCOUNTING	GL Accountant	Leadership Mindset	R2	X	Strong task-focus; needs to develop a broader view of how finance supports Ops.	"Participate in cross-departmental ""Phase 2"" planning meetings."	Q2–Q3		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development-Cheryl
50884	River Le	INFORMATION SYSTEM	IT Technician	"Incident Handling (Incident)
Xử lý sự cố"	N/A	X	"Not deeply knowledgeable, but possessing broad knowledge across many fields.
Kiến thức chưa chuyên sâu nhưng có hiểu biết rộng ở nhiều lĩnh vực.
Demonstrates strong ownership in incident handling, with the ability to independently resolve issues and proactively coordinate with relevant teams to ensure efficient resolution.
Thể hiện tinh thần trách nhiệm cao trong việc xử lý sự cố, có khả năng tự giải quyết vấn đề và chủ động phối hợp với các nhóm liên quan để đảm bảo giải quyết vấn đề hiệu quả."	"Maintain execution discipline
Duy trì tính kỷ luật trong thực thi công việc"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"Hardware & Device Management
Quản lý thiết bị & phần cứng"	N/A	X	"Willing but lacks structured coaching skills
Có tinh thần học hỏi nhưng thiếu kỹ năng đào tạo/hướng dẫn bài bản.
Proactively maintains and updates asset inventory, ensuring accuracy and alignment with device allocation and changes in hardware distribution
Chủ động duy trì và cập nhật kho tài sản, đảm bảo tính chính xác và phù hợp với việc phân bổ thiết bị và những thay đổi trong phân phối phần cứng."	"Continue to learn and improve your skills.
Tiếp tục học hỏi và nâng cao kỹ năng"	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"Network Troubleshooting
Xử lý sự cố mạng"	N/A	X	"Willing but lacks structured coaching skills
Có tinh thần học hỏi nhưng thiếu định hướng đào tạo bài bản.
Demonstrates basic root cause analysis capability in network-related incidents; however, further hands-on experience is required to strengthen advanced troubleshooting skills.
Thể hiện khả năng phân tích nguyên nhân gốc rễ cơ bản trong các sự cố liên quan đến mạng; tuy nhiên, cần thêm kinh nghiệm thực tế để nâng cao kỹ năng khắc phục sự cố chuyên sâu."	"Focus on understanding how to configure Network Phase 2.
Tập trung hiểu và thực hành cấu hình mạng (Network Phase 2)"	Q1-Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"System Administration (AD, File Server)
Quản trị hệ thống (AD, File Server)"	N/A		"know the basics but have little practical experience.Careful, meticulous
Nắm được kiến thức cơ bản nhưng thiếu kinh nghiệm thực tế; làm việc cẩn thận, tỉ mỉ.
Should enhance collaboration with the server team, particularly in backup and recovery scenarios, to improve end-to-end system troubleshooting capability.
Cần tăng cường hợp tác với nhóm máy chủ, đặc biệt là trong các kịch bản sao lưu và phục hồi dữ liệu, để nâng cao khả năng khắc phục sự cố hệ thống từ đầu đến cuối."	"Continue to learn and improve your skills.
Tiếp tục học hỏi và nâng cao kỹ năng"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"IT Asset Management
Quản lý tài sản IT"	N/A		"Careful, meticulous
Làm việc cẩn thận, tỉ mỉ.
Demonstrates strong ownership in asset management by maintaining accurate tracking data and showing good understanding of hardware specifications and system-related performance metrics.
Thể hiện tinh thần trách nhiệm cao trong quản lý tài sản bằng cách duy trì dữ liệu theo dõi chính xác và hiểu biết tốt về thông số kỹ thuật phần cứng cũng như các chỉ số hiệu suất liên quan đến hệ thống."	"Maintain execution discipline
Duy trì tính kỷ luật trong thực thi công việc"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"Preventive Maintenance
Bảo trì định kỳ"	N/A	X	"Strong execution; needs more strategic planning
Khả năng thực thi tốt nhưng cần cải thiện tư duy lập kế hoạch mang tính chiến lược.
Should further strengthen strategic planning capability in preventive maintenance, including proactive scheduling, cross-team alignment, and structured reporting to management.
Cần tăng cường hơn nữa năng lực lập kế hoạch chiến lược trong bảo trì phòng ngừa, bao gồm lập lịch chủ động, sự phối hợp giữa các nhóm và báo cáo có cấu trúc cho ban quản lý."	"Continue to learn and improve your skills.
Tiếp tục học hỏi và nâng cao kỹ năng"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"IT Documentation & SOP
Tài liệu IT & SOP"	N/A		"Review existing SOPs, and write new SOPs when new errors are discovered.
Rà soát SOP hiện có và xây dựng SOP mới khi phát sinh lỗi mới.
Proactively updates and standardizes SOP documentation following major incidents, ensuring knowledge retention and supporting team scalability.
Chủ động cập nhật và chuẩn hóa tài liệu quy trình vận hành tiêu chuẩn (SOP) sau các sự cố lớn, đảm bảo việc lưu giữ kiến ​​thức và hỗ trợ khả năng mở rộng quy mô của nhóm."	"Continue best practices and share knowledge
Duy trì best practices và chia sẻ kiến thức"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"Security Awareness & Compliance
Nhận thức & tuân thủ bảo mật"	N/A		"Willing but lacks structured coaching skills
Có tinh thần học hỏi nhưng thiếu định hướng đào tạo bài bản.
Needs to strengthen coordination with the security team and improve understanding of security policies to enhance incident resolution effectiveness.
Cần tăng cường phối hợp với đội ngũ an ninh và nâng cao hiểu biết về các chính sách an ninh để tăng hiệu quả giải quyết sự cố."	"Continue to learn and improve your skills.
Tiếp tục học hỏi và nâng cao kỹ năng"	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"User Training & Support
Đào tạo & hỗ trợ người dùng"	N/A		"Actively supports people development
Chủ động hỗ trợ phát triển người dùng/đồng nghiệp.
Demonstrates strong ownership in user support by ensuring case follow-through; however, communication and training capabilities should be enhanced to improve user understanding and satisfaction.
Thể hiện tinh thần trách nhiệm cao trong việc hỗ trợ người dùng bằng cách đảm bảo theo dõi sát sao các trường hợp; tuy nhiên, cần tăng cường khả năng giao tiếp và đào tạo để nâng cao sự hiểu biết và sự hài lòng của người dùng."	"Continue to learn and improve your skills.
Tiếp tục học hỏi và nâng cao kỹ năng"	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	River Le
50884	River Le	INFORMATION SYSTEM	IT Technician	"AI Usage in Troubleshooting
Ứng dụng AI trong xử lý sự cố"	N/A		"Apply directly to real-life situations and work, and verify using external AI sources if available.
Có khả năng áp dụng vào thực tế công việc và xác thực thông tin từ nhiều nguồn AI khác nhau.
Shows strong initiative in applying AI tools in daily operations. Further development in automation and practical implementation is recommended to maximize efficiency and scalability
Thể hiện sự chủ động mạnh mẽ trong việc ứng dụng các công cụ AI vào hoạt động hàng ngày. Cần phát triển thêm về tự động hóa và triển khai thực tiễn để tối đa hóa hiệu quả và khả năng mở rộng."	"Continue to learn and improve your skills.
Tiếp tục học hỏi và nâng cao kỹ năng"	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	River Le
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	Application Support (Incident)	R4		Always support users on time.	Improve response time and ensure consistent user support.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	Bug Fixing & Troubleshooting	R4		Search for bugs and fix them promptly as soon as possible.	Enhance debugging efficiency and reduce issue resolution time.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	System Integration (API, DB)	R4	X	Always improve and upgrade the system to keep up with current work progress.	Improve integration reliability and ensure seamless data flow.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	Database Management	R4		Design, maintain, and optimize databases for performance and reliability.	Enhance performance, strengthen data security, and implement scalable database solutions.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	Software Development	R4	X	Develop, test, and improve applications with clean and efficient code.	Adopt best practices, improve code quality, and accelerate delivery with modern tools and AI support.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	Testing & QA	R3		Test the system before releasing the application to users.	Improve test coverage and automate testing to ensure system reliability.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	Documentation (Tech & User)	R3	X	Create and maintain clear technical and user documentation.	Streamline change processes, improve tracking, and minimize risks during system updates.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	Change Management	R3		Manage and track system changes to ensure smooth updates and stability.	Standardize documentation, keep it up-to-date, and improve accessibility for all user.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	AI Usage in Development	R4		Use AI as a powerful assistant in coding, Replace most of the time spent coding.	Leverage AI to boost productivity and reduce manual coding effort.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
50804	Harry Hoang	INFORMATION SYSTEM	Specialist	System Performance Optimization	R3	X	Find ways to optimize system operations and avoid stagnation.	Continuously optimize performance and prevent system bottlenecks.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harry Hoang
	Denis Vy			"Incident Handling (Incident)
Xử lý sự cố"	N/A	X	"Strong experience in handling daily incidents independently, able to prioritize and resolve issues effectively.
Có kinh nghiệm tốt trong việc xử lý sự cố hàng ngày một cách độc lập, có khả năng ưu tiên và giải quyết vấn đề hiệu quả.
Demonstrates the ability to independently resolve standard incidents. Should further strengthen proactive coordination with relevant teams before escalation to improve resolution efficiency and reduce unnecessary escalations
Thể hiện khả năng tự giải quyết các sự cố thông thường. Cần tăng cường hơn nữa sự phối hợp chủ động với các nhóm liên quan trước khi leo thang vấn đề để nâng cao hiệu quả giải quyết và giảm thiểu việc leo thang không cần thiết."	"Improve incident root cause analysis
Cải thiện phân tích nguyên nhân gốc (Root Cause Analysis)"	Ongoing	"Reviewing 100% of major incidents
Rà soát 100% các sự cố nghiêm trọng"	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Denis Vy
	Denis Vy			"Hardware & Device Management
Quản lý thiết bị & phần cứng"	N/A	X	"Able to manage and troubleshoot hardware devices effectively, including laptops, printers, and peripherals.
Có khả năng quản lý và xử lý sự cố thiết bị phần cứng hiệu quả, bao gồm laptop, máy in và thiết bị ngoại vi.
Needs to improve proactiveness in maintaining accurate and up-to-date asset inventory, especially when there are changes in device allocation or quantity.
Cần cải thiện tính chủ động trong việc duy trì kho tài sản chính xác và cập nhật, đặc biệt khi có sự thay đổi về phân bổ hoặc số lượng thiết bị."	"Standardize device management process
Learn asset automation tools
Improve preventive maintenance
- Chuẩn hóa quy trình quản lý thiết bị
- Học các công cụ tự động hóa quản lý tài sản
- Nâng cao công tác bảo trì định kỳ"	Ongoing	"Need better tracking system
Cần cải thiện hệ thống theo dõi (tracking)"	Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Denis Vy
	Denis Vy			"Network Troubleshooting
Xử lý sự cố mạng"	N/A	X	"Good understanding of basic networking but needs improvement in advanced troubleshooting (VLAN, routing, firewall).
Có nền tảng tốt về mạng cơ bản nhưng cần cải thiện ở các kỹ năng xử lý sự cố nâng cao (VLAN, routing, firewall).
Needs to enhance root cause analysis capability, particularly in network-related incidents, to improve troubleshooting effectiveness beyond basic issue resolution
Cần tăng cường khả năng phân tích nguyên nhân gốc rễ, đặc biệt là trong các sự cố liên quan đến mạng, để nâng cao hiệu quả khắc phục sự cố vượt ra ngoài việc giải quyết vấn đề cơ bản."	"Practice real network troubleshooting scenarios
Thực hành các tình huống xử lý sự cố mạng thực tế"	Ongoing	"Align with career path (Network Engineer)
Định hướng theo lộ trình Network Engineer"	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Denis Vy
	Denis Vy			"System Administration (AD, File Server)
Quản trị hệ thống (AD, File Server)"	N/A	X	"Strong basic knowledge in AD and file server but lacks advanced configuration experience.
Có kiến thức nền tảng tốt về AD và file server nhưng còn thiếu kinh nghiệm cấu hình nâng cao.
Should improve collaboration with the server team, particularly in backup and recovery scenarios, to strengthen end-to-end incident resolution capability
Cần tăng cường sự phối hợp với nhóm máy chủ, đặc biệt là trong các kịch bản sao lưu và phục hồi dữ liệu, để củng cố khả năng giải quyết sự cố từ đầu đến cuối."	"Practice user/group policy management,Learn backup & disaster recovery
- Thực hành quản lý user/group policy
- Học backup & disaster recovery"	Q3	"Need access to test environment
Cần được cấp quyền truy cập môi trường test"	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Denis Vy
	Denis Vy			"IT Asset Management
Quản lý tài sản IT"	N/A	X	"Able to manage IT assets but processes are mostly manual and not optimized.
Có khả năng quản lý tài sản IT nhưng quy trình còn thủ công, chưa tối ưu.
Should enhance ownership in asset management by maintaining accurate tracking data and developing a deeper understanding of hardware specifications and system-related metrics (e.g., bandwidth, performance indicators).
Cần tăng cường trách nhiệm trong quản lý tài sản bằng cách duy trì dữ liệu theo dõi chính xác và phát triển sự hiểu biết sâu sắc hơn về thông số kỹ thuật phần cứng và các chỉ số liên quan đến hệ thống (ví dụ: băng thông, chỉ số hiệu suất)."	"Implement asset tracking system (Excel/Tool)
Automate reporting
- Triển khai hệ thống quản lý tài sản (Excel/Tool)
- Tự động hóa báo cáo"	Q3	"Can integrate with Power Automate
Có thể tích hợp với Power Automate"	Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Denis Vy
	Denis Vy			"Preventive Maintenance
Bảo trì định kỳ"	N/A	X	"Currently performing preventive maintenance activities, however, the process is not yet fully structured or optimized.
Đã thực hiện bảo trì định kỳ nhưng quy trình chưa được chuẩn hóa và tối ưu.
Needs to improve ownership in planning and scheduling preventive maintenance activities, ensuring alignment across the team and providing clear, structured reporting to management.
Cần cải thiện tinh thần trách nhiệm trong việc lập kế hoạch và lên lịch các hoạt động bảo trì phòng ngừa, đảm bảo sự thống nhất trong toàn nhóm và cung cấp báo cáo rõ ràng, có cấu trúc cho ban quản lý."	"Develop a standardized preventive maintenance plan
Establish clear checklists and procedures
- Xây dựng kế hoạch bảo trì định kỳ chuẩn hóa
- Thiết lập checklist và quy trình rõ ràng"	Ongoing	"Aim to minimize system downtime and reduce incident frequency
Mục tiêu giảm downtime và tần suất sự cố"	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Denis Vy
	Denis Vy			"IT Documentation & SOP
Tài liệu IT & SOP"	N/A	X	"Documentation is available but not standardized and lacks detail.
Đã có tài liệu nhưng chưa chuẩn hóa và thiếu chi tiết.
Should proactively update and standardize SOP documentation following major incidents to ensure knowledge retention and support team scalability
Nên chủ động cập nhật và chuẩn hóa tài liệu quy trình vận hành tiêu chuẩn (SOP) sau các sự cố lớn để đảm bảo việc lưu giữ kiến ​​thức và hỗ trợ khả năng mở rộng quy mô của nhóm."	"Create SOP templates
Improve documentation clarity
- Xây dựng template SOP
- Cải thiện độ rõ ràng của tài liệu"	Ongoing	"Useful for team training
Hữu ích cho đào tạo nội bộ"	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Denis Vy
	Denis Vy			"Security Awareness & Compliance
Nhận thức & tuân thủ bảo mật"	N/A	X	"Currently have basic understanding of IT security concepts, with opportunity to further develop knowledge in security standards, policies, and compliance practices.
Có hiểu biết cơ bản về bảo mật IT, có tiềm năng phát triển thêm về tiêu chuẩn, chính sách và tuân thủ.
Needs to strengthen coordination with the security team and improve follow-through in incident resolution to avoid repeated escalations and enhance resolution efficiency
Cần tăng cường phối hợp với đội ngũ an ninh và cải thiện việc xử lý sự cố để tránh tình trạng leo thang sự cố lặp đi lặp lại và nâng cao hiệu quả giải quyết vấn đề."	"Participate in security incident handling and monitoring activities
Learn best practices in network and system security
- Tham gia xử lý & giám sát sự cố bảo mật
- Học best practices về security hệ thống & mạng"	Ongoing	"Key focus area for career growth toward Network/Security Engineer role
Trọng tâm phát triển cho hướng Network/Security Engineer"	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Denis Vy
	Denis Vy			"User Training & Support
Đào tạo & hỗ trợ người dùng"	N/A	X	"Strong ability to support users and provide clear guidance.
Có khả năng hỗ trợ người dùng tốt và hướng dẫn rõ ràng
Should improve case ownership by ensuring full follow-through until resolution. Additionally, communication and user training capabilities should be enhanced to improve user understanding and satisfaction.
Cần cải thiện trách nhiệm xử lý vụ việc bằng cách đảm bảo theo dõi sát sao cho đến khi giải quyết xong. Ngoài ra, cần tăng cường khả năng giao tiếp và đào tạo người dùng để nâng cao hiểu biết và sự hài lòng của người dùng."	"Improve communication skills
Create user guides
Conduct basic training sessions
- Cải thiện kỹ năng giao tiếp
- Xây dựng tài liệu hướng dẫn
- Tổ chức training cơ bản"	Q3	"Good soft skill advantage
Lợi thế về kỹ năng mềm"	Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Denis Vy
	Denis Vy			"AI Usage in Troubleshooting
Ứng dụng AI trong xử lý sự cố"	N/A	X	"Able to use AI tools but not fully optimized in troubleshooting scenarios.
Có khả năng sử dụng công cụ AI nhưng chưa tối ưu trong thực tế xử lý sự cố.
Demonstrates strong initiative in adopting and leveraging AI tools in daily operations. Further development in automation and practical application is recommended to maximize efficiency gains
Thể hiện sự chủ động mạnh mẽ trong việc áp dụng và tận dụng các công cụ AI vào hoạt động hàng ngày. Cần phát triển thêm về tự động hóa và ứng dụng thực tiễn để tối đa hóa hiệu quả."	"Use ChatGPT for log analysis
Build automation (Python / n8n)
Apply AI in incident handling
- Sử dụng ChatGPT để phân tích log
- Xây dựng automation (Python / n8n)
- Áp dụng AI trong xử lý sự cố"	Q3	"High potential area
Lĩnh vực tiềm năng cao"	Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Denis Vy
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	Incident Handling (Incident)	N/A	X	"They have knowledge in many areas, but not in depth.
Keep maintaining strong incident handling performance and ensure no SLA breaches. Use any available downtime to deepen your technical expertise and expand your professional knowledge
Tiếp tục duy trì hiệu suất xử lý sự cố ở mức cao và đảm bảo không vi phạm SLA. Tận dụng thời gian rảnh để nâng cao chuyên môn kỹ thuật và mở rộng kiến thức chuyên nghiệp"	continue to maintain and improve	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	Hardware & Device Management	N/A	X	"Willing but lacks structured coaching skills
Asset management is already supported by the fixed asset system; you are expected to proactively update it whenever there are any changes to IT equipment.
Việc quản lý tài sản đã được triển khai trên hệ thống Fix asset management; yêu cầu chủ động cập nhật kịp thời mọi thay đổi liên quan đến thiết bị IT để đảm bảo dữ liệu luôn chính xác và đầy đủ."	Learn and gain more practical experience.	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	Network Troubleshooting	N/A	X	"They lack a solid foundation of knowledge and need to do and learn more.
You are expected to build deeper expertise in networking, proactively coordinate with relevant teams when issues occur, and properly document key learnings after each training or resolved issue
Yêu cầu nâng cao chuyên môn chuyên sâu về network, chủ động phối hợp liên bộ phận khi xảy ra sự cố, và nên làm SOP đầy đủ các bài học kinh nghiệm sau mỗi lần đào tạo hoặc xử lý vấn đề nhằm phục vụ cho việc chia sẻ và cải tiến liên tục về sau."	Learn and gain more practical experience.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	System Administration (AD, File Server)	N/A	X	"They lack a solid foundation of knowledge and need to do and learn more.
Similar to networking, you are expected to further develop your knowledge in server systems. Build a solid understanding of basic Active Directory (AD) and be able to provide support to end users when needed
Nâng cao kiến thức server, nắm vững AD cơ bản và hỗ trợ end user khi cần."	Learn and gain more practical experience.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	IT Asset Management	N/A		"Careful, meticulous
Proactively learn and understand the service specifications from ISPs (VNPT, Viettel), as well as the current software licenses of the IT team, in order to effectively manage and provide support when needed
Yêu cầu chủ động nghiên cứu và hiểu rõ các thông số dịch vụ từ các nhà cung cấp ISP (VNPT, Viettel), đồng thời nắm vững tình trạng các license phần mềm của Team IT, nhằm đảm bảo công tác quản lý hiệu quả và hỗ trợ kịp thời khi phát sinh nhu cầu"	continue to maintain and improve	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	Preventive Maintenance	N/A		"To do well, we need more effective strategies.
Develop and implement a clear maintenance strategy.
Xây dựng và triển khai chiến lược bảo trì rõ ràng."	Learn and gain more practical experience.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	IT Documentation & SOP	N/A		"Add any missaing or incorrect information, and update the SOP.
Proactively update SOPs for critical issues and continuously refine solutions to minimize recurring incidents.
Chủ động cập nhật SOP cho các sự cố quan trọng và liên tục cải tiến giải pháp nhằm giảm thiểu các sự cố lặp lại"	continue to maintain and improve	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	Security Awareness & Compliance	N/A		"Willing but lacks structured coaching skills
Similar to networking, you are expected to proactively deepen your server knowledge to enhance your technical expertise. For example, you should take the initiative to enroll in and complete relevant courses through available IT learning platforms such as Udemy
Tương tự lĩnh vực mạng, yêu cầu chủ động nâng cao kiến thức chuyên sâu về hệ thống server nhằm gia tăng năng lực kỹ thuật. Chủ động tham gia và hoàn thành các khóa đào tạo liên quan trên các nền tảng học tập IT (ví dụ: Udemy) để phục vụ cho việc phát triển năng lực lâu dài."	Learn and gain more practical experience.	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	User Training & Support	N/A	X	"Actively cooperate and make corrections when users need them.
Enhance your communication skills and actively provide IT-related training to end users
Nâng cao kỹ năng giao tiếp và chủ động triển khai các buổi đào tạo liên quan đến IT cho người dùng cuối."	continue to maintain and improve	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Ryder Nguyen
50655	Ryder Nguyen	INFORMATION SYSTEM	IT Technician	AI Usage in Troubleshooting	N/A		"Applying it to real-world situations and considering it from multiple perspectives beyond AI.
Proactively stay updated with AI developments and deepen your understanding of AI to better support the IT team and improve overall work efficiency
Chủ động cập nhật các xu hướng phát triển về AI và nâng cao hiểu biết về AI nhằm hỗ trợ hiệu quả cho Team IT và cải thiện hiệu suất công việc tổng thể."	Learn and gain more practical experience.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ryder Nguyen
	Henry Le / Logistics Team	LOGISTICS		Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Ramp Plan Execution	R4		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Resource Development (Human)	R4		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Recruitment Plan Development	R3	X	Strong execution; needs more strategic planning	Build annual recruitment plan	Q2–Q3	Align with manpower plan	Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Recruitment Execution	R3		Executes hiring well; improve metrics usage	Strengthen recruitment analytics	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Building and Promoting a Company Culture	R4		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2–Q3	Use GROW model	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Henry Le / Logistics Team	LOGISTICS		Employee Relations Improvement	R4		Handles ER cases effectively	Share ER best practices	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Ramp Plan Execution	R4		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Resource Development (Human)	R4		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Recruitment Plan Development	R3	X	Strong execution; needs more strategic planning	Build annual recruitment plan	Q2–Q3	Align with manpower plan	Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Recruitment Execution	R3		Executes hiring well; improve metrics usage	Strengthen recruitment analytics	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Building and Promoting a Company Culture	R4		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2–Q3	Use GROW model	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Shen Jim / Inventory Team	WAREHOUSE		Employee Relations Improvement	R4		Handles ER cases effectively	Share ER best practices	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Ramp Plan Execution	R4		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Resource Development (Human)	R4		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Recruitment Plan Development	R3	X	Strong execution; needs more strategic planning	Build annual recruitment plan	Q2–Q3	Align with manpower plan	Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Recruitment Execution	R3		Executes hiring well; improve metrics usage	Strengthen recruitment analytics	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Building and Promoting a Company Culture	R4		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2–Q3	Use GROW model	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Rita Hoang / Customs Team	CUSTOMS		Employee Relations Improvement	R4		Handles ER cases effectively	Share ER best practices	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Ramp Plan Execution	R4		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Resource Development (Human)	R4		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Recruitment Plan Development	R3	X	Strong execution; needs more strategic planning	Build annual recruitment plan	Q2–Q3	Align with manpower plan	Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Recruitment Execution	R3		Executes hiring well; improve metrics usage	Strengthen recruitment analytics	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Building and Promoting a Company Culture	R4		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2–Q3	Use GROW model	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Kim Tran / Warehouse Team	WAREHOUSE		Employee Relations Improvement	R4		Handles ER cases effectively	Share ER best practices	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Ramp Plan Execution	R4		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Resource Development (Human)	R4		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Recruitment Plan Development	R3	X	Strong execution; needs more strategic planning	Build annual recruitment plan	Q2–Q3	Align with manpower plan	Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Recruitment Execution	R3		Executes hiring well; improve metrics usage	Strengthen recruitment analytics	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Need Validation	Business Acumen Framework	Department / Functional SME	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Building and Promoting a Company Culture	R4		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2–Q3	Use GROW model	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Readiness Development Pl
	Trudy Dinh / CS Team	CUSTOMER SERVICE		Employee Relations Improvement	R4		Handles ER cases effectively	Share ER best practices	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Readiness Development Pl`;
