export const userCSV_part3 = `401,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
402,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
403,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
404,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
405,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
406,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
407,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
408,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
409,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
410,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
411,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
412,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
413,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
414,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
415,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
416,71510,Tran Minh Thuan,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
417,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
418,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
419,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
420,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
421,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
422,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
423,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
424,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
425,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
426,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
427,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
428,73229,Huynh Van Nhat,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
429,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
430,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
431,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
432,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
433,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
434,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
435,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
436,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
437,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
438,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
439,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
440,73200,Duong Tri Dung,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
441,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
442,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
443,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
444,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
445,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
446,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
447,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
448,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
449,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
450,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
451,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
452,71473,Ly Thanh Tung,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
453,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
454,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
455,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
456,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
457,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
458,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
459,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
460,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
461,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
462,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
463,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
464,24355,Tong Thi Sang,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
465,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
466,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
467,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
468,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
469,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
470,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
471,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
472,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
473,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
474,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
475,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
476,71460,Dang Van Tan,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
477,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
478,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
479,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
480,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
481,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
482,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
483,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
484,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
485,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
486,72611,Mai Hai Long,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
487,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
488,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
489,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
490,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
491,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
492,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
493,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
494,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
495,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
496,71318,Ngo Huu Chi,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
497,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
498,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
499,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
500,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
501,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
502,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
503,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
504,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
505,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
506,14441,Thuy Do,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
507,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
508,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
509,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
510,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
511,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
512,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
513,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
514,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
515,72596,Bui Van Thap,UPH Assembly WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
516,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
517,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
518,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
519,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
520,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
521,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
522,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
523,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
524,71295,Pham Dinh Tung,UPH Assembly WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
525,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
526,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
527,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
528,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
529,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
530,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
531,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
532,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
533,72583,Vo Chi Tinh,UPH Assembly WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
534,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
535,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
536,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
537,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
538,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
539,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
540,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
541,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Venus Le
542,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
543,24823,Kelvin Huynh,Cut&Sew WNK3,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Venus Le
544,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Develop & Maintain EHS Management System,R4,,EHS system is well maintained; alignment with international standards (ISO 45001/14001) can be further structured.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
545,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Conduct regular workplace safety audits,R4,,Audits are conducted systematically; implementing real-time compliance tracking dashboard can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
546,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Investigate workplace incidents and root cause analysis,R4,,Incident resolution is thorough; proactive corrective action tracking can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
547,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Coordinate environmental compliance (waste water/emissions),R4,,Emissions are monitored; local regulatory liaison capability can be further strengthened.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
548,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Drive hazard identification & risk assessment (HIRA),R3,X,Conducts assessments; cascading HIRA ownership to supervisors can improve.,Conduct EHS train-the-trainer workshops for supervisors; standardise hazard checklists,Q2,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
549,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Ensure fire safety compliance and emergency response,R4,,Drills are conducted; building emergency response team (ERT) capability is in progress.,Run monthly specialized training for ERT; coordinate with local fire department,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
550,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Implement 6S program across all workshops,R4,,6S standards are maintained; visual management and audit discipline can be updated.,Standardise 6S audit checklist; implement monthly visual awards for top lines,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
551,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Deliver safety induction training for new hires,R4,,Induction is completed; online safety learning modules can be further developed.,Develop interactive video safety modules; digitize new hire safety exams,Ongoing,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Venus Le
552,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Ensure hazardous chemical management compliance,R4,,Chemical storage is monitored; safety data sheets (SDS) visual standards can increase.,Standardise SDS boards across all storage locations; train chemical handlers,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
553,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Track and report EHS performance metrics,R3,X,Metrics are tracked; data-driven lag/lead indicator analytics needs development.,Present monthly EHS performance reports to Plant Manager; lead safety committee meetings,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Venus Le
554,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Conduct EHS team performance evaluations,R4,,Reviews completed; development-focused coaching can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
555,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Participate in corporate EHS alignment programs,R4,,Aligns with corporate requirements; leading cross-division safety forums can increase.,Facilitate monthly safety share sessions with other division EHS managers,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
556,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Manage industrial hygiene monitoring program,R3,X,Hygiene audits are scheduled; occupational health risk assessment needs structure.,Plan occupational health hygiene audit; implement ergonomic assessment for assembly lines,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
557,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Develop annual EHS budget and CAPEX forecast,R3,X,Understands cost structures; co-owning budget forecasts can increase.,Model next annual EHS CAPEX and OPEX budget scenarios; present to Plant Manager,Annual cycle,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
558,14470,Tom Nguyen,UPH Support WNK2,EHS AM,EHS Risk Assessment & Control Design,R3,X,EHS controls are maintained; risk mitigation planning can increase.,Support safety culture inside Server room; maintain clean desk & server cabinet,2026-05-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
559,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Strategic EHS Planning & Execution,R3,X,Delivers projects well; long-term infrastructure roadmap needs clear alignment with global standards.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
560,14470,Tom Nguyen,UPH Support WNK2,EHS AM,EHS SLA and Regulatory Governance,R3,X,Audit readiness is maintained; traceability documentation can be more structured.,"Standardize network configuration backups and policy change logs; store in centralized repository",2026-05-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
561,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Cross-functional Safety & Engineering Collaboration,R4,X,Collaborates well on requests; proactive engagement in business planning can increase.,"Participate in monthly planning with Plant Managers; align network deployment with layout changes",2026-06-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
562,14470,Tom Nguyen,UPH Support WNK2,EHS AM,C&B Team Coaching & Development,R4,X,Coaches team members; structured career development for analysts can improve.,Create skill development path for C&B Analyst; run monthly coaching,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
563,14470,Tom Nguyen,UPH Support WNK2,EHS AM,Budget Alignment & CAPEX Forecast,R4,X,Understands IT cost drivers; co-ownership of network CAPEX/OPEX budget should increase.,"Design network topology to optimize local resources, reduce bandwidth bottlenecks, and minimize WAN latency",Once Network project is designed,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
564,23351,Dominic Duong,UPH Support WNK2,QA AM,Strategic Quality Planning & Vision Translation,R3,X,Understands quality strategy at operational level; needs development in translating Director-level vision into dept action plans,Attend strategic planning sessions with TAT Director; co-develop annual quality roadmap,Q2Q3,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Venus Le
565,23351,Dominic Duong,UPH Support WNK2,QA AM,Audit Governance Framework Development,R3,,Familiar with existing frameworks; limited experience designing governance structures from scratch,Lead one governance review project with mentoring from TAT Director,Q3,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
566,23351,Dominic Duong,UPH Support WNK2,QA AM,KPI & Performance Dashboard Design,R3,,Able to use dashboards;  cascading KPIs,Build dept KPI dashboard aligned to Director's scorecard; review monthly,Q2Q4,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Venus Le
567,23351,Dominic Duong,UPH Support WNK2,QA AM,Culture of Quality & Accountability Leadership,R4,,Strong quality mindset; actively promotes standards and accountability within team,Continue best practices; coach direct reports on culture-building,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
568,23351,Dominic Duong,UPH Support WNK2,QA AM,SOP Audit & OBQ Inspection Oversight,R4,,Expert-level knowledge of SOP/OBQ systems; oversees with high independence,Maintain discipline; share expertise with new AM cohort,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
569,23351,Dominic Duong,UPH Support WNK2,QA AM,CAR / PAR Approval for Critical Defects,R3,,Approves routine CARs; developing confidence in systemic/customer-critical escalations,Shadow TAT Director on 35 critical CAR reviews; build decision framework,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
570,23351,Dominic Duong,UPH Support WNK2,QA AM,Versatility Matrix & Headcount Deployment,R4,,Effectively manages shift coverage and versatility planning across sections,Expand scope to include cross-division deployment planning,Ongoing,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Venus Le
571,23351,Dominic Duong,UPH Support WNK2,QA AM,Audit Documentation & Traceability Standards,R4,X,Maintains high discipline in version control and audit traceability,Mentor Lead Supervisors on documentation standards,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
572,23351,Dominic Duong,UPH Support WNK2,QA AM,Product Quality Project Governance,R3,,Solid execution; needs to demonstrate clear understanding of full end-to-end project governance model.,Lead 1-3  full Product Quality Project cycle as project owner,Q3Q4,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
573,23351,Dominic Duong,UPH Support WNK2,QA AM,Senior Customer Quality Meeting Leadership,R2,,Participates in customer meetings; needs development in leading executive-level discussions independently,Co-lead weekly US customer meetings with TAT Director; take solo lead,Q2Q4,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
574,23351,Dominic Duong,UPH Support WNK2,QA AM,Customer Escalation Response & Communication,R3,X,Responds to standard escalations well,,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
575,23351,Dominic Duong,UPH Support WNK2,QA AM,Formal Quality Report & Dashboard Presentation,R3,,Builds reports competently; presentation narrative at executive level in development,Present monthly quality report to Dir once per quarter; receive structured feedback,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
576,23351,Dominic Duong,UPH Support WNK2,QA AM,Cross-Functional Collaboration (IE / CI / WH / Logistics),R4,,Strong relationship with cross-functional teams; drives joint quality controls effectively,Expand influence to Logistics and FI/QC; lead monthly cross-functional quality sync,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
577,23351,Dominic Duong,UPH Support WNK2,QA AM,Predictive Risk Control & Defect Analytics,R3,X,Uses historical data well; FMEA and process capability analytics need further development,Complete advanced FMEA training; apply on 2 pilot run reviews this year,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
578,23351,Dominic Duong,UPH Support WNK2,QA AM,Talent Pipeline Building & Succession Planning,R3,,Strong individual coaching skills; competency framework and succession planning need structure,Co-develop TAT succession map with HR Head; identify 2 AM-ready candidates by Q3,Q2Q3,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
579,23351,Dominic Duong,UPH Support WNK2,QA AM,Training Roadmap & Competency Framework Design,R3,,Delivers effective on-the-job training; formal competency framework design is new territory,Develop TAT Competency Framework for Auditor-to-AM pipeline; pilot Q3,Q3Q4,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
580,23351,Dominic Duong,UPH Support WNK2,QA AM,Headcount Planning & Workforce Strategy,R4,,Demonstrates strong workforce planning aligned to production volume and complexity,Lead annual HC planning for next cycle; present to TAT Director for approval,Annual cycle,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
581,23351,Dominic Duong,UPH Support WNK2,QA AM,Performance Evaluation & PDMS Oversight,R4,,Conducts thorough performance reviews; strong in PDMS administration,Standardize PDMS process across all AM reports; train new AMs,Q2 & Q4,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
582,23351,Dominic Duong,UPH Support WNK2,QA AM,Recruitment & Retention Strategy,R3,,Good at identifying talent; structured retention strategy needs development,Build TAT retention plan with HR; implement 1 key retention initiative by Q3,Q2Q3,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
583,23351,Dominic Duong,UPH Support WNK2,QA AM,Lean / Kaizen / 6S Program Leadership,R4,,Leads 6S programs effectively; Kaizen facilitation skills are strong,Lead enterprise Kaizen event this year; document and share outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
584,23351,Dominic Duong,UPH Support WNK2,QA AM,Audit System Digitalization & Modernization,R2,X,Aware of digital audit tools; needs to focus more on leading full-scale system digitalization,Lead pilot digitalization of 1 audit system (SOP or OBQ); present roadmap,Q3Q4,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
585,23351,Dominic Duong,UPH Support WNK2,QA AM,Quality Cost Reduction Initiatives,R3,,Contributes to cost reduction; needs more ownership over program,Own 1-3  quality cost reduction initiative end-to-end; report  results quarterly,Q2Q4,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
586,23351,Dominic Duong,UPH Support WNK2,QA AM,Improvement KPI Measurement & Reporting,R3,,Tracks KPIs at team level; needs to develop enterprise-level improvement reporting,Build monthly improvement KPI report; present to Director and cross-functional heads,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
587,23351,Dominic Duong,UPH Support WNK2,QA AM,Annual Budget Development & Management,R3,,Understands budget structure;,Co-own next annual budget submission with TAT Director; attend all finance reviews,Annual cycle,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
588,23351,Dominic Duong,UPH Support WNK2,QA AM,Executive Quality Status Reporting,R3,,Produces solid team-level reports; executive-level reporting narrative can be further developed,Draft monthly Director report; receive structured feedback on executive communication style,Ongoing,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Venus Le
589,23351,Dominic Duong,UPH Support WNK2,QA AM,Trend Analysis & Performance Dashboard for Stakeholders,R3,,Strong data skills; stakeholder-facing dashboard design needs practice,Design and own TAT performance dashboard presented to senior leadership monthly,Q2Q3,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Venus Le
590,23351,Dominic Duong,UPH Support WNK2,QA AM,Critical Quality Event Escalation & Impact Assessment,R4,,Responds swiftly to critical events; escalation communication with business impact framing is solid,Continue current standard; coach AM team on escalation protocols,Ongoing,,Business Acumen,Business Acumen,Department Follow-up,Business Acumen Framework,Department / Functional SME,Venus Le
591,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
592,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
593,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
594,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
595,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
596,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
597,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
598,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Venus Le
599,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
600,18501,Mai Thi Hoang Bich Tram,UPH Support WNK2,QA Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Venus Le`;
