export const userCSV_part2 = `201,78493,Willy Pham,IT,Network & Telecom AM,Network Topology & Architecture Governance,R4,,Topology designs are stable; standardizing patterns across divisions can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
202,78493,Willy Pham,IT,Network & Telecom AM,Information Security Control Implementation,R4,,Security controls are in place; threat posture analysis can go deeper.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
203,78493,Willy Pham,IT,Network & Telecom AM,Network Capacity Planning & Performance Monitoring,R4,,Performance is reliable; proactive resource utilization forecasts can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Jonathan To
204,78493,Willy Pham,IT,Network & Telecom AM,Telecom System Governance & Optimization,R4,,Systems are stable; routing and trunks cost optimization should be reviewed.,"Release for team/sub handle, monitoring only",,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
205,78493,Willy Pham,IT,Network & Telecom AM,EHS Controls in Server Room & Workplace,R4,X,EHS controls are maintained; risk mitigation planning can increase. ,Support safety culture inside Server room; maintain clean desk & server cabinet,2026-05-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
206,78493,Willy Pham,IT,Network & Telecom AM,Disaster Recovery Strategy & Incident Management,R4,,Incident resolution is fast; DR simulations need stronger ownership.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
207,78493,Willy Pham,IT,Network & Telecom AM,IT Asset Management & Compliance,R4,,Inventory is accurate; software license compliance audits should be formalized.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
208,78493,Willy Pham,IT,Network & Telecom AM,Network Engineering Team Mentoring,R4,,Provides good mentoring; coaching on advanced tech skills should be more structured.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Jonathan To
209,78493,Willy Pham,IT,Network & Telecom AM,Budgeting & IT Cost Optimization,R3,X,Understands IT cost drivers; co-ownership of network CAPEX/OPEX budget should increase.,"Design network topology to optimize local resources, reduce bandwidth bottlenecks, and minimize WAN latency",Once Network project is designed,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Jonathan To
210,78493,Willy Pham,IT,Network & Telecom AM,Vendor SLA Governance & Management,R4,,SLA monitoring is stable; contract negotiations can be more proactive.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
211,78493,Willy Pham,IT,Network & Telecom AM,Strategic Infrastructure Planning & Execution,R4,,Delivers projects well; long-term infrastructure roadmap needs clear alignment with global standards.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
212,78493,Willy Pham,IT,Network & Telecom AM,Stakeholder Communication & Project Portfolio Updates,R4,,Updates are clear; executive status reports can be more concise and highlight key risks.,,,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Jonathan To
213,78493,Willy Pham,IT,Network & Telecom AM,Audit Documentation & Traceability Standards,R4,X,Audit readiness is maintained; traceability documentation can be more structured.,"Standardize network configuration backups and policy change logs; store in centralized repository",2026-05-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
214,78493,Willy Pham,IT,Network & Telecom AM,Collaborative Planning & Cross-Functional Sync (IE / CI / Ops),R4,X,Collaborates well on requests; proactive engagement in business planning can increase.,"Participate in monthly planning with Plant Managers; align network deployment with layout changes",2026-06-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
215,78493,Willy Pham,IT,Network & Telecom AM,Succession Pipeline Development,R3,X,Coaches team members; formal competency frameworks for successors need development.,Develop skill map for Senior Network Engineer; run monthly 1-on-1 coaching sessions,,Successor path is defined but needs structured development plan,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Jonathan To
216,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
217,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
218,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
219,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
220,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
221,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
222,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
223,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Venus Le
224,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
225,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Venus Le
226,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
227,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
228,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Manage line capacity and headcount deployment,R3,X,Manages line headcount; line balancing under layout changes needs development.,Optimize operator placement; adjust line balancing using time study data,Q2Q3,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
229,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Build team morale and resolve line conflicts,R3,X,Resolves conflicts; structured team-building activities can increase.,Run monthly team sync; recognize top operators; resolve conflicts using active listening,Ongoing,,Functional,Employee Relations,Department Follow-up,Employee Relations Follow-up,HRBP / Department,Venus Le
230,24867,Chivas Cao,Cut&Sew WNK3,Lead Supervisor,Monitor operator learning curve and performance,R3,X,Tracks performance; coaching plan for underperforming operators needs structure.,Create 30-60-90 day operator training roadmap; provide weekly feedback,Q2,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Venus Le
231,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Server & Network Infrastructure Governance,R4,,Topology designs are stable; standardizing patterns across divisions can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
232,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Security Access & Information Protection,R4,,Security controls are in place; threat posture analysis can go deeper.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
233,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,System Performance & Resource Monitoring,R4,,Performance is reliable; proactive resource utilization forecasts can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Jonathan To
234,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Systems Service SLA Oversight,R4,,Systems are stable; routing and trunks cost optimization should be reviewed.,"Release for team/sub handle, monitoring only",,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
235,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,EHS Protocols in Server Rooms & Offices,R4,X,EHS controls are maintained; risk mitigation planning can increase.,Support safety culture inside Server room; maintain clean desk & server cabinet,2026-05-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
236,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,DR / Business Continuity Simulation,R4,,Incident resolution is fast; DR simulations need stronger ownership.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
237,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,IT Asset Portfolio Management,R4,,Inventory is accurate; software license compliance audits should be formalized.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
238,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Infrastructure Technical Coaching,R4,,Provides good mentoring; coaching on advanced tech skills should be more structured.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Jonathan To
239,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Budget Alignment & CAPEX Forecast,R3,X,Understands IT cost drivers; co-ownership of network CAPEX/OPEX budget should increase.,"Design network topology to optimize local resources, reduce bandwidth bottlenecks, and minimize WAN latency",Once Network project is designed,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Jonathan To
240,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Service Partner & Vendor Governance,R4,,SLA monitoring is stable; contract negotiations can be more proactive.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
241,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Long-term Infrastructure Strategy & Projects,R4,,Delivers projects well; long-term infrastructure roadmap needs clear alignment with global standards.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
242,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Portfolio Status Updates & Reporting,R4,,Updates are clear; executive status reports can be more concise and highlight key risks.,,,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Jonathan To
243,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Traceability & Audit Readiness Standards,R4,X,Audit readiness is maintained; traceability documentation can be more structured.,"Standardize network configuration backups and policy change logs; store in centralized repository",2026-05-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
244,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Cross-functional Layout & Engineering Sync,R4,X,Collaborates well on requests; proactive engagement in business planning can increase.,"Participate in monthly planning with Plant Managers; align network deployment with layout changes",2026-06-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
245,13405,Lucian Nguyen,IT,IT Infrastructure Lead Supervisor,Infrastructure Successor Development,R3,X,Coaches team members; formal competency frameworks for successors need development.,Develop skill map for Senior Network Engineer; run monthly 1-on-1 coaching sessions,,Successor path is defined but needs structured development plan,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Jonathan To
246,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,Workplace Harassment Investigation,R4,X,Adheres to guidelines; handling complex emotional escalations can improve.,Shadow HR Head on investigation meetings; learn active listening,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
247,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,EHS Risk Assessment,R4,,Proactive in EHS; risk assessment templates can be updated.,Improve risk mapping and safety controls on floor,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
248,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,Retention Strategy & Action Planning,R3,X,Analyzes turnover data; translating data into actionable plans can improve.,"Develop retention plan for high-turnover depts; run stay interviews, design intervention plan",Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
249,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,Department Restructuring & Org Design,R3,,Understands org structure; managing restructuring communication can go deeper.,"Prepare org design maps; co-facilitate restructuring workshops with HR Head",Q3,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Amber Dinh
250,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,Talent Assessment & Performance Oversight,R4,,Conducts reviews effectively; coaching managers on assessment biases can improve.,Standardize assessment reviews; train new HRBPs on bias mitigation,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
251,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,Training Needs Analysis (TNA) & Program Design,R4,,Good at basic TNA; designing competency-based programs can be further structured.,Develop competency map for key roles; design structured learning paths,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
252,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,Recruitment Operations & Vendor Control,R4,,Maintains target levels; recruitment agency vendor SLA controls can increase.,Optimize agency partner SLA terms and monitoring process,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
253,18500,Tuan Nguyen,Human Resources,HRBP Assistant Manager,Succession Pipeline Development,R3,X,Coaches team members; formal competency frameworks for successors need development.,Develop skill map for Senior HRBP; run monthly 1-on-1 coaching sessions,,Successor path is defined but needs structured development plan,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
254,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,Workplace Harassment Investigation,R4,X,Adheres to guidelines; handling complex emotional escalations can improve.,Shadow HR Head on investigation meetings; learn active listening,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
255,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,EHS Risk Assessment,R4,,Proactive in EHS; risk assessment templates can be updated.,Improve risk mapping and safety controls on floor,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
256,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,Retention Strategy & Action Planning,R3,X,Analyzes turnover data; translating data into actionable plans can improve.,"Develop retention plan for high-turnover depts; run stay interviews, design intervention plan",Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
257,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,Department Restructuring & Org Design,R3,,Understands org structure; managing restructuring communication can go deeper.,"Prepare org design maps; co-facilitate restructuring workshops with HR Head",Q3,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Amber Dinh
258,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,Talent Assessment & Performance Oversight,R4,,Conducts reviews effectively; coaching managers on assessment biases can improve.,Standardize assessment reviews; train new HRBPs on bias mitigation,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
259,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,Training Needs Analysis (TNA) & Program Design,R4,,Good at basic TNA; designing competency-based programs can be further structured.,Develop competency map for key roles; design structured learning paths,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
260,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,Recruitment Operations & Vendor Control,R4,,Maintains target levels; recruitment agency vendor SLA controls can increase.,Optimize agency partner SLA terms and monitoring process,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
261,16860,Quyen Lam,Human Resources,HRBP Assistant Manager,Succession Pipeline Development,R3,X,Coaches team members; formal competency frameworks for successors need development.,Develop skill map for Senior HRBP; run monthly 1-on-1 coaching sessions,,Successor path is defined but needs structured development plan,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
262,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,Compensation Structure Review & Design,R3,X,Understands grade structures; designing benchmark-aligned grade ranges needs guidance.,Co-develop next-cycle grade structures with Total Rewards Manager; utilize market survey data,Q2Q3,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Amber Dinh
263,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,Benefit Program Evaluation & Redesign,R4,,Evaluates benefits competently; employee wellness benefit redesign is in progress.,Lead wellness benefit program redesign project this year; track feedback,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
264,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,Job Evaluation & Grading Governance,R3,,Applies grading guidelines; grading of non-standard/niche roles needs development.,Shadow TR Manager on 1-3  grading panels for specialized tech positions,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
265,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,Payroll & Compliance Operations,R4,,Payroll operations are stable; payroll compliance audits should be conducted.,Run monthly internal payroll compliance audits; coordinate with Legal,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
266,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,Annual Salary Review & Merit Cycle,R3,,Coordinates merit cycles effectively; merit budget modeling needs development.,Model next-cycle merit budget under 3 cost scenarios; present to TR Manager,Q2,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Amber Dinh
267,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,Total Rewards System Automation,R3,,Uses HR systems competently; leading system modernization projects is new territory.,Lead pilot modernization of 1 compensation workflow on HR system,Q3Q4,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Amber Dinh
268,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,C&B Team Coaching & Development,R4,,Coaches team members; structured career development for analysts can improve.,Create skill development path for C&B Analyst; run monthly coaching,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
269,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,TR Vendor SLA Governance,R4,,SLA monitoring is stable; partner contract renegotiations can be proactive.,Coordinate with TR vendors on annual SLA reviews; identify cost-saving options,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
270,51461,Hana Truong,Human Resources,Total Rewards Lead Supervisor,Internal Equity Audit,R3,X,Identifies pay gaps; systemic equity audits across divisions need more structure.,Plan and run gender and tenure internal equity audit; draft corrective plan,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
271,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,Compensation Structure Review & Design,R3,X,Understands grade structures; designing benchmark-aligned grade ranges needs guidance.,Co-develop next-cycle grade structures with Total Rewards Manager; utilize market survey data,Q2Q3,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Amber Dinh
272,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,Benefit Program Evaluation & Redesign,R4,,Evaluates benefits competently; employee wellness benefit redesign is in progress.,Lead wellness benefit program redesign project this year; track feedback,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
273,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,Job Evaluation & Grading Governance,R3,,Applies grading guidelines; grading of non-standard/niche roles needs development.,Shadow TR Manager on 1-3  grading panels for specialized tech positions,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
274,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,Payroll & Compliance Operations,R4,,Payroll operations are stable; payroll compliance audits should be conducted.,Run monthly internal payroll compliance audits; coordinate with Legal,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
275,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,Annual Salary Review & Merit Cycle,R3,,Coordinates merit cycles effectively; merit budget modeling needs development.,Model next-cycle merit budget under 3 cost scenarios; present to TR Manager,Q2,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Amber Dinh
276,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,Total Rewards System Automation,R3,,Uses HR systems competently; leading system modernization projects is new territory.,Lead pilot modernization of 1 compensation workflow on HR system,Q3Q4,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Amber Dinh
277,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,C&B Team Coaching & Development,R4,,Coaches team members; structured career development for analysts can improve.,Create skill development path for C&B Analyst; run monthly coaching,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Amber Dinh
278,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,TR Vendor SLA Governance,R4,,SLA monitoring is stable; partner contract renegotiations can be proactive.,Coordinate with TR vendors on annual SLA reviews; identify cost-saving options,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
279,,Ginta Doan,Human Resources,Total Rewards Lead Supervisor,Internal Equity Audit,R3,X,Identifies pay gaps; systemic equity audits across divisions need more structure.,Plan and run gender and tenure internal equity audit; draft corrective plan,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Amber Dinh
280,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
281,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
282,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
283,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
284,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
285,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
286,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
287,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Venus Le
288,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
289,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Venus Le
290,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
291,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
292,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Manage line capacity and headcount deployment,R3,X,Manages line headcount; line balancing under layout changes needs development.,Optimize operator placement; adjust line balancing using time study data,Q2Q3,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
293,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Build team morale and resolve line conflicts,R3,X,Resolves conflicts; structured team-building activities can increase.,Run monthly team sync; recognize top operators; resolve conflicts using active listening,Ongoing,,Functional,Employee Relations,Department Follow-up,Employee Relations Follow-up,HRBP / Department,Venus Le
294,24867,Anna Tran,Cut&Sew WNK3,Lead Supervisor,Monitor operator learning curve and performance,R3,X,Tracks performance; coaching plan for underperforming operators needs structure.,Create 30-60-90 day operator training roadmap; provide weekly feedback,Q2,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Venus Le
295,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Supervise preventive maintenance compliance,R3,,Ensures basic PM; proactive audit on PM quality can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
296,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Maintain critical spare parts inventory,R3,,Tracks inventory; safety stock calculations based on consumption data can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
297,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Resolve mechanical / electrical breakdowns,R4,,Breakdowns are resolved quickly; structured root cause documentation can go deeper.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
298,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Conduct machine safety inspections,R3,,Inspections are consistent; compliance tracking of safety action items can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
299,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Manage technician shifts and attendance,R3,,Schedules shifts well; cross-skilling plan for tech coverages can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
300,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Control repair and spare parts cost,R3,,Monitors costs; local sourcing and parts repair initiatives can be further structured.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
301,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Implement 6S in maintenance workshop,R3,,Workshop is organized; Daily team accountability of 6S standards can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
302,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Train technicians on technical SOPs,R4,,Delivers basic training; technician skill matrix tracking should be more structured.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
303,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Coordinate equipment installations & layout changes,R4,,Smooth coordination; post-installation performance review can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
304,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Track and report downtime metrics (MTTR/MTBF),R3,X,Metrics are tracked; data analysis for downtime trends needs further development.,Present monthly MTTR/MTBF reports; lead weekly downtime reviews with team,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
305,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Conduct technician performance evaluations,R3,,Reviews completed; development-focused coaching can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
306,72637,Nguyen Phuoc Duy,UPH Support WNK2,Maintenance Supervisor,Participate in machine improvement projects,R3,X,Contributes to machine modifications; leading improvement projects can increase.,Lead 1-3  machine optimization project this year; track performance outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
307,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Supervise receiving and storage compliance,R3,,Ensures basic compliance; proactive layout optimization for fast movers can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
308,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Maintain inventory accuracy (cycle count),R3,,Maintains basic accuracy; root cause investigation on inventory variances can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
309,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Manage picking and feeding to lines,R4,,Feeding is consistent; kitting and material delivery route optimization can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
310,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Ensure warehouse safety & EHS compliance,R3,,Safety guidelines are in place; proactive racking safety inspections can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
311,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Manage warehouse headcount and shifts,R3,,Controls attendance well; labor productivity tracking across sections can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
312,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Control warehouse material handling cost,R3,,Monitors costs; forklift utilization and route planning can be further optimized.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
313,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Implement 6S in warehouse locations,R3,,6S is maintained; visual warehouse and location labeling standard can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
314,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Train warehouse staff on logistics SOPs,R4,,Delivers basic training; logistics operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
315,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Coordinate material handovers with production,R4,,Smooth handovers; standardization of handover checklist can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
316,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Track and report warehouse metrics (lead time),R3,X,Metrics are tracked; data-driven inventory aging analysis can be further developed.,Present monthly inventory aging and warehouse space utilization reports to Plant Manager,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
317,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Conduct staff performance evaluations,R3,,Reviews completed; development-focused coaching can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
318,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Participate in warehouse space layout projects,R3,X,Contributes to space layout; leading small space optimization projects can increase.,Lead 1-3  warehouse layout/space optimization project this year; track results,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
319,73252,Truong Thi Thuy Trang,UPH Support WNK2,Warehouse Supervisor,Manage warehouse inventory storage layout,R3,X,Maintains storage layout; warehouse layout optimization under inventory changes needs development.,Optimize storage placement; adjust space layout using storage capacity study data,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
320,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
321,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
322,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
323,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
324,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
325,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
326,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
327,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
328,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
329,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
330,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
331,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
332,72650,Nguyen Hai Trieu,UPH Assembly WNK2,Lead Supervisor,Manage line capacity and headcount deployment,R3,X,Manages line headcount; line balancing under layout changes needs development.,Optimize operator placement; adjust line balancing using time study data,Q2Q3,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
333,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
334,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
335,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
336,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
337,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
338,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
339,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
340,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
341,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
342,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
343,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
344,75022,Le Tuan Anh,UPH Assembly WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
345,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
346,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
347,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
348,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
349,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
350,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
351,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
352,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
353,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
354,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
355,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
356,09019,Le Thi Tuyen,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
357,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
358,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
359,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
360,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
361,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
362,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
363,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
364,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
365,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
366,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
367,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
368,13748,Le Thi Huong,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
369,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
370,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
371,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
372,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
373,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
374,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
375,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
376,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
377,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
378,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
379,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
380,00549,Trinh Thi Kim Loan,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
381,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
382,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
383,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
384,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
385,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
386,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
387,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
388,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
389,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Coordinate with maintenance on machine breakdowns,R4,,Breakdowns are resolved quickly; preventive maintenance coordination can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
390,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Lead shift handover meetings and report progress,R3,X,Meetings are held; data-driven handover reporting can be further structured.,Present daily output and quality metrics; document outstanding issues on white board,Q2,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
391,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Conduct operator performance evaluations,R3,,Evaluations are completed; development-focused feedback can go deeper.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
392,71457,Phan Thanh Son,Cut&Sew WNK2,Lead Supervisor,Participate in Lean / Kaizen improvement projects,R3,X,Contributes to projects; leading small improvement initiatives can increase.,Lead 1-3  line level Kaizen project this year; track and report outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
393,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Manage daily production outputs to meet plan,R3,,Meets daily goals; resource optimization during volume shifts can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
394,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Supervise and control safety compliance on lines,R3,,Maintains basic safety; proactive risk identification can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
395,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Conduct quality inspections (OBQ) and address issues,R3,,Inspections are consistent; root cause analysis on recurring defects can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
396,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Coordinate line setup and machine changeovers,R4,,Changeovers are smooth; setup time optimization can be further enhanced.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
397,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Manage team headcount and absenteeism,R3,,Controls attendance well; cross-training to mitigate absenteeism impact can improve.,,,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
398,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Monitor and minimize material waste on lines,R3,,Waste is monitored; material utilization awareness among team should be enhanced.,,,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Ashton Vo
399,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Implement 6S standards in the work area,R3,,Standards are maintained; team ownership of daily 6S routines can increase.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
400,73212,Daniel Pham,Cut&Sew WNK2,Lead Supervisor,Train and coach operators on standard SOPs,R4,,Conducts basic training; structured operator skill matrix tracking can improve.,,,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo`;
