export const userCSV_part1 = `1,30516,Ashton Vo,Training,TTraining Supervisor - Project,Tri?n khai cc m?c tiu KPI h?ng thng ??n Gim st khu v?c n?m r v th?c hi?n,R3,,Giao ti?p v truy?n ??t hi?u qu? v?i cc bn.,Chu?n ha cc bi?u m?u h?p tri?n khai KPI.,Ongoing,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
2,30516,Ashton Vo,Training,TTraining Supervisor - Project,"H?c h?i cch xy d?ng quy trnh automation cho 1 s? cng ?o?n trong dy chuy?n s?n xu?t sofa, t? ? xy d?ng ch??ng trnh ?o t?o ph h?p",R2,X,? tham gia 1 d? n bn t? ??ng ha chuy?n blow mold B101,"Qu?n l s?p x?p tham gia cc d? n cng team automation cc khu v?c s?n xu?t
H?c h?i cc ph?n m?m l?p trnh t? ??ng trn web, AI vi?t code",Ongoing,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
3,30516,Ashton Vo,Training,TTraining Supervisor - Project,H?c h?i cng c? AI ?? l?p k? ho?ch c?i thi?n hi?u qu? cng vi?c, gi?m th?i gian lm bo co th? cng,R2,X,C?i ti?n hi?u qu? cng vi?c,H?c ph?n m?m Copilot, power BI v ph?i h?p cc b? ph?n lin quan tri?n khai,Q2Q3,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
4,30516,Ashton Vo,Training,TTraining Supervisor - Project,Tham gia cc kha h?c quy trnh xy d?ng v pht tri?n ch??ng trnh ?o t?o, ti?u ?o t?o cc dng s?n ph?m m?i (sofa, bedding, Case goods,),R2,X,C?n thi?t cho vi?c thi?t l?p quy trnh m?i,Tham gia cng team automation, IT cc d? n m?i, ?? xu?t cc sng ki?n xy d?ng v c?i ti?n quy trnh theo t? ??ng ha, gi?m con ng??i,Q3Q4,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
5,30516,Ashton Vo,Training,TTraining Supervisor - Project,Tri?n khai th?c hi?n cc d? n ?o t?o ??m b?o hi?u qu? KPI cho b? ph?n,R4,,C thnh tch t?t trong th?c thi d? n.,Nhn r?ng cc khung ?o t?o ? thnh cng.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
6,30516,Ashton Vo,Training,TTraining Supervisor - Project,H?c thm cc ?ng d?ng m?i ?? lm cc ti?u ?o t?o d?ng video ng?n h??ng d?n, c?p nh?t ln n?n t?ng tr?c quan,R1,X,Chuy?n ??i ti?u t? vndata ln Helix,Tham kh?o ph?m m?m Helix v cc thao tc c?p nh?t m?i,Q2Q3,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
7,30516,Ashton Vo,Training,TTraining Supervisor - Project,L?n k? ho?ch v tri?n khai d? n  t??ng c?i ti?n: h? tr? Trainer pht tri?n cc  t??ng c?i ti?n, th?c hi?n lm m?u th nghi?m, nng cao t? l?  t??ng thnh cng, ti?t ki?m chi ph,R3,,T?p trung cao vo ti?t ki?m chi ph & ??i m?i.,H??ng d?n Trainer s? d?ng cng c? Lean/Six Sigma.,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management Follow-up,Department / Functional SME,Ashton Vo
8,30516,Ashton Vo,Training,TTraining Supervisor - Project,L?n k? ho?ch v th?c hi?n cc d? n ?o t?o cc m?ng s?n xu?t theo ??nh h??ng t? ban gim ??c: xy d?ng ch??ng trnh, ti?u, b? tr ngu?n l?c, ?nh gi chuy?n giao s?n xu?t,,R2,,Th?c hi?n t?t nh?ng c?n phn b? ngu?n l?c h?n.,Tinh ch?nh ch??ng trnh & tri?n khai th ?i?m.,Ongoing,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Ashton Vo
9,30516,Ashton Vo,Training,TTraining Supervisor - Project,Tri?n khai v th?c hi?n ch??ng trnh g?n k?t nhn vin: MT7/MT30/MT60/MT90,R4,,Ph?i h?p t?t; c?n ch tr?ng t? l? gi? chn.,T?ng c??ng cc ho?t ??ng tr?i nghi?m cho NV m?i.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
10,30516,Ashton Vo,Training,TTraining Supervisor - Project,L?n k? ho?ch ?o t?o v ??ng l?p gi?ng d?y cc mn h?c n?i dung k? thu?t cho nhm qu?n l m?i (FLL, MLL),R3,,K? n?ng gi?ng d?y t?t; c?n thm tnh hu?ng th?c t?.,L?ng ghp cc bi?i t?p ?ng vai & tnh hu?ng th?c.,Ongoing,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
11,30516,Ashton Vo,Training,TTraining Supervisor - Project,?o t?o re-train cc mn k? thu?t cho qu?n l s?n xu?t FLL,R3,,?o t?o l?i hi?u qu?; c?n ?nh gi sau ?o t?o.,Pht tri?n b? cng c? ?nh gi sau ?o t?o.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
12,30516,Ashton Vo,Training,TTraining Supervisor - Project,Xy d?ng m?i cc ti?u v ch?nh s?a ??nh k? cc ti?u ?o t?o theo k? ho?ch,R3,,Qu?n l ti?u ch?t l??ng cao.,S? ha ti?u ?? s? d?ng trn my tnh b?ng.,Ongoing,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
13,10394,Quach Le Du,Training,Training Lead Supervisor,Xy d?ng ch??ng trnh v ?o t?o quy trnh cho Supervisor, Team leader,R2,X,Ch??ng trnh ?o t?o ? hon thi?n v ?ang v?n hnh ?n ??nh.,??nh k? c?p nh?t cc c?i ti?n m?i vo ti?u gi?ng d?y.,Ongoing,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
14,10394,Quach Le Du,Training,Training Lead Supervisor,B? tr t?i ?u ngu?n l?c Supervisor, Team Leader h?p l theo t?ng th?i ?i?m,R4,,?i?u ph?i nhn s? linh ho?t, bm st k? ho?ch s?n xu?t.,Xy d?ng b?ng theo di ngu?n l?c ?? t?i ?u ha vi?c phn b?.,Ongoing,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
15,10394,Quach Le Du,Training,Training Lead Supervisor,Qu?n l t?ng quan v ??m b?o hi?u qu? ?o t?o c?a khu v?c mnh qu?n l,R4,,Duy tr t?t cc ch? s? hi?u qu? ?o t?o t?i khu v?c.,T?ng c??ng gim st hi?n tr??ng ?? ??m b?o ch?t l??ng ??ng nh?t.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
16,10394,Quach Le Du,Training,Training Lead Supervisor,Xy d?ng ti?u m?i v ch?nh s?a ??nh k? cc ti?u ?o t?o,R2,X,Ti?u ???c l?u tr? v c?p nh?t ?ng quy trnh.,S? ha ti?u ?? h? tr? h?c t?p trn thi?t b? di ??ng/Helix.,Ongoing,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
17,10394,Quach Le Du,Training,Training Lead Supervisor,Xy d?ng k? ho?ch headcount d?a trn ramp plan ?? chu?n b? ngu?n l?c,R4,,K? ho?ch headcount bm st ti?n ?? m? r?ng c?a nh my.,Ph?i h?p v?i TA Team ?? ??m b?o ngu?n cung nhn l?c k?p th?i.,Annual cycle,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
18,10394,Quach Le Du,Training,Training Lead Supervisor,B? tr ngu?n nhn l?c (Supervisor, Team Leader, Trainer) th?c hi?n k? ho?ch,R4,,??i ng? nng c?t ???c b? tr ?ng ng??i, ?ng vi?c.,T? ch?c cc bu?i h?p nhanh ?? x? l v??ng m?c ngu?n l?c.,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
19,10394,Quach Le Du,Training,Training Lead Supervisor,Phn b? v b? tr ngu?n nhn l?c Trainer t?i ?u nh?t theo nhu c?u,R4,,T?i ?u ha th?i gian lm vi?c c?a ??i ng? Trainer.,?o t?o cho (Cross-train) ?? Trainer c th? h? tr? nhi?u line.,Q2Q3,Align with manpower plan,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
20,10394,Quach Le Du,Training,Training Lead Supervisor,Theo st k? ho?ch, ki?m tra ?i?u ch?nh v ch? ??ng h? tr?,R4,,Ch? ??ng x? l cc tnh hu?ng pht sinh ngoi k? ho?ch.,Duy tr c? ch? bo co nhanh ?? c?p trn k?p th?i h? tr?.,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
21,10394,Quach Le Du,Training,Training Lead Supervisor,?nh gi n?ng l?c, ??nh h??ng pht tri?n k? n?ng cho nhn vin,R4,,Vi?c ?nh gi ???c th?c hi?n cng tm v ?ng h?n.,Thi?t l?p l? trnh ?o t?o chuyn su cho cc nhn s? lo?i A.,Ongoing,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Ashton Vo
22,10394,Quach Le Du,Training,Training Lead Supervisor,Xy d?ng ch??ng trnh pht tri?n n?ng l?c, k? n?ng cho nhn vin,R4,,Cc kha h?c k? n?ng m?m v qu?n tr? ???c tri?n khai t?t.,?a d?ng ha hnh th?c ?o t?o (th?c hnh, video bi gi?ng).,Q1Q4,Leadership focus,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
23,10394,Quach Le Du,Training,Training Lead Supervisor,H? tr? k?p th?i, ??ng vin, xy d?ng m?i tr??ng g?n k?t,R4,,Xy d?ng ???c m?i tr??ng lm vi?c tch c?c, g?n b.,Duy tr cc knh l?ng nghe  ki?n ?ng gp c?a nhn vin.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
24,10394,Quach Le Du,Training,Training Lead Supervisor,T? ch?c cc ho?t ??ng g?n k?t v xy s? Team Word ??i nhm (Team Building),R4,,Cc ngY l? v s? ki?n ???c t? ch?c bi b?n,  ngha.,L?ng ghp cc thng ?i?p v?n ha cng ty vo ho?t ??ng ??i nhm.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
25,10394,Quach Le Du,Training,Training Lead Supervisor,Xy d?ng v?n ha h?c t?p t? thn (Vinh danh Trainer, chia s? kinh nghi?m),R3,X,V?n ha chia s? ki?n th?c ?ang d?n hnh thnh m?nh m?.,Duy tr ch??ng trnh "Sng ki?n ?o t?o" ?? khuy?n khch sng t?o.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
26,10394,Quach Le Du,Training,Training Lead Supervisor,Xy d?ng ch??ng trnh v tri?n khai cc d? n c?a b? ph?n,R1,X,D? n ?ang trong giai ?o?n chu?n b?, c?n ??y nhanh ti?n ??.,L?p k? ho?ch chi ti?t v phn cng trch nhi?m (RACI) cho d? n.,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
27,10394,Quach Le Du,Training,Training Lead Supervisor,Ch? ??ng ?? xu?t, xy d?ng v tri?n khai d? n cng cc phng ban,R1,X,Kh? n?ng ph?i h?p lin phng ban c?n ???c pht huy h?n.,Thi?t l?p cc cu?c h?p ??nh k? v?i S?n xu?t ?? tm gi?i php chung.,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
28,4272,Phan Thi Ha,Training,Training Supervisor C&S,?o t?o v pht tri?n v? n?ng l?c, k? n?ng.,R3,X,V?a lm v?a h?c, trao ??i l?n nhau,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
29,4272,Phan Thi Ha,Training,Training Supervisor C&S,Xy d?ng ch??ng trnh, cc ti?u m?i v ch?nh s?a ??nh k? ti?u ?o t?o,R3,X,Ti?u c b?n ??y ?? nh?ng c?n c?p nh?t cc m?u m m?i.,?u tin hon thi?n th? vi?n video h??ng d?n thao tc chu?n.,Qu 3,Ch? th?c hi?n c? b?n cc ti?u c?p trn giao ch?a tm hi?u su v? k? n?ng  th?c hi?n cc file bo co,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
30,4272,Phan Thi Ha,Training,Training Supervisor C&S,C?i ti?n v cc d? n,R3,X,"- Qu?n l d? n b? ph?n: Thi?t l?p v tri?n khai d? n n?i b?
- Ch? ??ng ?? xu?t ph?i h?p v tri?n khai d? n cng cc phng ban",S? d?ng m hisnh RAIL ?? ki?m soat ti?n ?? t?ng h?ng m?c d? n.,Ongoing,Ch? th?c hi?n c? b?n cc ti?u c?p trn giao ch?a tm hi?u su v? k? n?ng  th?c hi?n cc file bo co,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
31,4272,Phan Thi Ha,Training,Training Supervisor C&S,B? tr nhn l?c,R3,,"- S?p x?p cng vi?c v ??m b?o ngu?n nhn l?c ?o t?o.
- C?p nh?t bo co v?ng v HC khu v?c qu?n l v b? tr v phn b? t?i ?u ngu?n l?c Team Leader, Trainer",T? ??ng ha bo co ?? c?p nh?t d? li?u th?i gian th?c. Xy d?ng ma tr?n k? n?ng ?a nhi?m cho ??i ng? nng c?t.,Ongoing,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
32,4272,Phan Thi Ha,Training,Training Supervisor C&S,L?p k? ho?ch ?o t?o cng nhn m?i,R4,,"- L?p k? ho?ch chu?n b? nh?n cng nhn m?i: my mc, cng c???m b?o s? ??y ?? d?ng c? v nguYn v?t li?u ?o t?o.",Chu?n ha danh m?c ki?m tra (checklist) chu?n b? cho t?ng line.,Ongoing,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
33,4272,Phan Thi Ha,Training,Training Supervisor C&S,L?p v th?c hi?n k? ho?ch s?n xu?t (P&IC, m?c tiu ?o t?o...),R4,,- ??t k? ho?ch hng ha ph h?p; ch? ??ng h? tr? k?p th?i.,T?ng c??ng ph?i h?p v?i P&IC ?? t?i ?u nng su?t line ?o t?o.,Ongoing,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
34,4272,Phan Thi Ha,Training,Training Supervisor C&S,Qu?n l t?ng quan hi?u qu? ?o t?o (Nng su?t, ch?t l??ng, OBQ...),R4,,"- Bm st m?c tiu cc cng ?o?n, ??m b?o t? l? rc th?p.",Phn tch d? li?u OBQ ??nh k? ?? tm nguyn nhn g?c r?.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
35,4272,Phan Thi Ha,Training,Training Supervisor C&S,Tri?n khai v th?c hi?n cc Form b?ng bi?u (MT, Canban, h? s?...),R4,,- Th?c hi?n ??y ?? cc h? s? Trainer v b?ng bi?u t?i x??ng.,S? ha cc form bi?u m?u trn tablet thng qua h? th?ng Helix.,Ongoing,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
36,4272,Phan Thi Ha,Training,Training Supervisor C&S,G?p g? One on One nhn vin,R4,,"- L?ng nghe, ??ng vin v gi?i quy?t kh kh?n k?p th?i.",Duy tr l?ch h?p 1-1 ??nh k? hng thng ?? t?ng tnh g?n k?t.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
37,4272,Phan Thi Ha,Training,Training Supervisor C&S,Bo co cng vi?c & ?nh gi ??nh k? cng vi?c hng tu?n v hng thng,R2,X,"- T?ng h?p d? li?u chnh xc, ph?n nh ?ng th?c t?.
- Chu?n ha quy trnh thu th?p v ??i soat d? li?u th.
- C?p nh?t bo co cng vi?c hng tu?n (OBQ, v?ng, NS-CL)
- D?a trn m?c tiu ??t ra, c?p nh?t k?t qu? v k? ho?ch ti?p theo.
- ??m b?o tnh cng b?ng v minh b?ch trong tiu ch ?nh gi.",Thi?t l?p b?ng ?i?u khi?n (Dashboard) ?? theo di nhanh.,Ongoing,H?c h?i thm cch ?? c?p nh?t bo co nhanh v p d?ng cng ngh? khi nh?p bo co,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
38,4272,Phan Thi Ha,Training,Training Supervisor C&S,Nh?n thng tin Mail v Team ?? x? l v?n ?? k?p th?i,R4,,"- Ti?p nh?n v ph?n h?i thng tin nhanh chng, hiu qu?.",Chu?n ha quy trnh x? l thng tin kh?n c?p lin phng ban.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
39,4272,Phan Thi Ha,Training,Training Supervisor C&S,?nh gi n?ng l?c, ??nh h??ng pht tri?n cho nhn vin v xy d?ng ch??ng trnh ?o t?o quy trnh, pht tri?n n?ng l?c,R4,,- Nh?n di?n ?ng cc nhn t? ti?m n?ng ?? ?o t?o k? th?a.,L?p l? trnh pht tri?n n?ng l?c (IDP) cho Team Leader/Trainer.,Ongoing,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Ashton Vo
40,4272,Phan Thi Ha,Training,Training Supervisor C&S,H?c h?i thm cng c? AI, p d?ng AI nng cao hi?u qu?,R2,X,"- C?i ti?n hiu qu? cng vi?c
- p d?ng AI vo s?n xu?t","Tham gia cc l?p ?o t?o v? AI, tm hi?u cc cng c? AI cch s? d?ng v p d?ng vo co co, lm k? ho?ch",Qu 3,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
41,72166,Tran Cong Minh,Training,Training Supervisor UPH,B? tr nhn l?c,R4,,"Cng nhn n?m b?t cc thao tc chu?n, hi?u r v lm ?ng tiu chu?n SOP",Duy tr ki?m tra tay ngh? (Audit) ??nh k? sau ?o t?o.,Ongoing,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
42,72166,Tran Cong Minh,Training,Training Supervisor UPH,Gim st hi?u qu? cng vi?c,R3,,"T?ng nhm lun ??t m?c tiu cc KPI b? ph?n: (AB, TO, SOP, OBQ, Eff, Idea, EHS, 6S)",Phn tch su cc ch? s? bi?n ??ng ?? c gi?i php k?p th?i.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
43,72166,Tran Cong Minh,Training,Training Supervisor UPH,Xy d?ng, h? tr? ??i nhm g?n k?t, pht tri?n,R3,,"M?i tr??ng lm vi?c g?n k?t
Th?u hi?u, tch c?c v hi?u qu?.
H? tr? kh kh?n k?p th?i.",T? ch?c cc bu?i h?p nhanh (Briefing) ?? l?ng nghe ph?n h?i.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
44,72166,Tran Cong Minh,Training,Training Supervisor UPH,Xy d?ng, ch?nh s?a ti?u c b?n,R2,X,??m b?o ??y ?? s? chu?n b? cho cho cng tc ?o t?o,S? ha ti?u v c?p nh?t ln h? th?ng th? vi?n video.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
45,72166,Tran Cong Minh,Training,Training Supervisor UPH,L?p k? ho?ch gim st ch?t l??ng,R3,,,Chu?n ha danh m?c checklist thi?t b? theo t?ng line s?n xu?t.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
46,72166,Tran Cong Minh,Training,Training Supervisor UPH,?nh gi n?ng l?c c?p d??i,R3,,,Thi?t l?p l? trnh th?ng ti?n c nhn cho cc nhn t? ti?m n?ng.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
47,72166,Tran Cong Minh,Training,Training Supervisor UPH,L?p k? ho?ch hng ha hng tu?n,R4,,??m b?o ?? hng ha v  ?ng tay ngh? cng nhn theo tu?n tu?i,Theo di st nng su?t th?c t? so v?i k? ho?ch trn h? th?ng.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
48,72166,Tran Cong Minh,Training,Training Supervisor UPH,L?p k? ho?ch ki?m soat ch?t l??ng SOP v OBQ khu v?c ?ng gh? v Blow fill,R3,,Nng cao ch?t l??ng v xy d?ng  th?c ch?t l??ng cho h?c vin v Trainer,T?ng c??ng ?o t?o th?c hnh v? l?i ngo?i quan (Visual defect).,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
49,72166,Tran Cong Minh,Training,Training Supervisor UPH,G?p g? c nhn Trainer, Team v h?c vin,R3,,"K?t n?i, chia s? v l?ng nghe",Xy d?ng v?n ha ph?n h?i hai chi?u (Top-down & Bottom-up).,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
50,72166,Tran Cong Minh,Training,Training Supervisor UPH,"Bo co tu?n theo MSS v? con ng??i, ch?t l??ng, hi?u qu?, Idear, d? n,.",R3,,C?p nh?t ti?n ?? ?o t?o,T? ??ng ha b?ng bi?u bo co ?? gi?m thi?u thao tc th? cng.,Q3,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
51,72166,Tran Cong Minh,Training,Training Supervisor UPH,Bo co ?nh gi Bonus thng,R4,,,??m b?o tnh cng b?ng v minh b?ch trong tiu ch ?nh gi.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
52,72166,Tran Cong Minh,Training,Training Supervisor UPH,"T?ng h?p bo co OBQ, V?ng, TLNV, NS -CL theo tu?n, thng",R3,X,,Chu?n ha quy trnh thu th?p v ??i soat d? li?u th.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
53,72166,Tran Cong Minh,Training,Training Supervisor UPH,Th? t?c hnh chnh,R3,,,??n gi?n ha cc bi?u m?u hnh chnh trn n?n t?ng s?.,Q2,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
54,72166,Tran Cong Minh,Training,Training Supervisor UPH,B? tr OT theo nh? c?u s?n xu?t v ??ng k OT,R4,,Cng s?n xu?t th?c hi?n k? ho?ch nh my,Theo di st gi? lm thm ?? ??m b?o s?c kh?e cho ??i ng?.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
55,72166,Tran Cong Minh,Training,Training Supervisor UPH,Nh?n thng tin Mail v chat Team ?? x? l cc v?n ?? lin quan k?p th?i,R4,,Nh?n thng tin v ph?n h?i,Thi?t l?p khung th?i gian vng ?? ph?n h?i cc yu c?u kh?n.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
56,72166,Tran Cong Minh,Training,Training Supervisor UPH,?nh gi YTCT c?a ??i nhm,R3,X,,"Xy d?ng b? tiu ch ch?m ?i?m YTCT r rng, d? ?o l??ng.",Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
57,72166,Tran Cong Minh,Training,Training Supervisor UPH,X? l v?n ?? v?i cc b? ph?n lin quan trong nh my,R3,,??m b?o cng vi?c ?o t?o ?ng v c?p nh?t cc thng tin thay ??i k?p th?i,Thi?t l?p nhm ph?n ?ng nhanh (Task force) v?i b? ph?n IE/S?n xu?t.,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
58,72166,Tran Cong Minh,Training,Training Supervisor UPH,"?o t?o c b?n cho c?p d??i v? k? n?ng, giao ti?p,.",R3,,"V?a lm v?a h?c, trao ??i l?n nhau",Th?c hi?n cc bu?i hu?n luy?n t?i ch? (On-the-job coaching).,Ongoing,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
59,72166,Tran Cong Minh,Training,Training Supervisor UPH,S? d?ng cng c? AI hiu qu?,R2,X,"Thu?t ng? d tm, khai thc n?i dung hiu qu?",,Q3,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Ashton Vo
60,72166,Tran Cong Minh,Training,Training Supervisor UPH,"Cch s? d?ng cc ph?n m?m ?? ch?nh s?a video, c?t ghp,.",R1,X,"Ph?c v? cho vi?c ch?nh s?a ti?u, SOP",,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
61,72166,Tran Cong Minh,Training,Training Supervisor UPH,"Cc tnh n?ng c?a Email, Excel (d tm, format,)",R2,X,,,Q4,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
62,72166,Vo Vu Luan,Training,Training Supervisor UPH,"K? ho?ch xy d?ng v c?p nh?t cc ti?u m?i
Ch?nh s?a ??nh k? cc ti?u ?o t?o",R3,,"- Ch? ??ng ki?m tra v ?nh gi tnh th?c t? c?a ch??ng trnh ?o t?o
 - H??ng t?i Trainer l ng??i ??a ra cc l?u trnh th?c t? t?i x??ng v t?ng h?p l?i tr??c khi p d?ng","- Tri?n khai qu 3, KPI Bonus trainer ??a ra 1  t??ng c?i ti?n/ tinh g?n quy trnh n?i mnh ?ang lm vi?c",On going,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
63,72166,Vo Vu Luan,Training,Training Supervisor UPH,Tri?n khai ch??ng trnh v ?o t?o nng cao k? n?ng cho nhn vin,R3,,"- ??m b?o nhn vin hi?u r v? l?u trnh v ch??ng trnh ?o t?o c?a mnh
 - Tun th? cc tiu chu?n v l?u trnh ?o t?o
 - C nh nh?p ?a ra cc ?? xu?t v? l?u trnh ?o t?o ?ng v?i th?c t?",Tri?n khai r - Ki?m tra v ?nh gi - C?p nh?t v ?i?u ch?nh - Theo di hi?u qu?,On going,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
64,72166,Vo Vu Luan,Training,Training Supervisor UPH,B? tr t?i ?u ngun l?c h?p l theo t?ng th?i ?i?m, nhu c?u t?ng nh my,R4,,"- Ch? ??ng ph?i h?p v ?i?u ph?i trainer cc nh my nh?m t?i ?u ngun l?c
 - ??m b?o nhn vin hi?u r vai tr trò v trch nhi?m cng vi?c",- ?nh gi n?ng l?c ngun l?c th?c t? UPH v Components,On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
65,72166,Vo Vu Luan,Training,Training Supervisor UPH,Ph?i h?p P&IC v TA team ??t k? ho?ch ph h?p theo m?c tiu ?o t?o v t?ng tr??ng nh my,R4,,"- ?nh gi ???c n?ng l?c nhm v ??t k? hoach ph h?p, ??m b?o hi?u qu?.
 - C k? ho?ch c? th? v? ramp plan v tri?n khai nhn vin hi?u r",- ?nh gi ngun l?c ??t k? ho?ch ph h?p hng tu?n,On going,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Ashton Vo
66,72166,Vo Vu Luan,Training,Training Supervisor UPH,??m b?o hi?u qu? ?o t?o c?a khu v?c mnh qu?n l.,R4,,"- ??m b?o nhn vin hi?u r m?c tiu v cng vi?c mnh c?n ph?i lm
 - Nng cao tinh th?n trch nhi?m c?a m?i c nhn trong m?i ho?t ??ng ?o t?o",Tri?n khai r - Ki?m tra v ?nh gi - C?p nh?t v ?i?u ch?nh - Theo di hi?u qu?,On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
67,72166,Vo Vu Luan,Training,Training Supervisor UPH,?nh gi n?ng l?c, ??nh h??ng pht tri?n k? n?ng cho nhn vin,R3,X,"- ?nh gi skill matrix hng qu, ??m b?o hi?u r n?ng l?c th?c t? nhm mnh qu?n l
 - Ch? ??ng b? tr nhn l?c h?c h?i, ?a k? n?ng chu?n b? cho cc d? n c?ng nh? trainer ti?m n?ng cho s? pht tri?n","- ?nh gi Skill matrix hng qu
 - L?n ch??ng trnh ?o t?o ??nh k? v? k? n?ng qu?n l",On going,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Ashton Vo
68,72166,Vo Vu Luan,Training,Training Supervisor UPH,Xy d?ng ch??ng trnh v ?o t?o, pht tri?n n?ng l?c, k? n?ng cho nhn vin,R3,X,"- Nng cao s? ph?i h?p v ghi nh?n ??i v?i nhn vin.
 - L?ng nghe v h? tr? k?p th?i
 - Hi?u nhn vin",- G?p g? c nhn hng tu?n theo l?ch c? ??nh,On going,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Ashton Vo
69,72166,Vo Vu Luan,Training,Training Supervisor UPH,Ch? ??ng ?? xu?t cc d? n hng thng, qu: Tinh g?n quy trnh, gi?m chi ph.,R3,X,- Xy d?ng k? ho?ch v ?? xu?t cc ho?t ??ng h??ng ??n tinh g?n quy trnh ?o t?o cho nhm th?c hi?n tr?c ti?p tham gia v th?c hi?n.,- M?c tiu ??a ra cc d? n hng qu/ n?m,On going,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management Follow-up,Department / Functional SME,Ashton Vo
70,72166,Vo Vu Luan,Training,Training Supervisor UPH,"Ph?i h?p cc team lin quan d? n Blow Mold
 + Blow mold
 + Assembly Blow Mold",R3,X,"-  Xy d?ng cc ch??ng trnh ?o t?o, tiu chu?n ?o t?o ph h?p v chnh xc v?i th?c t? ??m b?o hi?u qu? Blow Mold
 - Ph?i h?p cc phng ban xy d?ng tiu chu?n v t?i ?u cc quy trnh, layout chuy?n Assembly Blow mold","- Theo cc d? n v ?o t?o Blow mold Machine
 - ?o t?o line t?i WN2 v chuy?n sang WN5 thng 4",Qu 2,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Ashton Vo
71,72166,Vo Vu Luan,Training,Training Supervisor UPH,"M? r?ng qu?n l Cut & Sew
 + L?u trnh
 + K? Thu?t",R2,X,"- Qu?n l t?ng quan hi?u qu? ?o t?o
 - Th?c hnh k? thu?t cc kha u ??t trainer level 2
 - Hi?u r v gp  xy d?ng cc l?u trnh ?o t?o ph h?p, hi?u qu?",- M?i ngY h?c 1h theo k? ho?ch c? ??nh.,Qu 2,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Ashton Vo
72,72166,Vo Vu Luan,Training,Training Supervisor UPH,"Nng l?c qu?n l 
 + Xy d?ng v lan t?a v?n ha tn tr?ng t?i cc nhm
 + Nng cao k? n?ng qu?n l ??m nhnh r?ng h?n",R3,X,"- Thay ??i gc nhsn, t? duy
 - ?nh gi v?n ?? trn nhi?u kha c?nh, 
 - Hi?u r vai tr trò v trch nhi?m
 - Ch? ??ng t?t trong cc giao ti?p v nhi?m v?","- Tri?n khai hng ngY v? v?n ha ""Tn Tr?ng""",Qu 3,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Ashton Vo
73,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,"Develop organizational structure, and execute recruitment and training plans
Xy d?ng s? ?? t? ch?c, tuy?n d?ng v ?o t?o theo k? ho?ch",R3,X,"Demonstrates strong experience in organizing, training, and effectively managing teams; further development is needed in long-term workforce planning
C kinh nghi?m t? ch?c v ?o t?o, qu?n l team hi?u qu?; c?n nng cao trong vi?c xy d?ng k? ho?ch nhn s? di h?n.","Build a strong succession pipeline
Xy d?ng ??i ng? k? th?a",Q3-2026,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Sang Tong
74,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,"Organize and allocate workforce effectively to meet operational needs
T? ch?c v s?p x?p nhn l?c lm vi?c ph h?p ?p ?ng nhu c?u cng vi?c",R3,,"Possesses good coordination skills; however, needs to consistently optimize team productivity, with a stronger focus on efficiency improvement and optimal resource utilization
C kh? n?ng ?i?u ph?i t?t, tuy nhin c?n duy tr vi?c t?i ?u nng su?t nhm m?t cch lin t?c, t?p trung nng cao hi?u qu? v s? d?ng ngu?n l?c t?i ?u.","Drive continuous improvement initiatives
C?i ti?n lin t?c",On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
75,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,"Manage inventory (inbound, outbound, and stock control); ensure accurate and timely receiving, storage, and preservation of goods
T? ch?c qu?n l hng ha xu?t nh?p t?n, th?c hi?n cc th? t?c nh?p-xu?t, s?p x?p, l?u kho v b?o qu?n hng ha ???c chnh xc v k?p th?i",R4,,"Performing well with accurate and timely control
?ang th?c hi?n t?t, kim soat chnh xc v k?p th?i.","Standardize processes, provide team training, and implement continuous improvements
Chu?n ha quy trnh, ?o t?o team v tri?n khai c?i ti?n lin t?c.",On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
76,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,"Oversee logistics operations, including transportation and delivery between warehouses and according to customer orders
T? ch?c giao nh?n, v?n chuy?n, giao hng gi?a cc kho v theo ??n ??t hng c?a Khch Hng",R4,,"Operations are stable and effectively meet delivery demands
V?n hnh ?n ??nh, ?p ?ng t?t nhu c?u giao hng.","Optimize container loading and transportation efficiency
T?i ?u cont v?n chuy?n",On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
77,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,"Monitor, coordinate, and supervise work progress; promptly handle arising issues
Theo di, ?i?u ph?i v gim st ti?n ?? cng vi?c, k?p th?i x? l cc v?n ?? pht sinh",R4,,"Proactively monitors and promptly resolves operational issues as they arise
Ch? ??ng theo di v x? l k?p th?i cc v?n ?? pht sinh trong v?n hnh","Standardize incident handling procedures and enhance risk mitigation capability
Chu?n ha quy trnh x? l s? c? v nng cao kh? n?ng d? phng r?i ro.",On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
78,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,"Guide and remind employees on Occupational Safety and Fire Prevention (EHS/PCCC) daily; ensure compliance with regulations
H??ng d?n, nh?c nh? CNV v ATL?, ATPCCN hng ngY v gim st vi?c tun th? th?c hi?n",R3,,"Provides good guidance to employees; however, needs to increase the frequency of compliance monitoring
? th?c hi?n h??ng d?n t?t nh?ng c?n t?ng t?n su?t theo di tun th?","Strengthen execution monitoring and compliance control
T?ng c??ng gim st th?c hi?n",On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
79,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,T? ch?c v tham gia cc ho?t ??ng g?n k?t NL?,R4,X,Actively participates in organizing employee engagement activities,N?ng n? tham gia vo t? ch?c cc ho?t ??ng g?n k?t,Continue enhancing current strengths,Ti?p t?c pht huy,On going,,Functional,Employee Relations,Department Follow-up,Employee Relations Follow-up,HRBP / Department,Sang Tong
80,17676,Nguyen Thi Mong Van,DC - C&S Raw Material,Material Delivery Lead Supervisor,"Research and implement initiatives to improve and optimize work processes
Nghin c?u, th? nghi?m ?? c?i ti?n quy trnh lm vi?c ???c hi?u qu? v t?i ?u",R3,X,"Has a solid foundation and meets job requirements; however, should continue developing to enhance effectiveness, with greater focus on proposing and implementing improvements
C n?n t?ng t?t v ?ang ?p ?ng yu c?u cng vi?c, tuy nhin c?n ti?p t?c pht tri?n ?? nng cao hi?u qu? v t?p trung vo ?? xu?t v tri?n khai c?i ti?n.","Proactively research, pilot, and implement improvement initiatives to enhance efficiency and optimize workflows
Ch? ??ng nghin c?u, th? nghi?m v tri?n khai cc gi?i php c?i ti?n nh?m nng cao hi?u qu? v t?i ?u ha quy trnh lm vi?c.",On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
81,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,"Develop organizational structure, and execute recruitment and training plans
Xy d?ng s? ?? t? ch?c, tuy?n d?ng v ?o t?o theo k? ho?ch",R3,X,Demonstrates good capability in organizing, training, and managing the team,T? ch?c v ?o t?o qu?n l team kh t?t,Build a strong succession pipeline,C?n xy d?ng ??i ng? k? th?a,Q3-2026,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Sang Tong
82,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,"Organize and allocate workforce effectively to meet operational needs
T? ch?c v s?p x?p nhn l?c lm vi?c ph h?p ?p ?ng nhu c?u cng vi?c",R3,,Shows strong coordination skills; effectively organizes and allocates manpower to meet operational demands,C kh? n?ng ?i?u ph?i t?t, t? ch?c v s?p x?p nhn l?c ?p ?ng nhu c?u cng vi?c,Improve team productivity and overall efficiency,C?n t?i ?u nng su?t v hi?u qu? nhm,On going,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Sang Tong
83,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,"Manage inventory (inbound, outbound, and stock control); ensure accurate and timely receiving, storage, and preservation of goods
T? ch?c qu?n l hng ha xu?t nh?p t?n, th?c hi?n cc th? t?c nh?p-xu?t, s?p x?p, l?u kho v b?o qu?n hng ha ???c chnh xc v k?p th?i",R3,,Performing well with accurate and timely control,?ang th?c hi?n t?t, kim soat chnh xc v k?p th?i,Standardize processes and conduct regular team training,Chu?n ha quy trnh, ?o t?o nhm ??nh k?,On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
84,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,"Oversee logistics operations, including transportation and delivery between warehouses and according to customer orders
T? ch?c giao nh?n, v?n chuy?n, giao hng gi?a cc kho v theo ??n ??t hng c?a Khch Hng",R4,,Operations are stable and effectively meet delivery requirements,V?n hnh ?n ??nh, ?p ?ng t?t nhu c?u giao hng.,Research and drive initiatives to improve container utilization rates,C?n nghin c?u v thc ??y t?ng t? l? t?n d?ng cont,On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
85,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,"Monitor, coordinate, and supervise work progress; promptly handle arising issues
Theo di, ?i?u ph?i v gim st ti?n ?? cng vi?c, k?p th?i x? l cc v?n ?? pht sinh",R4,,Proactively monitors and promptly addresses operational issues,Ch? ??ng theo di v x? l k?p th?i cc v?n ?? pht sinh trong v?n hnh,Standardize incident handling processes and enhance risk prevention capability,Chu?n ha quy trnh x? l s? c? v nng cao kh? n?ng d? phng r?i ro,On going,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
86,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,"Guide and remind employees on Occupational Safety and Fire Prevention (EHS/PCCC) daily; ensure compliance with regulations
H??ng d?n, nh?c nh? CNV v ATL?, ATPCCN hng ngY v gim st vi?c tun th? th?c hi?n",R3,X,Has provided guidance; however, needs to increase the frequency of compliance monitoring,? th?c hi?n h??ng d?n nh?ng c?n t?ng t?n su?t theo di tun th?,Standardize training materials and checklists; strengthen execution monitoring,Chu?n ha ti?u ?o t?o, checklist v t?ng c??ng gim st th?c hi?n.,On going,,Functional,Training Capability,Department Follow-up,Training Capability Follow-up,Department / Functional SME,Sang Tong
87,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,T? ch?c v tham gia cc ho?t ??ng g?n k?t NL?,R3,X,Has participated in basic engagement activities,? th?c hi?n cc ho?t ??ng c b?n,Actively participate in company activities and foster employee engagement,C?n tch c?c tham gia cc ho?t ??ng chung v t?o s? g?n k?t,On going,,Functional,Employee Relations,Department Follow-up,Employee Relations Follow-up,HRBP / Department,Sang Tong
88,24805,Truong Minh Hung,Components,Material Delivery Lead Supervisor,"Research and implement initiatives to improve and optimize work processes
Nghin c?u, th? nghi?m ?? c?i ti?n quy trnh lm vi?c ???c hi?u qu? v t?i ?u",R4,,Actively contributes to improvement initiatives and encourages team members to participate,Tch c?c trong cc ho?t ??ng c?i ti?n v khuy?n khch nhn vin tham gia,Continue leveraging and building on current strengths,Ti?p t?c pht huy,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Sang Tong
89,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Strategic Quality Planning & Vision Translation,R3,X,Understands quality strategy at operational level; needs development in translating Director-level vision into dept action plans,Attend strategic planning sessions with TAT Director; co-develop annual quality roadmap,Q2Q3,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Venus Le
90,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Audit Governance Framework Development,R3,,Familiar with existing frameworks; limited experience designing governance structures from scratch,Lead one governance review project with mentoring from TAT Director,Q3,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
91,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,KPI & Performance Dashboard Design,R3,,Able to use dashboards;  cascading KPIs,Build dept KPI dashboard aligned to Director's scorecard; review monthly,Q2Q4,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Venus Le
92,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Culture of Quality & Accountability Leadership,R4,,Strong quality mindset; actively promotes standards and accountability within team,Continue best practices; coach direct reports on culture-building,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
93,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,SOP Audit & OBQ Inspection Oversight,R4,,Expert-level knowledge of SOP/OBQ systems; oversees with high independence,Maintain discipline; share expertise with new AM cohort,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
94,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,CAR / PAR Approval for Critical Defects,R3,,Approves routine CARs; developing confidence in systemic/customer-critical escalations,Shadow TAT Director on 35 critical CAR reviews; build decision framework,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
95,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Versatility Matrix & Headcount Deployment,R4,,Effectively manages shift coverage and versatility planning across sections,Expand scope to include cross-division deployment planning,Ongoing,,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Venus Le
96,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Audit Documentation & Traceability Standards,R4,X,Maintains high discipline in version control and audit traceability,Mentor Lead Supervisors on documentation standards,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
97,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Product Quality Project Governance,R3,,Solid execution; needs to demonstrate clear understanding of full end-to-end project governance model.,Lead 1-3  full Product Quality Project cycle as project owner,Q3Q4,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
98,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Senior Customer Quality Meeting Leadership,R2,,Participates in customer meetings; needs development in leading executive-level discussions independently,Co-lead weekly US customer meetings with TAT Director; take solo lead,Q2Q4,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
99,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Customer Escalation Response & Communication,R3,X,Responds to standard escalations well,,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
100,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Formal Quality Report & Dashboard Presentation,R3,,Builds reports competently; presentation narrative at executive level in development,Present monthly quality report to Dir once per quarter; receive structured feedback,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
101,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Cross-Functional Collaboration (IE / CI / WH / Logistics),R4,,Strong relationship with cross-functional teams; drives joint quality controls effectively,Expand influence to Logistics and FI/QC; lead monthly cross-functional quality sync,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
102,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Predictive Risk Control & Defect Analytics,R3,X,Uses historical data well; FMEA and process capability analytics need further development,Complete advanced FMEA training; apply on 2 pilot run reviews this year,Q2Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
103,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Talent Pipeline Building & Succession Planning,R3,,Strong individual coaching skills; competency framework and succession planning need structure,Co-develop TAT succession map with HR Head; identify 2 AM-ready candidates by Q3,Q2Q3,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
104,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Training Roadmap & Competency Framework Design,R3,,Delivers effective on-the-job training; formal competency framework design is new territory,Develop TAT Competency Framework for Auditor-to-AM pipeline; pilot Q3,Q3Q4,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
105,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Headcount Planning & Workforce Strategy,R4,,Demonstrates strong workforce planning aligned to production volume and complexity,Lead annual HC planning for next cycle; present to TAT Director for approval,Annual cycle,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Venus Le
106,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Performance Evaluation & PDMS Oversight,R4,,Conducts thorough performance reviews; strong in PDMS administration,Standardize PDMS process across all AM reports; train new AMs,Q2 & Q4,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
107,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Recruitment & Retention Strategy,R3,,Good at identifying talent; structured retention strategy needs development,Build TAT retention plan with HR; implement 1 key retention initiative by Q3,Q2Q3,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Venus Le
108,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Lean / Kaizen / 6S Program Leadership,R4,,Leads 6S programs effectively; Kaizen facilitation skills are strong,Lead enterprise Kaizen event this year; document and share outcomes,Q3,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
109,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Audit System Digitalization & Modernization,R2,X,Aware of digital audit tools; needs to focus more on leading full-scale system digitalization,Lead pilot digitalization of 1 audit system (SOP or OBQ); present roadmap,Q3Q4,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
110,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Quality Cost Reduction Initiatives,R3,,Contributes to cost reduction; needs more ownership over program,Own 1-3  quality cost reduction initiative end-to-end; report  results quarterly,Q2Q4,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
111,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Improvement KPI Measurement & Reporting,R3,,Tracks KPIs at team level; needs to develop enterprise-level improvement reporting,Build monthly improvement KPI report; present to Director and cross-functional heads,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Venus Le
112,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Annual Budget Development & Management,R3,,Understands budget structure;,Co-own next annual budget submission with TAT Director; attend all finance reviews,Annual cycle,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Venus Le
113,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Executive Quality Status Reporting,R3,,Produces solid team-level reports; executive-level reporting narrative can be further developed,Draft monthly Director report; receive structured feedback on executive communication style,Ongoing,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Venus Le
114,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Trend Analysis & Performance Dashboard for Stakeholders,R3,,Strong data skills; stakeholder-facing dashboard design needs practice,Design and own TAT performance dashboard presented to senior leadership monthly,Q2Q3,,Digital,AI & Automation,Add to Training Plan,AI for Everyone; Power Automate; Power BI,L&D + IT/Automation SME,Venus Le
115,,Harvey Nguyen / Edgar Bui,TAT Quality,TAT Manager,Critical Quality Event Escalation & Impact Assessment,R4,,Responds swiftly to critical events; escalation communication with business impact framing is solid,Continue current standard; coach AM team on escalation protocols,Ongoing,,Business Acumen,Business Acumen,Department Follow-up,Business Acumen Framework,Department / Functional SME,Venus Le
116,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Identify inputs for production activities,R4,,Demonstrate strong capability in identifying key inputs for production operations,Regularly review and optimize input assumptions to minimize the risk of shortages or excess inventory,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
117,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Develop efficient production processes; allocate manpower machinery and materials appropriately to ensure completion of plans,R4,,Effectively evaluate and align processes machinery and manpower across different production stages,Optimize resource allocation to ensure efficiency and productivity,Ongoing,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Nhat Huynh
118,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Ensure production storage transportation and delivery processes are carried out effectively to meet business demands,R4,,Proactively identify risks and implement timely solutions to ensure on-time delivery and operational efficiency,Develop contingency plans to mitigate impacts on production and delivery operations,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
119,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Monitor coordinate and supervise production progress; promptly handle arising issues.,R4,,Ensure seamless cross-functional coordination to maintain continuous and efficient production while addressing issues promptly,Drive effective cross-functional communication to promptly resolve issues and minimize production disruptions,Ongoing,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Nhat Huynh
120,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Supervise and control all aspects of production activities to maximize the use of resources machinery and labor while minimizing waste.,R3,X,Drive operational efficiency through process optimization effective resource allocation and cost control,Continuously improve processes and optimize resource utilization to enhance productivity and reduce operational costs,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
121,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Ensure necessary raw materials for production are always available in the company.,R4,,Proactively collaborate with Procurement and Supply Chain teams to prevent shortages and mitigate supply risks,Anticipate supply risks and implement contingency plans such as alternative sourcing and safety stock strategies,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
122,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Establish product quality standards and regulations.,R4,,Regularly review and update quality standards to drive continuous improvement and maintain product consistency,Foster a culture of continuous improvement by integrating feedback evaluation results and operational data into quality enhancement initiatives,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
123,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Conduct quality inspections at each stage of production to ensure output meets required standards,R4,,Proactively identify defects early in the production process and implement corrective actions to prevent recurrence ensuring stable quality,Strengthen in-process quality control to minimize defects and ensure timely corrective actions to prevent recurrence,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
124,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Regularly update and improve processes to enhance product quality.,R4,,Continuously seek improvement opportunities and implement effective solutions to enhance product quality,Encourage and lead continuous improvement initiatives to enhance overall quality performance,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
125,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Manage and evaluate product quality within the company.,R4,,Effectively manage and evaluate product quality to ensure alignment with company standards and customer expectations,Leverage data analysis and customer feedback to drive continuous improvement,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
126,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Manage and optimize costs related to materials raw materials labor and machinery in the production process.,R3,X,Ensure effective control of key operational areas,Implement appropriate control and maintenance measures to ensure operational stability efficiency and cost optimization,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
127,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Minimize waste and defects to reduce product costs.,R4,,Drive continuous improvement initiatives to optimize processes reduce waste and enhance cost competitiveness,Lead improvement projects focused on enhancing efficiency reducing waste and delivering sustainable value,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
128,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Control production costs to ensure products are manufactured at the lowest possible cost while maximizing profit,R3,X,Monitor and analyze cost drivers to ensure effective cost control,Regularly review cost structure and implement improvement initiatives to achieve cost savings,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
129,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Use electricity and water efficiently.,R4,,Ensure effective control and efficient utilization of electricity and water consumption,Optimize energy utilization,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
130,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Conduct research and testing to improve the quality and features of existing products,R4,,Coordinate with relevant departments to implement improvements aligned with customer needs,Drive innovation initiatives and continuous improvement programs,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
131,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Carry out R&D activities to improve company products,R4,,Identify opportunities for product upgrades,Lead cross-functional collaboration to effectively implement improvement initiatives,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
132,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Closely coordinate with the R&D department to introduce new products into production.,R4,,Ensure new product implementation meets quality timeline and cost objectives,Maintain effective cross-functional collaboration to manage the transition of products with maximum efficiency,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
133,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Guide and supervise compliance with safety measures in production.,R4,,Proactively identify unsafe behaviors or conditions and implement corrective actions,Promote a strong safety culture by enhancing awareness accountability and continuous improvement,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
134,14472,Nguyen Dang Viet,Components,Production Assistant Manager - Comp.,Prepare for annual environmental sanitation inspections by authorities.,R4,,Coordinate with relevant departments to ensure audit and inspection activities are properly prepared,Monitor execution and drive accountability to ensure full compliance throughout inspection processes,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
135,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Identify inputs for production activities,R4,,Demonstrate strong capability in identifying key inputs for production operations,Regularly review and optimize input assumptions to minimize the risk of shortages or excess inventory,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
136,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Develop efficient production processes; allocate manpower machinery and materials appropriately to ensure completion of plans,R4,,Effectively evaluate and align processes machinery and manpower across different production stages,Optimize resource allocation to ensure efficiency and productivity,Ongoing,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Nhat Huynh
137,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Ensure production storage transportation and delivery processes are carried out effectively to meet business demands,R4,,Proactively identify risks and implement timely solutions to ensure on-time delivery and operational efficiency,Develop contingency plans to mitigate impacts on production and delivery operations,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
138,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Monitor coordinate and supervise production progress; promptly handle arising issues.,R4,,Ensure seamless cross-functional coordination to maintain continuous and efficient production while addressing issues promptly,Drive effective cross-functional communication to promptly resolve issues and minimize production disruptions,Ongoing,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Nhat Huynh
139,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Supervise and control all aspects of production activities to maximize the use of resources machinery and labor while minimizing waste.,R3,X,Drive operational efficiency through process optimization effective resource allocation and cost control,Continuously improve processes and optimize resource utilization to enhance productivity and reduce operational costs,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
140,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Ensure necessary raw materials for production are always available in the company.,R4,,Proactively collaborate with Procurement and Supply Chain teams to prevent shortages and mitigate supply risks,Anticipate supply risks and implement contingency plans such as alternative sourcing and safety stock strategies,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
141,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Establish product quality standards and regulations.,R4,,Regularly review and update quality standards to drive continuous improvement and maintain product consistency,Foster a culture of continuous improvement by integrating feedback evaluation results and operational data into quality enhancement initiatives,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
142,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Conduct quality inspections at each stage of production to ensure output meets required standards,R4,,Proactively identify defects early in the production process and implement corrective actions to prevent recurrence ensuring stable quality,Strengthen in-process quality control to minimize defects and ensure timely corrective actions to prevent recurrence,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
143,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Regularly update and improve processes to enhance product quality.,R4,,Continuously seek improvement opportunities and implement effective solutions to enhance product quality,Encourage and lead continuous improvement initiatives to enhance overall quality performance,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
144,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Manage and evaluate product quality within the company.,R4,,Effectively manage and evaluate product quality to ensure alignment with company standards and customer expectations,Leverage data analysis and customer feedback to drive continuous improvement,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
145,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Manage and optimize costs related to materials raw materials labor and machinery in the production process.,R3,X,Ensure effective control of key operational areas,Implement appropriate control and maintenance measures to ensure operational stability efficiency and cost optimization,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
146,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Minimize waste and defects to reduce product costs.,R4,,Drive continuous improvement initiatives to optimize processes reduce waste and enhance cost competitiveness,Lead improvement projects focused on enhancing efficiency reducing waste and delivering sustainable value,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
147,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Control production costs to ensure products are manufactured at the lowest possible cost while maximizing profit,R3,X,Monitor and analyze cost drivers to ensure effective cost control,Regularly review cost structure and implement improvement initiatives to achieve cost savings,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
148,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Use electricity and water efficiently.,R4,,Ensure effective control and efficient utilization of electricity and water consumption,Optimize energy utilization,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
149,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Conduct research and testing to improve the quality and features of existing products,R4,,Coordinate with relevant departments to implement improvements aligned with customer needs,Drive innovation initiatives and continuous improvement programs,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
150,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Carry out R&D activities to improve company products,R4,,Identify opportunities for product upgrades,Lead cross-functional collaboration to effectively implement improvement initiatives,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
151,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Closely coordinate with the R&D department to introduce new products into production.,R4,,Ensure new product implementation meets quality timeline and cost objectives,Maintain effective cross-functional collaboration to manage the transition of products with maximum efficiency,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
152,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Guide and supervise compliance with safety measures in production.,R4,,Proactively identify unsafe behaviors or conditions and implement corrective actions,Promote a strong safety culture by enhancing awareness accountability and continuous improvement,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
153,6829,Pham Hung Minh,Components,Production Assistant Manager - Comp.,Prepare for annual environmental sanitation inspections by authorities.,R4,,Coordinate with relevant departments to ensure audit and inspection activities are properly prepared,Monitor execution and drive accountability to ensure full compliance throughout inspection processes,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
154,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Identify inputs for production activities,R4,,Demonstrate strong capability in identifying key inputs for production operations,Regularly review and optimize input assumptions to minimize the risk of shortages or excess inventory,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
155,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Develop efficient production processes; allocate manpower machinery and materials appropriately to ensure completion of plans,R4,,Effectively evaluate and align processes machinery and manpower across different production stages,Optimize resource allocation to ensure efficiency and productivity,Ongoing,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Nhat Huynh
156,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Ensure production storage transportation and delivery processes are carried out effectively to meet business demands,R4,,Proactively identify risks and implement timely solutions to ensure on-time delivery and operational efficiency,Develop contingency plans to mitigate impacts on production and delivery operations,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
157,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Monitor coordinate and supervise production progress; promptly handle arising issues.,R4,,Ensure seamless cross-functional coordination to maintain continuous and efficient production while addressing issues promptly,Drive effective cross-functional communication to promptly resolve issues and minimize production disruptions,Ongoing,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Nhat Huynh
158,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Supervise and control all aspects of production activities to maximize the use of resources machinery and labor while minimizing waste.,R3,X,Drive operational efficiency through process optimization effective resource allocation and cost control,Continuously improve processes and optimize resource utilization to enhance productivity and reduce operational costs,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
159,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Ensure necessary raw materials for production are always available in the company.,R4,,Proactively collaborate with Procurement and Supply Chain teams to prevent shortages and mitigate supply risks,Anticipate supply risks and implement contingency plans such as alternative sourcing and safety stock strategies,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
160,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Establish product quality standards and regulations.,R4,,Regularly review and update quality standards to drive continuous improvement and maintain product consistency,Foster a culture of continuous improvement by integrating feedback evaluation results and operational data into quality enhancement initiatives,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
161,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Conduct quality inspections at each stage of production to ensure output meets required standards,R4,,Proactively identify defects early in the production process and implement corrective actions to prevent recurrence ensuring stable quality,Strengthen in-process quality control to minimize defects and ensure timely corrective actions to prevent recurrence,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
162,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Regularly update and improve processes to enhance product quality.,R4,,Continuously seek improvement opportunities and implement effective solutions to enhance product quality,Encourage and lead continuous improvement initiatives to enhance overall quality performance,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
163,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Manage and evaluate product quality within the company.,R4,,Effectively manage and evaluate product quality to ensure alignment with company standards and customer expectations,Leverage data analysis and customer feedback to drive continuous improvement,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
164,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Manage and optimize costs related to materials raw materials labor and machinery in the production process.,R3,X,Ensure effective control of key operational areas,Implement appropriate control and maintenance measures to ensure operational stability efficiency and cost optimization,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
165,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Minimize waste and defects to reduce product costs.,R4,,Drive continuous improvement initiatives to optimize processes reduce waste and enhance cost competitiveness,Lead improvement projects focused on enhancing efficiency reducing waste and delivering sustainable value,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
166,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Control production costs to ensure products are manufactured at the lowest possible cost while maximizing profit,R3,X,Monitor and analyze cost drivers to ensure effective cost control,Regularly review cost structure and implement improvement initiatives to achieve cost savings,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
167,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Use electricity and water efficiently.,R4,,Ensure effective control and efficient utilization of electricity and water consumption,Optimize energy utilization,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
168,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Conduct research and testing to improve the quality and features of existing products,R4,,Coordinate with relevant departments to implement improvements aligned with customer needs,Drive innovation initiatives and continuous improvement programs,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
169,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Carry out R&D activities to improve company products,R4,,Identify opportunities for product upgrades,Lead cross-functional collaboration to effectively implement improvement initiatives,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
170,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Closely coordinate with the R&D department to introduce new products into production.,R4,,Ensure new product implementation meets quality timeline and cost objectives,Maintain effective cross-functional collaboration to manage the transition of products with maximum efficiency,Ongoing,,Functional,Finance / Cost Management,Department Follow-up,Finance / Cost Management-up,Department / Functional SME,Nhat Huynh
171,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Guide and supervise compliance with safety measures in production.,R4,,Proactively identify unsafe behaviors or conditions and implement corrective actions,Promote a strong safety culture by enhancing awareness accountability and continuous improvement,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
172,6653,Nguyen Trong Thuy,Components,Leadsupervisor,Prepare for annual environmental sanitation inspections by authorities.,R4,,Coordinate with relevant departments to ensure audit and inspection activities are properly prepared,Monitor execution and drive accountability to ensure full compliance throughout inspection processes,Ongoing,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Nhat Huynh
173,23679,Danny Cao,IT,Manager,Business Requirement Governance,R4,,Captures requirements clearly; standards for documentation and traceability can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
174,23679,Danny Cao,IT,Manager,Process Analysis & Optimization,R4,,Strong at mapping current processes; benefit quantification needs to be more consistent.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
175,23679,Danny Cao,IT,Manager,Stakeholder Engagement & Alignment,R4,,Builds productive relationships; can further strengthen alignment across competing priorities.,Create stakeholder map and clear communication plan; lead alignment sessions for key projects,Q1: Map & plan | Q2: Run workshops | Q3Q4: Improve feedback (?80%),Need better alignment across teams; support needed for conflict resolution,Functional,Employee Relations,Department Follow-up,Employee Relations Follow-up,HRBP / Department,Jonathan To
176,23679,Danny Cao,IT,Manager,Project Prioritization & Backlog Governance,R4,X,Backlog is managed effectively; prioritization criteria need to be more transparent.,Define clear prioritization rules; standardize backlog process and improve transparency,Q1: Define criteria | Q2: Apply process | Q3: Track via dashboard,Backlog works but not transparent; need alignment with business owners,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
177,23679,Danny Cao,IT,Manager,ERP/System Enhancement Planning,R4,X,Supports enhancements well; long-term enhancement roadmap needs more ownership.,"Together with US team, Build roadmap; assign clear ownership; align with business goals",Q2: Draft roadmap | Q3: Finalize | Q4: Track progress,Need stronger ownership and long-term planning,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
178,23679,Danny Cao,IT,Manager,Change Impact Assessment,R2,X,Identifies system impacts accurately; downstream business impact analysis can go deeper.,"do more, learn more related system (ERP, Manufacturing, Distribution)",Q2: Draft roadmap | Q3: Finalize | Q4: Track progress,Need stronger ownership and long-term planning,Business Acumen,Business Acumen,Department Follow-up,Business Acumen Framework,Department / Functional SME,Jonathan To
179,23679,Danny Cao,IT,Manager,User Acceptance Testing Governance,R3,,Coordinates UAT effectively; issue tracking and closure metrics can be more disciplined,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
180,23679,Danny Cao,IT,Manager,Data Analysis & Reporting Governance,R3,,Provides reliable reporting support; analytical insight generation can be expanded.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
181,23679,Danny Cao,IT,Manager,Team Coaching & Analyst Development,R2,X,Supports team members well; competency development should be more structured.,Create skill framework; run monthly coaching; build team development plans,,Team support is good but not structured yet,Leadership,Leadership Skills,Add to Training Plan,Servant Leadership,L&D + HRBP,Jonathan To
182,23679,Danny Cao,IT,Manager,Master Data & Process Governance,R2,,Understands master data dependencies; governance routines need stronger consistency.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
183,23679,Danny Cao,IT,Manager,KPI Definition & Business Reporting Alignment,R2,,Understands reporting needs; KPI alignment with business outcomes needs more rigor.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
184,23679,Danny Cao,IT,Manager,Change Management & User Enablement,R4,,Supports user readiness activities; training and communication planning can be more proactive.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
185,23679,Danny Cao,IT,Manager,Executive Communication & Portfolio Reporting,R4,,Shares project status clearly; executive-level summaries should be more concise and insight-driven.,,,,Soft Skill,Communication Skills,Add to Training Plan,Communication & Presentation,L&D + HRBP,Jonathan To
186,56340,Leo Le,IT,Assistant Manager,Application Development Roadmap Alignment,R4,,Delivers assigned development work well; long-term product and architecture planning can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
187,56340,Leo Le,IT,Assistant Manager,System Architecture & Code Quality Governance,R3,,Applies sound technical judgment; coding standards and design review can be more consistent.,"Release for team/sub handle, monitoring only",,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
188,56340,Leo Le,IT,Assistant Manager,DevOps & Release Management,R3,,Handles releases reliably; automation and rollback planning should be strengthened.,"Release for team/sub handle, monitoring only",,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
189,56340,Leo Le,IT,Assistant Manager,System Stability & Incident Resolution,R4,,Resolves issues quickly; root cause documentation and preventive actions can improve.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
190,56340,Leo Le,IT,Assistant Manager,Integration Management (API / ERP / 3rd Party),R4,X,Supports integrations effectively; scalability and dependency planning need more attention.,Need strong support for ERP/WMS and API team,Monthly Integration Health-check with 3rd Party teams or when new project start,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
191,56340,Leo Le,IT,Assistant Manager,Technical Debt Management,R4,,Understands legacy constraints; remediation planning is not yet sufficiently structured.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
192,56340,Leo Le,IT,Assistant Manager,Performance Optimization & Monitoring,R4,,Improves performance when issues arise; proactive monitoring can be more systematic.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
193,56340,Leo Le,IT,Assistant Manager,User Support Governance (L2/L3),R3,,Provides effective support for complex issues; service metrics should be more visible.,"Release for team/sub handle, monitoring only",,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
194,56340,Leo Le,IT,Assistant Manager,Development Team Mentoring,R4,,Gives strong technical support to team members; delegation and coaching depth can increase.,,,,People Development,Coaching Skills,Add to Training Plan,Train the Trainer / Coaching Program,L&D + HRBP,Jonathan To
195,56340,Leo Le,IT,Assistant Manager,Security in Development (Secure Coding Practice),R4,,Applies basic secure coding principles; secure SDLC practices should be more formalized.,,,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
196,56340,Leo Le,IT,Assistant Manager,Application Lifecycle Management,R4,X,Understands full system lifecycle; release-to-retirement planning needs stronger structure.,Need Product owner and all team manager to collaborate sooner to optimize my technical solution.,2026-05-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
197,56340,Leo Le,IT,Assistant Manager,Business Requirement Translation into Technical Solutions,R4,X,Translates needs into workable solutions; requirement clarification can start earlier.,Find solutions to minimize costs while achieving the expected results for business,Once Business requirements are gathered,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
198,56340,Leo Le,IT,Assistant Manager,Testing Strategy & Quality Assurance Coordination,R3,X,Supports testing activities well; test coverage and quality gates should be more consistent.,"Building a team with sufficient knowledge to execute QA/UAT. Implementing a rotation program between Dev and QA teams to enhance cross-functional skills, ensuring faster deployment cycles and high-quality production releases.",2026-06-01 00:00:00,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To
199,56340,Leo Le,IT,Assistant Manager,Resource Planning & Task Prioritization,R4,X,Manages team workload reasonably well; prioritization under competing demand can improve.,Prioritizing high-value objectives to maintain focus on business Requirement. Requesting management support to ensure transparency and clear separation of requirements/resources from higher levels.,2026-05-01 00:00:00,,Functional,Workforce Planning,Department Follow-up,Workforce / Ramp Planning Follow-up,Department / Functional SME,Jonathan To
200,56340,Leo Le,IT,Assistant Manager,Documentation & Knowledge Transfer,R3,,Maintains key knowledge informally; documentation and handover discipline should be improved.,"Release for team/sub handle, monitoring only",,,Functional,Process & Compliance,Department Follow-up,Process Improvement / Compliance Follow-up,Department / Functional SME,Jonathan To`;
