export const rawWanekIDPTSV_part5 = `Emp Code	Person Name	Department	Critical Role	Job Duty	R Rating	Top Opp.	Comments	Way Forward	Timeline	Notes	Training Category	Competency Focus	Action	Proposed Program	Program Owner	Source Owner
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Budget development & management	R1		Confident in HR budgeting and cost control	Support cross-functional budgeting			Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Succession Planning	R2		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Personal Development (Sharpen the Saw)	R3		Development activities not fully structured	Create and follow IDP			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Operational Knowlegde & understanding (Business Sense)	R3		Strong understanding of business operations	Mentor junior HR staff			Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Timely Decision Making	R3	X	Makes sound and timely decision	Maintain decision frameworks	Q2		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Building and Promoting a Company Culture	R3		Actively drives culture initiatives	Scale culture programs			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Promoting a Teamwork environment	R3	X	Encourages collaboration across teams	Lead cross-functional projects	Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Maintaining and Developing a Culture around our Core and Growth Values	R3		Values embedded in daily HR practices	Reinforce through HR processes			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Effective Communications	R2	X	Communicates clearly and effectively	Coach team on communication	Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Coaching and Mentoring	R2		Willing but lacks structured coaching skills	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Employee Relations Improvement	R3		Handles ER cases effectively	Share ER best practices			Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Hai Long
22556	Mai Hai Long	UPH Support WNK3	Production Assistant Manager - UPH	Quality Control & Issue Solving	R3		Monitoring processes, identifying root cause, and implementing effective corrective and preventive actions	Maintains consistent quality and resolves issues in a timely manner			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Hai Long
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Ramp Plan Development	R2		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Ramp Plan Execution & Shipment Delivery	R3	X	Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Resource Management (Human)	R3	X	Strong workforce planning and allocation	Coach others on resource planning	Q3		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Resource Development (Human)	R2		Actively supports people development	Expand development initiatives			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Budget development & management	R1		Confident in HR budgeting and cost control	Support cross-functional budgeting			Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Succession Planning	R2		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Personal Development (Sharpen the Saw)	R3		Development activities not fully structured	Create and follow IDP			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Operational Knowlegde & understanding (Business Sense)	R3		Strong understanding of business operations	Mentor junior HR staff			Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Timely Decision Making	R3		Makes sound and timely decision	Maintain decision frameworks			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Building and Promoting a Company Culture	R3		Actively drives culture initiatives	Scale culture programs			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Promoting a Teamwork environment	R3	X	Encourages collaboration across teams	Lead cross-functional projects	Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Maintaining and Developing a Culture around our Core and Growth Values	R3		Values embedded in daily HR practices	Reinforce through HR processes			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Effective Communications	R2		Communicates clearly and effectively	Coach team on communication			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Employee Relations Improvement	R3		Handles ER cases effectively	Share ER best practices			Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ngo Huu Chi
22179	Ngo Huu Chi	UPH Support WNK3	Production Assistant Manager - UPH	Quality Control & Issue Solving	R3		Monitoring processes, identifying root cause, and implementing effective corrective and preventive actions	Maintains consistent quality and resolves issues in a timely manner			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ngo Huu Chi
04478	Thuy Do	Cut&Sew WNK3	Leadsupervisor	Ramp Plan Development	R3	X	Area-focused	Lead cross-area ramps	Q3–Q4		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Thuy Do
04478	Thuy Do	Cut&Sew WNK3	Leadsupervisor	Resource Management (Human)	R4		Strong control	Mentor juniors	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Thuy Do
04478	Thuy Do	Cut&Sew WNK3	Leadsupervisor	Resource Development (People)	R3	X	Team-level only	Build pipeline	Q2–Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Thuy Do
04478	Thuy Do	Cut&Sew WNK3	Leadsupervisor	Budget & Cost Control	R2	X	Limited exposure	Join budget cycles	Annual		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Thuy Do
04478	Thuy Do	Cut&Sew WNK3	Leadsupervisor	Succession Planning	R3	X	Conceptual	Own leather plan	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Thuy Do
04478	Thuy Do	Cut&Sew WNK3	Leadsupervisor	Coaching & Mentoring	R3	X	Unstructured	Formal coaching	Q2–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Thuy Do
19395	Bui Van Thap	Cut&Sew WNK3	Leadsupervisor	Ramp Plan Development	R4		Strong ramp planning execution	Lead cross-area ramp initiatives	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Bui Van Thap
19395	Bui Van Thap	Cut&Sew WNK3	Leadsupervisor	Resource Management (Human)	R4		Strong manpower planning	Mentor peers	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Bui Van Thap
19395	Bui Van Thap	Cut&Sew WNK3	Leadsupervisor	Resource Development (People)	R3	X	Needs broader pipeline focus	Coach 1–2 successors	Q2–Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Bui Van Thap
19395	Bui Van Thap	Cut&Sew WNK3	Leadsupervisor	Budget & Cost Control	R3	X	Limited budget exposure	Join budget reviews	Annual		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Bui Van Thap
19395	Bui Van Thap	Cut&Sew WNK3	Leadsupervisor	Succession Planning	R3	X	Limited ownership	Co-lead with HR	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Bui Van Thap
19395	Bui Van Thap	Cut&Sew WNK3	Leadsupervisor	Coaching & Mentoring	R2	X	Unstructured coaching	Training + GROW model	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Bui Van Thap
19035	Pham Dinh Tung	Cut&Sew WNK3	Supervisor	Ramp Plan Development	R4		Consistent execution	Expand cross-shift scope	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Pham Dinh Tung
19035	Pham Dinh Tung	Cut&Sew WNK3	Supervisor	Resource Management (Human)	R4		Strong daily control	Coach peers	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Pham Dinh Tung
19035	Pham Dinh Tung	Cut&Sew WNK3	Supervisor	Resource Development (People)	R3	X	Execution focused	Build team IDPs	Q2–Q4		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Pham Dinh Tung
19035	Pham Dinh Tung	Cut&Sew WNK3	Supervisor	Budget & Cost Control	R3	X	Limited strategy exposure	Join cost review	Annual		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Pham Dinh Tung
19035	Pham Dinh Tung	Cut&Sew WNK3	Supervisor	Succession Planning	R3	X	Basic understanding	Own 1 plan	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Pham Dinh Tung
19035	Pham Dinh Tung	Cut&Sew WNK3	Supervisor	Coaching & Mentoring	R3	X	Task coaching only	Structured coaching	Q2–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Pham Dinh Tung
04822	Vo Chi Tinh	Cut&Sew WNK3	Supervisor	Ramp Plan Development	R3	X	Limited exposure	Join day shift ramps	Q3–Q4		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Chi Tinh
04822	Vo Chi Tinh	Cut&Sew WNK3	Supervisor	Resource Management (Human)	R4		Reliable manpower mgmt	Share best practices	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Chi Tinh
04822	Vo Chi Tinh	Cut&Sew WNK3	Supervisor	Resource Development (People)	R3	X	Ops focused	Coach night leads	Q2–Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Chi Tinh
04822	Vo Chi Tinh	Cut&Sew WNK3	Supervisor	Budget & Cost Control	R2	X	Low exposure	Learn cost drivers	Q4		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Chi Tinh
04822	Vo Chi Tinh	Cut&Sew WNK3	Supervisor	Succession Planning	R3	X	Support role only	Join discussions	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vo Chi Tinh
04822	Vo Chi Tinh	Cut&Sew WNK3	Supervisor	Coaching & Mentoring	R2	X	Informal	Training & practice	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vo Chi Tinh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Ramp Plan Development/Capacity Planning	R4		Continue best practices and share knowledge				Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Material Requirements Planning (MRP)	R4		Continue best practices and share knowledge				Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Master Production Schedule (MPS)	R4		Continue best practices and share knowledge				People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Scenario Planning (Whatif Scenario)	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Coordinate with US team	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Supply Chain Collaboration	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Drive for globalization tasks	R4		Continue best practices and share knowledge				Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Overseeing the entire execution	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	System enhancement (AS400, Mapics, Helix, etc)	R4		Continue best practices and share knowledge				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Ramp Plan Execution & Tracking (execute ramp actions; track actual vs plan; adjust)	R4		Continue best practices and share knowledge				Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Drive for process improvement	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Drive for Innovation Ideas	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Operational Knowlegde & understanding (Business Sense)	R4		Continue best practices and share knowledge				Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Overall Busines Acumen from Market/Industry	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Balances productivity, cost, safety and morale to achieve positive results in all areas	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Disaster Recovery Planning	R3		Good now but still more room to moving forward				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Promoting a Teamwork environment	R3		Good now but still more room to moving forward				People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Maintaining and Developing a Culture around our Core and Growth Values	R3	X	Good now but still more room to moving forward	"Inpriration team with bigger vision, bigger picture. To build a strong culture, leaders must:

Clarify values into daily behaviors
Role-model those behaviors consistently
Embed values into systems and processes
Recognize and reward value-aligned behavior
Correct misaligned behavior quickly and fairly
Coach leaders at every level to multiply the culture
Communicate values through stories, decisions, and actions"			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Coaching and Mentoring	R3	X	Willing but lacks structured coaching skills	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Employee Relations Improvement	R4		Continue best practices and share knowledge				Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Monitoring departmental/team performance measures	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Succession Planning	R3	X	"Need to work on Succession Planning so that 
you can grow more"	"Definted the next level (got candidate alredy), 
Definte succession planning for that candidate first 
KT to follow and work with a.Kelvin on this"			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Personal Professional Development Plan	R3		Need more practice	Follow current HR L&D program			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Hire and train new team player	R4		Continue best practices and share knowledge	Need some courses training			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Build the high performing team	R3		Good now but still more room to moving forward	Need some courses training			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Department Compliance	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Strategic Supply	R3		Good now but still more room to moving forward				Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Weekly/Monthly/Quarterly Report or Dashboard reflection	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Problem Solving	R3		Good now but still more room to moving forward	"Join the HR training and practice more frequently. 
How to clearly define root cause, Corrective action, Preventive action to repeat issue happen again"			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Effective Communications	R3	X	Communicates clearly but still have more rooms to keep improvement for upper level such as proactive alignment ahead of time	Coach team on communication: Short sentences, Clear logic, No operational detail unless asked, may need some story telling and proactive alignment ahead of time			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Decision Making	R4		Continue best practices and share knowledge				Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Critical Thinking	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Stakeholder Management	R3	X	okay now but still have more rooms to keep improvement with upper level	More confident when having meeting with other BODs. Build stronger connetion/trust with BOD			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Cross Functional Management	R3		Good now but still more room to moving forward				Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	Customer Satisfaction & On-time Shipment (ensure plans meet customer commitment)	R4		Continue best practices and share knowledge				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Kelvin Huynh
1564	Kelvin Huynh	Planning & Inventory Control	Senior Manager	"Power BI/SQL Dashboard, power automate Ownership: 
Elimination of manual reporting for the team + Applying AI in Daily Work"	R3		Good now but still more room to moving forward				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Kelvin Huynh
20170	Tom Nguyen	Planning & Inventory Control	Manager	Ramp Plan Development/Capacity Planning	R4						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Material Requirements Planning (MRP)	R4						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Master Production Schedule (MPS)	R4						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Scenario Planning (Whatif Scenario)	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Coordinate with US team	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Supply Chain Collaboration	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Drive for globalization tasks	R4						Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Inventory Accuracy	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Recording Transaction	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	WIP Control & Cycle Count Performance (plan/monitor; improve inventory accuracy)	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Overseeing the entire execution	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Production schedule optimization	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	System enhancement (AS400, Mapics, Helix, etc)	R4						Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Ramp Plan Execution & Tracking (execute ramp actions; track actual vs plan; adjust)	R4						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Day-to-day Production Constraints Resolution (identify, communicate, remove blockers)	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Drive for process improvement	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Drive for Innovation Ideas	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Operational Knowlegde & understanding (Business Sense)	R3		Need to have a bigger picture than just Wanek Opearation	KT & Kelvin to work on this			Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Overall Busines Acumen from Market/Industry	R2	X	"Gradually improvement by getting sharing information
 from Management & Social Media"	KT & Kelvin to work on this			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Balances productivity, cost, safety and morale to achieve positive results in all areas	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Direct the planning team and resolve day to day production constraints	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Disaster Recovery Planning	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Promoting a Teamwork environment	R4						People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Maintaining and Developing a Culture around our Core and Growth Values	R3		Willing to do but need to be trained thru professional course	"Inpriration team with bigger vision, bigger picture. To build a strong culture, leaders must:

Clarify values into daily behaviors
Role-model those behaviors consistently
Embed values into systems and processes
Recognize and reward value-aligned behavior
Correct misaligned behavior quickly and fairly
Coach leaders at every level to multiply the culture
Communicate values through stories, decisions, and actions"			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Coaching and Mentoring	R3	X	Willing but lacks structured coaching skills	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Employee Relations Improvement	R3		Good within UPH and will need to expan for bigger scope/group	Need to expan for bigger scope/group			Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Monitoring departmental/team performance measures	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Succession Planning	R3	X	Willing but lacks structured guidelines and need more focus to build up next level ASAP	"KT/a.Kelvin to provide more help on this.
Let's target to have some possitive output in 2026 first"			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Personal Professional Development Plan	R3	X	Willing but lacks structured skills and train successor	Follow-up closely HR training + coaching/mentoring from KT/a.Kelvin			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Hire and train new team player	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Build the high performing team	R4						Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Department Compliance	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen`;
