export const rawWanekIDPTSV_part5 = `14115	Dang Van Tan	Maintenance	Supervisor	"Monitor, coordinate, and supervise work progress; handle arising issues
Theo dõi, điều phối và giám sát tiến độ công việc, kịp thời xử lý các vấn đề phát sinh."	R4		"Effectively schedules maintenance work and resolves downtime issues swiftly
Bố trí công việc sửa chữa tốt, xử lý nhanh các sự cố dừng máy."	"Standardize maintenance request logs and optimize response procedures
Chuẩn hóa nhật ký yêu cầu sửa chữa, tối ưu hóa quy trình phản hồi."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Manage and optimize spare parts inventory
Quản lý, tối ưu hóa lượng vật tư phụ tùng dự phòng."	R4		"Controls critical spare parts effectively to prevent stockouts and minimize excess
Kiểm soát tốt lượng vật tư dự phòng, hạn chế tối đa thiếu hụt phụ tùng then chốt."	"Research and implement predictive parts lifetime modeling
Nghiên cứu ứng dụng mô hình dự báo tuổi thọ thiết bị để tối ưu tồn kho phụ tùng."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Evaluate team performance and build continuous development plans
Đánh giá hiệu quả công việc của đội nhóm, lên kế hoạch phát triển liên tục"	R3	X	"Conducts assessments; however, structured technical training pathways can improve
Có đánh giá tay nghề nhưng cần hệ thống hóa các chuyên đề đào tạo kỹ thuật."	"Establish a comprehensive technical skill matrix and peer-to-peer training
Xây dựng ma trận kỹ năng kỹ thuật chi tiết, tổ chức đào tạo chéo trong tổ."	On going		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Develop organizational structure, execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo theo kế hoạch"	R3	X	"Meets requirements but needs to map out strong backups for specialized machinery
Đáp ứng định biên nhưng cần quy hoạch nhân sự dự phòng cho các máy chuyên dụng."	"Identify and mentor high-potential technicians for critical machine groups
Nhận diện và bồi dưỡng thợ giỏi chuyên sâu cho các nhóm máy quan trọng."	Q3-2026		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Allocate maintenance technicians effectively to meet operational needs
Tổ chức sắp xếp nhân lực làm việc phù hợp đáp ứng nhu cầu công việc"	R4		"Deploys technicians logically to balance preventive maintenance and urgent repairs
Sắp xếp thợ máy hợp lý, cân bằng tốt giữa bảo trì định kỳ và sửa chữa khẩn cấp."	"Cross-train technicians across electrical and mechanical disciplines
Đào tạo đa năng thợ máy (cả điện và cơ khí) để tăng tính linh hoạt."	On going		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Guide and supervise compliance with daily safety (EHS) and fire safety regulations
Hướng dẫn, nhắc nhở ATLĐ, ATPCCN hằng ngày và giám sát việc tuân thủ thực hiện"	R4		"Enforces safety guidelines stringently during high-risk maintenance tasks
Giám sát an toàn nghiêm túc, đặc biệt đối với các công việc sửa chữa trên cao hoặc nguồn điện."	"Standardize Lock-Out / Tag-Out (LOTO) checklists for all technicians
Chuẩn hóa và giám sát chặt chẽ quy trình LOTO đối với mọi thợ sửa máy."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Conduct research and testing to optimize and improve work processes
Nghiên cứu, thử nghiệm để cải tiến quy trình làm việc hiệu quả và tối ưu"	R3	X	"Open to improvements; implementation speed for preventive projects can be improved
Sẵn sàng cải tiến nhưng cần chủ động thúc đẩy các giải pháp ngăn ngừa sự cố."	"Adopt autonomous maintenance concepts (TPM) to improve machine lifetime
Ứng dụng các khái niệm bảo trì tự quản (TPM) để tăng tuổi thọ máy móc."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Organize and participate in employee engagement activities
Tổ chức và tham gia các hoạt động gắn kết NLĐ"	R4		"Creates a supportive and collaborative team environment for technicians
Tạo môi trường làm việc chia sẻ, đoàn kết và sẵn sàng hỗ trợ kỹ thuật lẫn nhau."	"Establish daily technical huddles to share complex troubleshooting solutions
Duy trì họp nhanh đầu ngày để chia sẻ các ca sửa máy khó trong ngày."	On going		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Manage, utilize, and optimize operational costs
Quản lý, sử dụng và tiết kiệm các khoản chi phí phát sinh"	R3	X	"Controls maintenance spending; parts refurbishment can be optimized to save costs
Kiểm soát tốt ngân sách; có thể tăng cường phục hồi linh kiện cũ để tiết kiệm."	"Develop a repair-over-replace initiative for select cylinder and valve parts
Xây dựng chuyên đề phục hồi và tái sử dụng linh kiện để tối ưu chi phí."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	"Prepare for annual external compliance audits (environmental, fire safety, boiler)
Chuẩn bị cho công tác kiểm tra Vệ sinh môi trường và PCCC hằng năm"	R4		"Passes all technical compliance inspections (boiler, electrical rooms) successfully
Chuẩn bị chu đáo, đạt các chuẩn kiểm định thiết bị nghiêm ngặt."	"Establish a strict compliance calendar for boiler and electrical room audits
Xây dựng lịch rà soát định kỳ các thiết bị có yêu cầu nghiêm ngặt về an toàn."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
14115	Dang Van Tan	Maintenance	Supervisor	Học hỏi công cụ AI để lập kế hoạch cải thiện hiệu quả công việc, giảm thời gian làm báo cáo thủ công	R2	X	Cải tiến hiệu quả công việc	Học phần mềm Copilot, power BI và phối hợp các bộ phận liên quan triển khai	Q2–Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Monitor, coordinate, and supervise work progress; handle arising issues
Theo dõi, điều phối và giám sát tiến độ công việc, kịp thời xử lý các vấn đề phát sinh."	R4		"Effectively schedules maintenance work and resolves downtime issues swiftly
Bố trí công việc sửa chữa tốt, xử lý nhanh các sự cố dừng máy."	"Standardize maintenance request logs and optimize response procedures
Chuẩn hóa nhật ký yêu cầu sửa chữa, tối ưu hóa quy trình phản hồi."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Manage and optimize spare parts inventory
Quản lý, tối ưu hóa lượng vật tư phụ tùng dự phòng."	R4		"Controls critical spare parts effectively to prevent stockouts and minimize excess
Kiểm soát tốt lượng vật tư dự phòng, hạn chế tối đa thiếu hụt phụ tùng then chốt."	"Research and implement predictive parts lifetime modeling
Nghiên cứu ứng dụng mô hình dự báo tuổi thọ thiết bị để tối ưu tồn kho phụ tùng."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Evaluate team performance and build continuous development plans
Đánh giá hiệu quả công việc của đội nhóm, lên kế hoạch phát triển liên tục"	R3	X	"Conducts assessments; however, structured technical training pathways can improve
Có đánh giá tay nghề nhưng cần hệ thống hóa các chuyên đề đào tạo kỹ thuật."	"Establish a comprehensive technical skill matrix and peer-to-peer training
Xây dựng ma trận kỹ năng kỹ thuật chi tiết, tổ chức đào tạo chéo trong tổ."	On going		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Develop organizational structure, execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo theo kế hoạch"	R3	X	"Meets requirements but needs to map out strong backups for specialized machinery
Đáp ứng định biên nhưng cần quy hoạch nhân sự dự phòng cho các máy chuyên dụng."	"Identify and mentor high-potential technicians for critical machine groups
Nhận diện và bồi dưỡng thợ giỏi chuyên sâu cho các nhóm máy quan trọng."	Q3-2026		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Allocate maintenance technicians effectively to meet operational needs
Tổ chức sắp xếp nhân lực làm việc phù hợp đáp ứng nhu cầu công việc"	R4		"Sắp xếp thợ máy hợp lý, cân bằng tốt giữa bảo trì định kỳ và sửa chữa khẩn cấp."	"Cross-train technicians across electrical and mechanical disciplines
Đào tạo đa năng thợ máy (cả điện và cơ khí) để tăng tính linh hoạt."	On going		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Guide and supervise compliance with daily safety (EHS) and fire safety regulations
Hướng dẫn, nhắc nhở ATLĐ, ATPCCN hằng ngày và giám sát việc tuân thủ thực hiện"	R4		"Enforces safety guidelines stringently during high-risk maintenance tasks
Giám sát an toàn nghiêm túc, đặc biệt đối với các công việc sửa chữa trên cao hoặc nguồn điện."	"Standardize Lock-Out / Tag-Out (LOTO) checklists for all technicians
Chuẩn hóa và giám sát chặt chẽ quy trình LOTO đối với mọi thợ sửa máy."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Conduct research and testing to optimize and improve work processes
Nghiên cứu, thử nghiệm để cải tiến quy trình làm việc hiệu quả và tối ưu"	R3	X	"Open to improvements; implementation speed for preventive projects can be improved
Sẵn sàng cải tiến nhưng cần chủ động thúc đẩy các giải pháp ngăn ngừa sự cố."	"Adopt autonomous maintenance concepts (TPM) to improve machine lifetime
Ứng dụng các khái niệm bảo trì tự quản (TPM) để tăng tuổi thọ máy móc."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Organize and participate in employee engagement activities
Tổ chức và tham gia các hoạt động gắn kết NLĐ"	R4		"Creates a supportive and collaborative team environment for technicians
Tạo môi trường làm việc chia sẻ, đoàn kết và sẵn sàng hỗ trợ kỹ thuật lẫn nhau."	"Establish daily technical huddles to share complex troubleshooting solutions
Duy trì họp nhanh đầu ngày để chia sẻ các ca sửa máy khó trong ngày."	On going		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Manage, utilize, and optimize operational costs
Quản lý, sử dụng và tiết kiệm các khoản chi phí phát sinh"	R3	X	"Controls maintenance spending; parts refurbishment can be optimized to save costs
Kiểm soát tốt ngân sách; có thể tăng cường phục hồi linh kiện cũ để tiết kiệm."	"Develop a repair-over-replace initiative for select cylinder and valve parts
Xây dựng chuyên đề phục hồi và tái sử dụng linh kiện để tối ưu chi phí."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
17342	Mai Hai Long	Maintenance	Specialist	"Prepare for annual external compliance audits (environmental, fire safety, boiler)
Chuẩn bị cho công tác kiểm tra Vệ sinh môi trường và PCCC hằng năm"	R4		"Passes all technical compliance inspections (boiler, electrical rooms) successfully
Chuẩn bị chu đáo, đạt các chuẩn kiểm định thiết bị nghiêm ngặt."	"Establish a strict compliance calendar for boiler and electrical room audits
Xây dựng lịch rà soát định kỳ các thiết bị có yêu cầu nghiêm ngặt về an toàn."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Monitor, coordinate, and supervise work progress; handle arising issues
Theo dõi, điều phối và giám sát tiến độ công việc, kịp thời xử lý các vấn đề phát sinh."	R4		"Effectively schedules maintenance work and resolves downtime issues swiftly
Bố trí công việc sửa chữa tốt, xử lý nhanh các sự cố dừng máy."	"Standardize maintenance request logs and optimize response procedures
Chuẩn hóa nhật ký yêu cầu sửa chữa, tối ưu hóa quy trình phản hồi."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Manage and optimize spare parts inventory
Quản lý, tối ưu hóa lượng vật tư phụ tùng dự phòng."	R4		"Controls critical spare parts effectively to prevent stockouts and minimize excess
Kiểm soát tốt lượng vật tư dự phòng, hạn chế tối đa thiếu hụt phụ tùng then chốt."	"Research and implement predictive parts lifetime modeling
Nghiên cứu ứng dụng mô hình dự báo tuổi thọ thiết bị để tối ưu tồn kho phụ tùng."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Evaluate team performance and build continuous development plans
Đánh giá hiệu quả công việc của đội nhóm, lên kế hoạch phát triển liên tục"	R3	X	"Conducts assessments; however, structured technical training pathways can improve
Có đánh giá tay nghề nhưng cần hệ thống hóa các chuyên đề đào tạo kỹ thuật."	"Establish a comprehensive technical skill matrix and peer-to-peer training
Xây dựng ma trận kỹ năng kỹ thuật chi tiết, tổ chức đào tạo chéo trong tổ."	On going		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Develop organizational structure, execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo theo kế hoạch"	R3	X	"Meets requirements but needs to map out strong backups for specialized machinery
Đáp ứng định biên nhưng cần quy hoạch nhân sự dự phòng cho các máy chuyên dụng."	"Identify and mentor high-potential technicians for critical machine groups
Nhận diện và bồi dưỡng thợ giỏi chuyên sâu cho các nhóm máy quan trọng."	Q3-2026		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Allocate maintenance technicians effectively to meet operational needs
Tổ chức sắp xếp nhân lực làm việc phù hợp đáp ứng nhu cầu công việc"	R4		"Sắp xếp thợ máy hợp lý, cân bằng tốt giữa bảo trì định kỳ và sửa chữa khẩn cấp."	"Cross-train technicians across electrical and mechanical disciplines
Đào tạo đa năng thợ máy (cả điện và cơ khí) để tăng tính linh hoạt."	On going		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Guide and supervise compliance with daily safety (EHS) and fire safety regulations
Hướng dẫn, nhắc nhở ATLĐ, ATPCCN hằng ngày và giám sát việc tuân thủ thực hiện"	R4		"Enforces safety guidelines stringently during high-risk maintenance tasks
Giám sát an toàn nghiêm túc, đặc biệt đối với các công việc sửa chữa trên cao hoặc nguồn điện."	"Standardize Lock-Out / Tag-Out (LOTO) checklists for all technicians
Chuẩn hóa và giám sát chặt chẽ quy trình LOTO đối với mọi thợ sửa máy."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Conduct research and testing to optimize and improve work processes
Nghiên cứu, thử nghiệm để cải tiến quy trình làm việc hiệu quả và tối ưu"	R3	X	"Open to improvements; implementation speed for preventive projects can be improved
Sẵn sàng cải tiến nhưng cần chủ động thúc đẩy các giải pháp ngăn ngừa sự cố."	"Adopt autonomous maintenance concepts (TPM) to improve machine lifetime
Ứng dụng các khái niệm bảo trì tự quản (TPM) để tăng tuổi thọ máy móc."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Organize and participate in employee engagement activities
Tổ chức và tham gia các hoạt động gắn kết NLĐ"	R4		"Creates a supportive and collaborative team environment for technicians
Tạo môi trường làm việc chia sẻ, đoàn kết và sẵn sàng hỗ trợ kỹ thuật lẫn nhau."	"Establish daily technical huddles to share complex troubleshooting solutions
Duy trì họp nhanh đầu ngày để chia sẻ các ca sửa máy khó trong ngày."	On going		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Manage, utilize, and optimize operational costs
Quản lý, sử dụng và tiết kiệm các khoản chi phí phát sinh"	R3	X	"Controls maintenance spending; parts refurbishment can be optimized to save costs
Kiểm soát tốt ngân sách; có thể tăng cường phục hồi linh kiện cũ để tiết kiệm."	"Develop a repair-over-replace initiative for select cylinder and valve parts
Xây dựng chuyên đề phục hồi và tái sử dụng linh kiện để tối ưu chi phí."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
70603	Ngo Huu Chi	Maintenance	Supervisor	"Prepare for annual external compliance audits (environmental, fire safety, boiler)
Chuẩn bị cho công tác kiểm tra Vệ sinh môi trường và PCCC hằng năm"	R4		"Passes all technical compliance inspections (boiler, electrical rooms) successfully
Chuẩn bị chu đáo, đạt các chuẩn kiểm định thiết bị nghiêm ngặt."	"Establish a strict compliance calendar for boiler and electrical room audits
Xây dựng lịch rà soát định kỳ các thiết bị có yêu cầu nghiêm ngặt về an toàn."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
-	Thuy Do	Finance	Manager	Enterprise Budgeting & Financial Modeling	R4		Demonstrates high expertise; financial modeling for new business units needs alignment with corporate templates.	Attend corporate financial modeling workshops; co-develop division's budget projection model	Q2–Q3		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Elsa Nguyen
-	Thuy Do	Finance	Manager	Variance Analysis & Cost Controls	R4		Provides detailed monthly variance reports; root-cause analysis for manufacturing variances can improve.	Establish monthly variance review meeting with Plant Managers; implement corrective action tracker	Q2–Q4		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Elsa Nguyen
-	Thuy Do	Finance	Manager	Financial System Governance & Compliance	R4		Maintains high discipline; data standardization across divisions needs consistent oversight.	Conduct quarterly system compliance audits; standardize accounting data flows	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
-	Thuy Do	Finance	Manager	Working Capital & Cash Flow Management	R4		Manages routine working capital effectively; forecasting models can be further optimized.	Design automated 13-week rolling cash flow forecasting sheet; review weekly with Director	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Elsa Nguyen
-	Thuy Do	Finance	Manager	Capex Evaluation & ROI Analysis	R3	X	Evaluates CAPEX projects competently; post-implementation audit procedures need formal structure.	Establish Capex post-audit framework; evaluate 3 major projects completed last year	Q3		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Elsa Nguyen
-	Thuy Do	Finance	Manager	Executive Dashboard & Financial Storytelling	R3	X	Builds reports well; presentation of financial stories to senior leadership needs strategic focus.	Co-present monthly financial review to Board; receive feedback on executive delivery style	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Elsa Nguyen
-	Thuy Do	Finance	Manager	Team Leadership & Mentoring	R4		Mentors direct reports effectively; technical skill development path should be more structured.	Create structured finance-competency roadmap; run monthly coaching sessions with team	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Elsa Nguyen
-	Thuy Do	Finance	Manager	Cross-Functional Synergy (Ops / SC / HR)	R4		Strong relationships; collaborative cost-saving initiatives can be proactively led.	Lead cross-functional cost-reduction taskforce (Finance/Ops/SC); target 5% waste reduction	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Elsa Nguyen
-	Thuy Do	Finance	Manager	Tax Compliance & Audit Representation	R4		Ensures full tax compliance; leading external tax audits is an area for continued experience.	Act as main liaison for upcoming corporate tax audit; coordinate documentation prep	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
-	Thuy Do	Finance	Manager	Strategic Decision Support & Business Case Analysis	R3	X	Analyzes standard cases well; strategic options evaluation should be more structured.	Shadow Finance Director on 2 strategic business expansion evaluations; write-up case studies	Q3–Q4		Business Acumen	Business Acumen	Department Follow-up	Business Acumen Framework	Department / Functional SME	Elsa Nguyen
01116	Bui Van Thap	Quality	Supervisor	Maintain SOP and audit standards in production lines.	R4		Ensures high compliance with standard operating procedures across lines.	Conduct periodic auditor calibration sessions to maintain consistent standards.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Oversee final inspection (OBQ) and line audits.	R4		OBQ results are highly reliable; issues are addressed quickly.	Develop an automated OBQ defect log on Helix/tablet.	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Analyze defect trends and lead corrective actions (CAPA).	R3	X	Identifies defects; however, root cause analysis can be more structured.	Attend structured problem-solving (8D) training; lead 2 critical CAPAs this year.	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Support customer audit preparation and compliance checks.	R4		Compliance files are well-maintained; audits pass consistently.	Coordinate standard prep checklists across all sections before audits.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Track quality metrics (scrap rate, defect rate, rework).	R4		Maintains precise databases; reports are timely and accurate.	Build a visual quality-metrics board at the main assembly area.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Provide on-the-job training for inspectors and operators.	R4		Provides excellent, clear training on defect-limit samples.	Standardize the visual limit-sample boards for new models.	Ongoing		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Manage and evaluate performance of quality inspectors.	R3	X	Evaluates well operationally; needs a more structured coaching approach.	Participate in company's supervisory mentoring program; build 1-1 coaching plans.	Q2–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Collaborate with Production on quality issue resolution.	R4		Collaborates well; needs more proactive intervention during initial runs.	Establish daily pre-shift quality syncs with Production Supervisors.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
01116	Bui Van Thap	Quality	Supervisor	Manage quality department costs and equipment calibration.	R3		Tracks calibration well; budget cost-savings can be improved.	Identify 2 calibration procedures that can be conducted in-house to save costs.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Maintain SOP and audit standards in production lines.	R4		Ensures high compliance with standard operating procedures across lines.	Conduct periodic auditor calibration sessions to maintain consistent standards.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Oversee final inspection (OBQ) and line audits.	R4		OBQ results are highly reliable; issues are addressed quickly.	Develop an automated OBQ defect log on Helix/tablet.	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Analyze defect trends and lead corrective actions (CAPA).	R3	X	Identifies defects; however, root cause analysis can be more structured.	Attend structured problem-solving (8D) training; lead 2 critical CAPAs this year.	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Support customer audit preparation and compliance checks.	R4		Compliance files are well-maintained; audits pass consistently.	Coordinate standard prep checklists across all sections before audits.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Track quality metrics (scrap rate, defect rate, rework).	R4		Maintains precise databases; reports are timely and accurate.	Build a visual quality-metrics board at the main assembly area.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Provide on-the-job training for inspectors and operators.	R4		Provides excellent, clear training on defect-limit samples.	Standardize the visual limit-sample boards for new models.	Ongoing		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Manage and evaluate performance of quality inspectors.	R3	X	Evaluates well operationally; needs a more structured coaching approach.	Participate in company's supervisory mentoring program; build 1-1 coaching plans.	Q2–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Collaborate with Production on quality issue resolution.	R4		Collaborates well; needs more proactive intervention during initial runs.	Establish daily pre-shift quality syncs with Production Supervisors.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
04313	Pham Dinh Tung	Quality	Supervisor	Manage quality department costs and equipment calibration.	R3		Tracks calibration well; budget cost-savings can be improved.	Identify 2 calibration procedures that can be conducted in-house to save costs.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Maintain SOP and audit standards in production lines.	R4		Ensures high compliance with standard operating procedures across lines.	Conduct periodic auditor calibration sessions to maintain consistent standards.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Oversee final inspection (OBQ) and line audits.	R4		OBQ results are highly reliable; issues are addressed quickly.	Develop an automated OBQ defect log on Helix/tablet.	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Analyze defect trends and lead corrective actions (CAPA).	R3	X	Identifies defects; however, root cause analysis can be more structured.	Attend structured problem-solving (8D) training; lead 2 critical CAPAs this year.	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Support customer audit preparation and compliance checks.	R4		Compliance files are well-maintained; audits pass consistently.	Coordinate standard prep checklists across all sections before audits.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Track quality metrics (scrap rate, defect rate, rework).	R4		Maintains precise databases; reports are timely and accurate.	Build a visual quality-metrics board at the main assembly area.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Provide on-the-job training for inspectors and operators.	R4		Provides excellent, clear training on defect-limit samples.	Standardize the visual limit-sample boards for new models.	Ongoing		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Manage and evaluate performance of quality inspectors.	R3	X	Evaluates well operationally; needs a more structured coaching approach.	Participate in company's supervisory mentoring program; build 1-1 coaching plans.	Q2–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Collaborate with Production on quality issue resolution.	R4		Collaborates well; needs more proactive intervention during initial runs.	Establish daily pre-shift quality syncs with Production Supervisors.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
05705	Vo Chi Tinh	Quality	Supervisor	Manage quality department costs and equipment calibration.	R3		Tracks calibration well; budget cost-savings can be improved.	Identify 2 calibration procedures that can be conducted in-house to save costs.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Dominic Duong
`;
