export const rawWanekIDPTSV_part7 = `Emp Code	Person Name	Department	Critical Role	Job Duty	R Rating	Top Opp.	Comments	Way Forward	Timeline	Notes	Training Category	Competency Focus	Action	Proposed Program	Program Owner	Source Owner
43877	Annie Nguyen	Human Resources	Communication Supervisor	AI Workflow Optimization	R2		"Integrates AI tools to automate and speed up work flow and 
reduce manual errors."	Expand AI and digital tools to streamline and optimize daily team workflows.			Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Annie Nguyen
60190	Amber Dinh	Human Resources	HRBP Team Leader	Ramp Plan Development	R2	X	Limited experience in developing long-term ramp plans	Participate in annual manpower & ramp planning	Q2–Q4		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Ramp Plan Execution	R2		Execution is inconsistent and relies on guidance	Strengthen execution discipline and ownership	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Resource Management (Human)	R2		Basic manpower coordination, not yet optimized	Improve workforce planning & allocation skills	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Resource Development (Human)	R3	X	Supports team development but lacks structured approach	Build IDPs and talent pipeline	Q2–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Budget development & management	R2		Limited exposure to HR budgeting	Join budgeting process with manager	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Succession Planning	R3	X	Understands concept but lacks end-to-end ownership	Develop succession plans for key roles	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Recruitment Plan Development	R2		Able to contribute but not yet leading planning	Build annual hiring plan aligned with business needs	Q2–Q3		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Recruitment Execution	R3		Delivers hiring needs but lacks data-driven approach	Improve recruitment analytics and tracking	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	HR Market Analysis	R3		Has basic market awareness	Deepen analysis and provide actionable insights	Ongoing		Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Personal Development (Sharpen the Saw)	R4		Proactively invests in self-development	Continue structured learning journey	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Operational Knowlegde & understanding (Business Sense)	R2		Understands operations at a basic level	Strengthen business acumen and strategic thinking	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Decision making	R2		Decision-making still depends on guidance	Apply structured decision-making frameworks	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Building and Promoting a Company Culture	R3		Actively contributes to culture and engagement initiatives	Scale initiatives across teams	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Promoting a Teamwork environment	R3		Strong collaboration and teamwork facilitation	Lead cross-functional collaboration	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Maintaining and Developing a Culture around our Core and Growth Values	R3		Applies values in daily work	Strengthen role-modeling at team level	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Effective Communications	R3		Communicates clearly and effectively	Enhance influence and stakeholder management	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Coaching and Mentoring	R2	X	Limited structured coaching experience	Attend coaching training and apply GROW model	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Amber Dinh
60190	Amber Dinh	Human Resources	HRBP Team Leader	Employee Relations Improvement	R3		Handles ER cases at operational level	Build structured ER management approach	Ongoing		Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Ramp Plan Development	R4	X	Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Q1 2026		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Ramp Plan Execution & Shipment Delivery	R4	X	Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline	Q1 2026		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Resource Management (Human)	R3		Strong workforce planning and allocation	Coach others on resource planning			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Resource Development (Human)	R3		Actively supports people development	Expand development initiatives			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Budget development & management	R3		Confident in HR budgeting and cost control	Support cross-functional budgeting			Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Succession Planning	R3		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Personal Development (Sharpen the Saw)	R4	X	Development activities not fully structured	Create and follow IDP	Q2 2026		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Operational Knowlegde & understanding (Business Sense)	R3		Strong understanding of business operations	Mentor junior HR staff			Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Timely Decision Making	R4	X	Makes sound and timely decision	Maintain decision frameworks	Q3 20026		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Building and Promoting a Company Culture	R4	X	Actively drives culture initiatives	Scale culture programs	Q4 2026		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Promoting a Teamwork environment	R3		Encourages collaboration across teams	Lead cross-functional projects			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Maintaining and Developing a Culture around our Core and Growth Values	R3		Values embedded in daily HR practices	Reinforce through HR processes			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Q2 2026		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Coaching and Mentoring	R3		Willing but lacks structured coaching skills	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Employee Relations Improvement	R4	X	Handles ER cases effectively	Share ER best practices	Q3 2026		Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vu Van Xuan
09405	Vu Van Xuan	UPH Assembly WNK3	Production Manager	Quality Control & Issue Solving	R4	X	Monitoring processes, identifying root cause, and implementing effective corrective and preventive actions	Maintains consistent quality and resolves issues in a timely manner	Q1 2026		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vu Van Xuan
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Ramp Plan Development	R2		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Ramp Plan Execution & Shipment Delivery	R3	X	Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Resource Management (Human)	R3	X	Strong workforce planning and allocation	Coach others on resource planning			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Resource Development (Human)	R2		Actively supports people development	Expand development initiatives			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Budget development & management	R1		Confident in HR budgeting and cost control	Support cross-functional budgeting			Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Succession Planning	R2		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Personal Development (Sharpen the Saw)	R3		Development activities not fully structured	Create and follow IDP			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Operational Knowlegde & understanding (Business Sense)	R3		Strong understanding of business operations	Mentor junior HR staff			Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Timely Decision Making	R3	X	Makes sound and timely decision	Maintain decision frameworks			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Building and Promoting a Company Culture	R3		Actively drives culture initiatives	Scale culture programs			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Promoting a Teamwork environment	R3	X	Encourages collaboration across teams	Lead cross-functional projects			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Maintaining and Developing a Culture around our Core and Growth Values	R3		Values embedded in daily HR practices	Reinforce through HR processes			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Effective Communications	R2		Communicates clearly and effectively	Coach team on communication			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Coaching and Mentoring	R2		Willing but lacks structured coaching skills	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Employee Relations Improvement	R3		Handles ER cases effectively	Share ER best practices			Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Giap Quang Huy
71849	Giap Quang Huy	UPH Support WNK3	Production Manager	Quality Control & Issue Solving	R3		Monitoring processes, identifying root cause, and implementing effective corrective and preventive actions	Maintains consistent quality and resolves issues in a timely manner			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Giap Quang Huy
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Ramp Plan Execution & Shipment Delivery	R4		Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning			Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Resource Development (Human)	R3	X	Actively supports people development	Expand development initiatives			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting			Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Succession Planning	R3	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff			Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Timely Decision Making	R4		Makes sound and timely decision	Maintain decision frameworks			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Building and Promoting a Company Culture	R4		Actively drives culture initiatives	Scale culture programs			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Effective Communications	R4		Communicates clearly and effectively	Coach team on communication			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Employee Relations Improvement	R4		Handles ER cases effectively	Share ER best practices			Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Trinh Ngoc Phien
05458	Trinh Ngoc Phien	Cut&Sew WNK3	Production Assistant Manager	Quality Control & Issue Solving	R4		Monitoring processes, identifying root cause, and implementing effective corrective and preventive actions	Maintains consistent quality and resolves issues in a timely manner			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Trinh Ngoc Phien
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Ramp Plan Execution & Shipment Delivery	R4		Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Resource Development (Human)	R4		Actively supports people development	Expand development initiatives	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting	Q4		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Succession Planning	R4	X	Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Personal Development (Sharpen the Saw)	R3	X	Development activities not fully structured	Create and follow IDP	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Operational Knowlegde & understanding (Business Sense)	R3		Strong understanding of business operations	Mentor junior HR staff	Q4		Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Timely Decision Making	R4		Makes sound and timely decision	Maintain decision frameworks	Q4		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Building and Promoting a Company Culture	R3		Actively drives culture initiatives	Scale culture programs	Q3-Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Maintaining and Developing a Culture around our Core and Growth Values	R3		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Effective Communications	R4	X	Communicates clearly and effectively	Coach team on communication	Q2-Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Coaching and Mentoring	R4	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2-Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Employee Relations Improvement	R4		Handles ER cases effectively	Share ER best practices	Ongoing		Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dinh Thi Hong Van
26649	Dinh Thi Hong Van	Cut&Sew WNK3	Production Assistant Manager	Quality Control & Issue Solving	R4	X	Monitoring processes, identifying root cause, and implementing effective corrective and preventive actions	Maintains consistent quality and resolves issues in a timely manner	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dinh Thi Hong Van`;
