export const rawWanekIDPTSV = `Emp Code	Person Name	Department	Critical Role	Job Duty	R Rating	Top Opp.	Comments	Way Forward	Timeline	Notes	Training Category	Competency Focus	Action	Proposed Program	Program Owner	Source Owner
30516	Ashton Vo	Training	TTraining Supervisor - Project	Triển khai các mục tiêu KPI hằng tháng đến Giám sát khu vực nắm rõ và thực hiện	R3		Giao tiếp và truyền đạt hiệu quả với các bên.	Chuẩn hóa các biểu mẫu họp triển khai KPI.	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Học hỏi cách xây dựng quy trình automation cho 1 số công đoạn trong dây chuyền sản xuất sofa, từ đó xây dựng chương trình đào tạo phù hợp	R2	X	Đã tham gia 1 dự án bán tự động hóa chuyền blow mold B101	"Quản lý sắp xếp tham gia các dự án cùng team automation các khu vực sản xuất
Học hỏi các phần mềm lập trình tự động trên web, AI viết code"	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Học hỏi công cụ AI để lập kế hoạch cải thiện hiệu quả công việc, giảm thời gian làm báo cáo thủ công	R2	X	Cải tiến hiệu quả công việc	Học phần mềm Copilot, power BI và phối hợp các bộ phận liên quan triển khai	Q2–Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Tham gia các khóa học quy trình xây dựng và phát triển chương trình đào tạo, tài liệu đào tạo các dòng sản phẩm mới (sofa, bedding, Case goods,…)	R2	X	Cần thiết cho việc thiết lập quy trình mới	Tham gia cùng team automation, IT các dự án mới, đề xuất các sáng kiến xây dựng và cải tiến quy trình theo tự động hóa, giảm con người	Q3–Q4		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Triển khai thực hiện các dự án đào tạo đảm bảo hiệu quả KPI cho bộ phận	R4		Có thành tích tốt trong thực thi dự án.	Nhân rộng các khung đào tạo đã thành công.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Học thêm các ứng dụng mới để làm các tài liệu đào tạo dạng video ngắn hướng dẫn, cập nhật lên nền tảng trực quan	R1	X	Chuyển đổi tài liệu từ vndata lên Helix	Tham khảo phầm mềm Helix và các thao tác cập nhật mới	Q2–Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Lên kế hoạch và triển khai dự án ý tưởng cải tiến: hỗ trợ Trainer phát triển các ý tưởng cải tiến, thực hiện làm mẫu thí nghiệm, nâng cao tỷ lệ ý tưởng thành công, tiết kiệm chi phí	R3		Tập trung cao vào tiết kiệm chi phí & đổi mới.	Hướng dẫn Trainer sử dụng công cụ Lean/Six Sigma.	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Lên kế hoạch và thực hiện các dự án đào tạo các mảng sản xuất theo định hướng từ ban giám đốc: xây dựng chương trình, tài liệu, bố trí nguồn lực, đánh giá chuyển giao sản xuất,…	R2		Thực hiện tốt nhưng cần phân bổ nguồn lực hơn.	Tinh chỉnh chương trình & triển khai thí điểm.	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Triển khai và thực hiện chương trình gắn kết nhân viên: MT7/MT30/MT60/MT90	R4		Phối hợp tốt; cần chú trọng tỷ lệ giữ chân.	Tăng cường các hoạt động trải nghiệm cho NV mới.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Lên kế hoạch đào tạo và đứng lớp giảng dạy các môn học nội dung kỹ thuật cho nhóm quản lý mới (FLL, MLL)	R3		Kỹ năng giảng dạy tốt; cần thêm tình huống thực tế.	Lồng ghép các bài tập đóng vai & tình huống thực.	Ongoing		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Đào tạo re-train các môn kỹ thuật cho quản lý sản xuất FLL	R3		Đào tạo lại hiệu quả; cần đánh giá sau đào tạo.	Phát triển bộ công cụ đánh giá sau đào tạo.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ashton Vo
30516	Ashton Vo	Training	TTraining Supervisor - Project	Xây dựng mới các tài liệu và chỉnh sửa định kỳ các tài liệu đào tạo theo kế hoạch	R3		Quản lý tài liệu chất lượng cao.	Số hóa tài liệu để sử dụng trên máy tính bảng.	Ongoing		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Ashton Vo
10394	Quach Le Du	Training	Training Lead Supervisor	Xây dựng chương trình và đào tạo quy trình cho Supervisor, Team leader	R2	X	Chương trình đào tạo đã hoàn thiện và đang vận hành ổn định.	Định kỳ cập nhật các cải tiến mới vào tài liệu giảng dạy.	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Bố trí tối ưu nguồn lực Supervisor, Team Leader hợp lý theo từng thời điểm	R4		Điều phối nhân sự linh hoạt, bám sát kế hoạch sản xuất.	Xây dựng bảng theo dõi nguồn lực để tối ưu hóa việc phân bổ.	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Quản lý tổng quan và đảm bảo hiệu quả đào tạo của khu vực mình quản lý	R4		Duy trì tốt các chỉ số hiệu quả đào tạo tại khu vực.	Tăng cường giám sát hiện trường để đảm bảo chất lượng đồng nhất.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Xây dựng tài liệu mới và chỉnh sửa định kỳ các tài liệu đào tạo	R2	X	Tài liệu được lưu trữ và cập nhật đúng quy trình.	Số hóa tài liệu để hỗ trợ học tập trên thiết bị di động/Helix.	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Xây dựng kế hoạch headcount dựa trên ramp plan để chuẩn bị nguồn lực	R4		Kế hoạch headcount bám sát tiến độ mở rộng của nhà máy.	Phối hợp với TA Team để đảm bảo nguồn cung nhân lực kịp thời.	Annual cycle		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Bố trí nguồn nhân lực (Supervisor, Team Leader, Trainer) thực hiện kế hoạch	R4		Đội ngũ nòng cốt được bố trí đúng người, đúng việc.	Tổ chức các buổi họp nhanh để xử lý vướng mắc nguồn lực.	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Phân bổ và bố trí nguồn nhân lực Trainer tối ưu nhất theo nhu cầu	R4		Tối ưu hóa thời gian làm việc của đội ngũ Trainer.	Đào tạo chéo (Cross-train) để Trainer có thể hỗ trợ nhiều line.	Q2–Q3		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Theo sát kế hoạch, kiểm tra điều chỉnh và chủ động hỗ trợ	R4		Chủ động xử lý các tình huống phát sinh ngoài kế hoạch.	Duy trì cơ chế báo cáo nhanh để cấp trên kịp thời hỗ trợ.	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Đánh giá năng lực, định hướng phát triển kỹ năng cho nhân viên	R4		Việc đánh giá được thực hiện công tâm và đúng hạn.	Thiết lập lộ trình đào tạo chuyên sâu cho các nhân sự loại A.	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Xây dựng chương trình phát triển năng lực, kỹ năng cho nhân viên	R4		Các khóa học kỹ năng mềm và quản trị được triển khai tốt.	Đa dạng hóa hình thức đào tạo (thực hành, video bài giảng).	Q1–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Hỗ trợ kịp thời, động viên, xây dựng môi trường gắn kết	R4		Xây dựng được môi trường làm việc tích cực, gắn bó.	Duy trì các kênh lắng nghe ý kiến đóng góp của nhân viên.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Tổ chức các hoạt động gắn kết và xây sự Team Word đội nhóm (Team Building)	R4		Các ngày lễ và sự kiện được tổ chức bài bản, ý nghĩa.	Lồng ghép các thông điệp văn hóa công ty vào hoạt động đội nhóm.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Xây dựng văn hóa học tập tự thân (Vinh danh Trainer, chia sẻ kinh nghiệm)	R3	X	Văn hóa chia sẻ kiến thức đang dần hình thành mạnh mẽ.	"Duy trì chương trình ""Sáng kiến đào tạo"" để khuyến khích sáng tạo."	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Xây dựng chương trình và triển khai các dự án của bộ phận	R1	X	Dự án đang trong giai đoạn chuẩn bị, cần đẩy nhanh tiến độ.	Lập kế hoạch chi tiết và phân công trách nhiệm (RACI) cho dự án.			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Quach Le Du
10394	Quach Le Du	Training	Training Lead Supervisor	Chủ động đề xuất, xây dựng và triển khai dự án cùng các phòng ban	R1	X	Khả năng phối hợp liên phòng ban cần được phát huy hơn.	Thiết lập các cuộc họp định kỳ với Sản xuất để tìm giải pháp chung.			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Quach Le Du
4272	Phan Thi Ha	Training	Training Supervisor C&S	Đào tạo và phát triển về năng lực, kỹ năng….	R3	X	Vừa làm vừa học, trao đổi lẫn nhau				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Xây dựng chương trình, các tài liệu mới và chỉnh sửa định kỳ tài liệu đào tạo	R3	X	Tài liệu cơ bản đầy đủ nhưng cần cập nhật các mẫu mã mới.	Ưu tiên hoàn thiện thư viện video hướng dẫn thao tác chuẩn.	Quý 3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Cải tiến và các dự án	R3	X	"- Quản lý dự án bộ phận: Thiết lập và triển khai dự án nội bộ
- Chủ động đề xuất phối hợp và triển khai dự án cùng các phòng ban"	Sử dụng mô hình RAIL để kiểm soát tiến độ từng hạng mục dự án.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Bố trí nhân lực	R3		"- Sắp xếp công việc và đảm bảo nguồn nhân lực đào tạo.
- Cập nhật báo cáo vắng và HC khu vực quản lý và bố trí và phân bổ tối ưu nguồn lực Team Leader, Trainer…"	"Tự động hóa báo cáo để cập nhật dữ liệu thời gian thực.
Xây dựng ma trận kỹ năng đa nhiệm cho đội ngũ nòng cốt."	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Lập kế hoạch đào tạo công nhân mới	R4		- Lập kế hoạch chuẩn bị nhận công nhân mới: máy móc, công cụ…đảm bảo sự đầy đủ dụng cụ và nguyên vật liệu đào tạo.	Chuẩn hóa danh mục kiểm tra (checklist) chuẩn bị cho từng line.	Ongoing		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Lập và thực hiện kế hoạch sản xuất (P&IC, mục tiêu đào tạo...)	R4		- Đạt kế hoạch hàng hóa phù hợp; chủ động hỗ trợ kịp thời.	Tăng cường phối hợp với P&IC để tối ưu năng suất line đào tạo.	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Quản lý tổng quan hiệu quả đào tạo (Năng suất, chất lượng, OBQ...)	R4		- Bám sát mục tiêu các công đoạn, đảm bảo tỷ lệ rác thấp.	Phân tích dữ liệu OBQ định kỳ để tìm nguyên nhân gốc rễ.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Triển khai và thực hiện các Form bảng biểu (MT, Canban, hồ sơ...)	R4		- Thực hiện đầy đủ các hồ sơ Trainer và bảng biểu tại xưởng.	Số hóa các form biểu mẫu trên tablet thông qua hệ thống Helix.	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Gặp gỡ One on One nhân viên	R4		- Lắng nghe, động viên và giải quyết khó khăn kịp thời.	Duy trì lịch họp 1-1 định kỳ hàng tháng để tăng tính gắn kết.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Báo cáo công việc & Đánh giá định kỳ công việc hằng tuần và hằng tháng	R2	X	"- Tổng hợp dữ liệu chính xác, phản ánh đúng thực tế.
- Chuẩn hóa quy trình thu thập và đối soát dữ liệu thô.
- Cập nhật báo cáo công việc hằng tuần (OBQ, vắng, NS-CL)
- Dựa trên mục tiêu đặt ra, cập nhật kết quả và kế hoạch tiếp theo.
- Đảm bảo tính công bằng và minh bạch trong tiêu chí đánh giá."	Thiết lập bảng điều khiển (Dashboard) để theo dõi nhanh.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Nhận thông tin Mail và Team để xử lý vấn đề kịp thời	R4		- Tiếp nhận và phản hồi thông tin nhanh chóng, hiệu quả.	Chuẩn hóa quy trình xử lý thông tin khẩn cấp liên phòng ban.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Đánh giá năng lực, định hướng phát triển cho nhân viên và xây dựng chương trình đào tạo quy trình, phát triển năng lực	R4		- Nhận diện đúng các nhân tố tiềm năng để đào tạo kế thừa.	Lập lộ trình phát triển năng lực (IDP) cho Team Leader/Trainer.	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Phan Thi Ha
4272	Phan Thi Ha	Training	Training Supervisor C&S	Học hỏi thêm công cụ AI, áp dụng AI nâng cao hiệu quả	R2	X	"- Cải tiến hiệu quả công việc
- Áp dụng AI vào sản xuất"	Tham gia các lớp đào tạo về AI, tìm hiểu các công cụ AI cách sử dụng và áp dụng vào cáo cáo, làm kế hoạch	Quý 3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Phan Thi Ha
72166	Tran Cong Minh	Training	Training Supervisor UPH	Bố trí nhân lực	R4		Công nhân nắm bắt các thao tác chuẩn, hiểu rõ và làm đúng tiêu chuẩn SOP	Duy trì kiểm tra tay nghề (Audit) định kỳ sau đào tạo.	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Giám sát hiệu quả công việc	R3		Từng nhóm luôn đạt mục tiêu các KPI bộ phận: (AB, TO, SOP, OBQ, Eff, Idea, EHS, 6S)	Phân tích sâu các chỉ số biến động để có giải pháp kịp thời.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Xây dựng, hỗ trợ đội nhóm gắn kết, phát triển	R3		"Môi trường làm việc gắn kết
Thấu hiểu, tích cực và hiệu quả.
Hỗ trợ khó khăn kịp thời."	Tổ chức các buổi họp nhanh (Briefing) để lắng nghe phản hồi.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Xây dựng, chỉnh sửa tài liệu cơ bản	R2	X	Đảm bảo đầy đủ sự chuẩn bị cho cho công tác đào tạo	Số hóa tài liệu và cập nhật lên hệ thống thư viện video.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Lập kế hoạch giám sát chất lượng	R3			Chuẩn hóa danh mục checklist thiết bị theo từng line sản xuất.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Đánh giá năng lực cấp dưới	R3			Thiết lập lộ trình thăng tiến cá nhân cho các nhân tố tiềm năng.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Lập kế hoạch hàng hóa hàng tuần	R4		Đảm bảo đủ hàng hóa và  đúng tay nghề công nhân theo tuần tuổi	Theo dõi sát năng suất thực tế so với kế hoạch trên hệ thống.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Lập kế hoạch kiểm soát chất lượng SOP và OBQ khu vực đóng ghế và Blow fill	R3		Nâng cao chất lượng và xây dựng ý thức chất lượng cho học viên và Trainer	Tăng cường đào tạo thực hành về lỗi ngoại quan (Visual defect).	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Gặp gỡ cá nhân Trainer, Team và học viên	R3		Kết nối, chia sẻ và lắng nghe	Xây dựng văn hóa phản hồi hai chiều (Top-down & Bottom-up).	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Báo cáo tuần theo MSS về con người, chất lượng, hiệu quả, Idear, dự án,….	R3		Cập nhật tiến độ đào tạo	Tự động hóa bảng biểu báo cáo để giảm thiểu thao tác thủ công.	Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Báo cáo đánh giá Bonus tháng	R4			Đảm bảo tính công bằng và minh bạch trong tiêu chí đánh giá.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Tổng hợp báo cáo OBQ, Vắng, TLNV, NS -CL theo tuần, tháng	R3	X		Chuẩn hóa quy trình thu thập và đối soát dữ liệu thô.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Thủ tục hành chính	R3			Đơn giản hóa các biểu mẫu hành chính trên nền tảng số.	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Bố trí OT theo như cầu sản xuất và đăng ký OT	R4		Cùng sản xuất thực hiện kế hoạch nhà máy	Theo dõi sát giờ làm thêm để đảm bảo sức khỏe cho đội ngũ.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Nhận thông tin Mail và chat Team để xử lý các vấn đề liên quan kịp thời	R4		Nhận thông tin và phản hồi	Thiết lập khung thời gian vàng để phản hồi các yêu cầu khẩn.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Đánh giá YTCT của đội nhóm	R3	X		Xây dựng bộ tiêu chí chấm điểm YTCT rõ ràng, dễ đo lường.	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Xử lý vấn đề với các bộ phận liên quan trong nhà máy	R3		Đảm bảo công việc đào tạo đúng và cập nhật các thông tin thay đổi kịp thời	Thiết lập nhóm phản ứng nhanh (Task force) với bộ phận IE/Sản xuất.	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Đào tạo cơ bản cho cấp dưới về kỹ năng, giao tiếp,….	R3		Vừa làm vừa học, trao đổi lẫn nhau	Thực hiện các buổi huấn luyện tại chỗ (On-the-job coaching).	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Sử dụng công cụ AI hiệu quả	R2	X	Thuật ngữ dò tìm, khai thác nội dung hiệu quả		Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Cách sử dụng các phần mềm để chỉnh sửa video, cắt ghép,….	R1	X	Phục vụ cho việc chỉnh sửa tài liệu, SOP		Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Tran Cong Minh	Training	Training Supervisor UPH	Các tính năng của Email, Excel (dò tìm, format,…)	R2	X			Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tran Cong Minh
72166	Vo Vu Luan	Training	Training Supervisor UPH	"Kế hoạch xây dựng và cập nhật các tài liệu mới
Chỉnh sửa định kỳ các tài liệu đào tạo"	R3		"- Chủ động kiểm tra và đánh giá tính thực tế của chương trình đào tạo
 - Hướng tới Trainer là người đưa ra các lưu trình thực tế tại xưởng và tổng hợp lại trước khi áp dụng"	- Triển khai quý 3, KPI Bonus trainer đưa ra 1 ý tưởng cải tiến/ tinh gọn quy trình nơi mình đang làm việc	On going		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	Triển khai chương trình và đào tạo nâng cao kỹ năng cho nhân viên	R3		"- Đảm bảo nhân viên hiểu rõ về lưu trình và chương trình đào tạo của mình
 - Tuân thủ các tiêu chuẩn và lưu trình đào tạo
 - Cá nhân đưa ra các đề xuất về lưu trình đào tạo đúng với thực tế"	Triển khai rõ - Kiểm tra và đánh giá - Cập nhật và điều chỉnh - Theo dõi hiệu quả	On going		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	Bố trí tối ưu nguồn lực hợp lý theo từng thời điểm, nhu cầu từng nhà máy	R4		"- Chủ động phối hợp và điều phối trainer các nhà máy nhằm tối ưu nguồn lực
 - Đảm bảo nhân viên hiểu rõ vai trò và trách nhiệm công việc"	- Đánh giá năng lực nguồn lực thực tế UPH và Components	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	Phối hợp P&IC và TA team đặt kế hoạch phù hợp theo mục tiêu đào tạo và tăng trưởng nhà máy	R4		"- Đánh giá được năng lực nhóm và đặt kế hoach phù hợp, đảm bảo hiệu quả.
 - Có kế hoạch cụ thể về ramp plan và triển khai nhân viên hiểu rõ"	- Đánh giá nguồn lực đặt kế hoạch phù hợp hàng tuần	On going		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	Đảm bảo hiệu quả đào tạo của khu vực mình quản lý.	R4		"- Đảm bảo nhân viên hiểu rõ mục tiêu và công việc mình cần phải làm
 - Nâng cao tinh thần trách nhiệm của mỗi cá nhân trong mọi hoạt động đào tạo"	Triển khai rõ - Kiểm tra và đánh giá - Cập nhật và điều chỉnh - Theo dõi hiệu quả	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	Đánh giá năng lực, định hướng phát triển kỹ năng cho nhân viên	R3	X	"- Đánh giá skill matrix hàng quý, đảm bảo hiểu rõ năng lực thực tế nhóm mình quản lý
 - Chủ động bố trí nhân lực học hỏi, đa kỹ năng chuẩn bị cho các dự án cũng như trainer tiềm năng cho sự phát triển"	"- Đánh giá Skill matrix hàng quý
 - Lên chương trình đào tạo định kỳ về kỹ năng quản lý"	On going		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	Xây dựng chương trình và đào tạo, phát triển năng lực, kỹ năng cho nhân viên	R3	X	"- Nâng cao sự phối hợp và ghi nhận đối với nhân viên.
 - Lắng nghe và hỗ trợ kịp thời
 - Hiểu nhân viên"	- Gặp gỡ cá nhân hàng tuần theo lịch cố định	On going		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	Chủ động đề xuất các dự án hàng tháng, quý: Tinh gọn quy trình, giảm chi phí.	R3	X	- Xây dựng kế hoạch và đề xuất các hoạt động hướng đến tinh gọn quy trình đào tạo cho nhóm thực hiện trực tiếp tham gia và thực hiện.	- Mục tiêu đưa ra các dự án hàng quý/ năm	On going		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	"Phối hợp các team liên quan dự án Blow Mold
 + Blow mold
 + Assembly Blow Mold"	R3	X	"-  Xây dựng các chương trình đào tạo, tiêu chuẩn đào tạo phù hợp và chính xác với thực tế đảm bảo hiệu quả Blow Mold
 - Phối hợp các phòng ban xây dựng tiêu chuẩn và tối ưu các quy trình, layout chuyền Assembly Blow mold"	"- Theo các dự án và đào tạo Blow mold Machine
 - Đào tạo line tại WN2 và chuyển sang WN5 tháng 4"	Quý 2		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	"Mở rộng quản lý Cut & Sew
 + Lưu trình
 + Kỹ Thuật"	R2	X	"- Quản lý tổng quan hiệu quả đào tạo
 - Thực hành kỹ thuật các khâu đạt trainer level 2
 - Hiểu rõ và góp ý xây dụng các lưu trình đào tạo phù hợp, hiệu quả"	- Mỗi ngày học 1h theo kế hoạch cố định.	Quý 2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Vo Vu Luan
72166	Vo Vu Luan	Training	Training Supervisor UPH	"Năng lực quản lý 
 + Xây dựng và lan tỏa văn hóa tôn trọng tới các nhóm
 + Nâng cao kỹ năng quản lý đảm nhânh rộng hơn"	R3	X	"- Thay đổi góc nhìn, tư duy
 - Đánh giá vấn đề trên nhiều khía cạnh, 
 - Hiểu rõ vai trò và trách nhiệm
 - Chủ động tốt trong các giao tiếp và nhiệm vụ"	"- Triển khai hàng ngày về văn hóa ""Tôn Trọng"""	Quý 3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Vo Vu Luan
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Develop organizational structure, and execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo theo kế hoạch"	R3	X	"Demonstrates strong experience in organizing, training, and effectively managing teams; further development is needed in long-term workforce planning
Có kinh nghiệm tổ chức và đào tạo, quản lý team hiệu quả; cần nâng cao trong việc xây dựng kế hoạch nhân sự dài hạn."	"Build a strong succession pipeline
Xây dựng đội ngũ kế thừa"	Q3-2026		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Organize and allocate workforce effectively to meet operational needs
Tổ chức và sắp xếp nhân lực làm việc phù hợp đáp ứng nhu cầu công việc"	R3		"Possesses good coordination skills; however, needs to consistently optimize team productivity, with a stronger focus on efficiency improvement and optimal resource utilization
Có khả năng điều phối tốt, tuy nhiên cần duy trì việc tối ưu năng suất nhóm một cách liên tục, tập trung nâng cao hiệu quả và sử dụng nguồn lực tối ưu."	"Drive continuous improvement initiatives
Cải tiến liên tục"	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Manage inventory (inbound, outbound, and stock control); ensure accurate and timely receiving, storage, and preservation of goods
Tổ chức quản lý hàng hóa xuất nhập tồn, thực hiện các thủ tục nhập-xuất, sắp xếp, lưu kho và bảo quản hàng hóa được chính xác và kịp thời"	R4		"Performing well with accurate and timely control
Đang thực hiện tốt, kiểm soát chính xác và kịp thời."	"Standardize processes, provide team training, and implement continuous improvements
Chuẩn hóa quy trình, đào tạo team và triển khai cải tiến liên tục."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Oversee logistics operations, including transportation and delivery between warehouses and according to customer orders
Tổ chức giao nhận, vận chuyển, giao hàng giữa các kho và theo đơn đặt hàng của Khách Hàng"	R4		"Operations are stable and effectively meet delivery demands
Vận hành ổn định, đáp ứng tốt nhu cầu giao hàng."	"Optimize container loading and transportation efficiency
Tối ưu cont vận chuyển"	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Monitor, coordinate, and supervise work progress; promptly handle arising issues
Theo dõi, điều phối và giám sát tiến độ công việc, kịp thời xử lý các vấn đề phát sinh"	R4		"Proactively monitors and promptly resolves operational issues as they arise
Chủ động theo dõi và xử lý kịp thời các vấn đề phát sinh trong vận hành"	"Standardize incident handling procedures and enhance risk mitigation capability
Chuẩn hóa quy trình xử lý sự cố và nâng cao khả năng dự phòng rủi ro."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Guide and remind employees on Occupational Safety and Fire Prevention (EHS/PCCC) daily; ensure compliance with regulations
Hướng dẫn, nhắc nhở CNV về ATLĐ, ATPCCN hằng ngày và giám sát việc tuân thủ thực hiện"	R3		"Provides good guidance to employees; however, needs to increase the frequency of compliance monitoring
Đã thực hiện hướng dẫn tốt nhưng cần tăng tần suất theo dõi tuân thủ"	"Strengthen execution monitoring and compliance control
Tăng cường giám sát thực hiện"	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Organize and participate in employee engagement activities
Tổ chức và tham gia các hoạt động gắn kết NLĐ"	R4	X	"Actively participates in organizing employee engagement activities
Năng nổ tham gia vào tổ chức các hoạt động gắn kết"	"Continue enhancing current strengths
Tiếp tục phát huy"	On going		Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
17676	Nguyen Thi Mong Van	DC - C&S Raw Material	Material Delivery Lead Supervisor	"Research and implement initiatives to improve and optimize work processes
Nghiên cứu, thử nghiệm để cải tiến quy trình làm việc được hiệu quả và tối ưu"	R3	X	"Has a solid foundation and meets job requirements; however, should continue developing to enhance effectiveness, with greater focus on proposing and implementing improvements
Có nền tảng tốt và đang đáp ứng yêu cầu công việc, tuy nhiên cần tiếp tục phát triển để nâng cao hiệu quả và tập trung vào đề xuất và triển khai cải tiến."	"Proactively research, pilot, and implement improvement initiatives to enhance efficiency and optimize workflows
Chủ động nghiên cứu, thử nghiệm và triển khai các giải pháp cải tiến nhằm nâng cao hiệu quả và tối ưu hóa quy trình làm việc."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Thi Mong Van
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Develop organizational structure, and execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo theo kế hoạch"	R3	X	"Demonstrates good capability in organizing, training, and managing the team
Tổ chức và đào tạo quản lý team khá tốt"	"Build a strong succession pipeline
Cần xây dựng đội ngũ kế thừa"	Q3-2026		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Organize and allocate workforce effectively to meet operational needs
Tổ chức và sắp xếp nhân lực làm việc phù hợp đáp ứng nhu cầu công việc"	R3		"Shows strong coordination skills; effectively organizes and allocates manpower to meet operational demands
Có khả năng điều phối tốt, tổ chức và sắp xếp nhân lực đáp ứng nhu cầu công việc"	"Improve team productivity and overall efficiency
Cần tối ưu năng suất và hiệu quả nhóm"	On going		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Manage inventory (inbound, outbound, and stock control); ensure accurate and timely receiving, storage, and preservation of goods
Tổ chức quản lý hàng hóa xuất nhập tồn, thực hiện các thủ tục nhập-xuất, sắp xếp, lưu kho và bảo quản hàng hóa được chính xác và kịp thời"	R3		"Performing well with accurate and timely control
Đang thực hiện tốt, kiểm soát chính xác và kịp thời"	"Standardize processes and conduct regular team training
Chuẩn hóa quy trình, đào tạo nhóm định kỳ"	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Oversee logistics operations, including transportation and delivery between warehouses and according to customer orders
Tổ chức giao nhận, vận chuyển, giao hàng giữa các kho và theo đơn đặt hàng của Khách Hàng"	R4		"Operations are stable and effectively meet delivery requirements
Vận hành ổn định, đáp ứng tốt nhu cầu giao hàng."	"Research and drive initiatives to improve container utilization rates
Cần nghiên cứu và thúc đẩy tăng tỉ lệ tận dụng cont"	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Monitor, coordinate, and supervise work progress; promptly handle arising issues
Theo dõi, điều phối và giám sát tiến độ công việc, kịp thời xử lý các vấn đề phát sinh"	R4		"Proactively monitors and promptly addresses operational issues
Chủ động theo dõi và xử lý kịp thời các vấn đề phát sinh trong vận hành"	"Standardize incident handling processes and enhance risk prevention capability
Chuẩn hóa quy trình xử lý sự cố và nâng cao khả năng dự phòng rủi ro"	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Guide and remind employees on Occupational Safety and Fire Prevention (EHS/PCCC) daily; ensure compliance with regulations
Hướng dẫn, nhắc nhở CNV về ATLĐ, ATPCCN hằng ngày và giám sát việc tuân thủ thực hiện"	R3	X	"Has provided guidance; however, needs to increase the frequency of compliance monitoring
Đã thực hiện hướng dẫn nhưng cần tăng tần suất theo dõi tuân thủ"	"Standardize training materials and checklists; strengthen execution monitoring
Chuẩn hóa tài liệu đào tạo, checklist và tăng cường giám sát thực hiện."	On going		Functional	Training Capability	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Organize and participate in employee engagement activities
Tổ chức và tham gia các hoạt động gắn kết NLĐ"	R3	X	"Has participated in basic engagement activities
Đã tham gia các hoạt động cơ bản"	"Actively participate in company activities and foster employee engagement
Cần tích cực tham gia các hoạt động chung và tạo sự gắn kết"	On going		Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
24805	Truong Minh Hung	Components	Material Delivery Lead Supervisor	"Research and implement initiatives to improve and optimize work processes
Nghiên cứu, thử nghiệm để cải tiến quy trình làm việc được hiệu quả và tối ưu"	R4		"Actively contributes to improvement initiatives and encourages team members to participate
Tích cực trong các hoạt động cải tiến và khuyến khích nhân viên tham gia"	"Continue leveraging and building on current strengths
Tiếp tục phát huy"			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Truong Minh Hung
	Harvey Nguyen	TAT Quality	TAT Manager	Strategic Quality Planning & Vision Translation	R2	X	Understands quality strategy at operational level; needs development in translating Director-level vision into dept action plans	Attend strategic planning sessions with TAT Director; co-develop annual quality roadmap	Q2–Q3		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Audit Governance Framework Development	R3		Familiar with existing frameworks; limited experience designing governance structures from scratch	Lead one governance review project with mentoring from TAT Director	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	KPI & Performance Dashboard Design	R3		Able to use dashboards;  cascading KPIs	Build dept KPI dashboard aligned to Director's scorecard; review monthly	Q2–Q4		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Culture of Quality & Accountability Leadership	R4		Strong quality mindset; actively promotes standards and accountability within team	Continue best practices; coach direct reports on culture-building	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	SOP Audit & OBQ Inspection Oversight	R4		Expert-level knowledge of SOP/OBQ systems; oversees with high independence	Maintain discipline; share expertise with new AM cohort	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	CAR / PAR Approval for Critical Defects	R3		Approves routine CARs; developing confidence in systemic/customer-critical escalations	Shadow TAT Director on 3–5 critical CAR reviews; build decision framework	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Versatility Matrix & Headcount Deployment	R4		Effectively manages shift coverage and versatility planning across sections	Expand scope to include cross-division deployment planning	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Audit Documentation & Traceability Standards	R4	X	Maintains high discipline in version control and audit traceability	Mentor Lead Supervisors on documentation standards	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Product Quality Project Governance	R3		Solid execution; needs to demonstrate clear understanding of full end-to-end project governance model.	Lead 1-3  full Product Quality Project cycle as project owner	Q3–Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Senior Customer Quality Meeting Leadership	R2		Participates in customer meetings; needs development in leading executive-level discussions independently	Co-lead weekly US customer meetings with TAT Director; take solo lead	Q2–Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Customer Escalation Response & Communication	R2	X	Responds to standard escalations well		Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Formal Quality Report & Dashboard Presentation	R3		Builds reports competently; presentation narrative at executive level in development	Present monthly quality report to Dir once per quarter; receive structured feedback	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Cross-Functional Collaboration (IE / CI / WH / Logistics)	R4		Strong relationship with cross-functional teams; drives joint quality controls effectively	Expand influence to Logistics and FI/QC; lead monthly cross-functional quality sync	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Predictive Risk Control & Defect Analytics	R3	X	Uses historical data well; FMEA and process capability analytics need further development	Complete advanced FMEA training; apply on 2 pilot run reviews this year	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Talent Pipeline Building & Succession Planning	R3		Strong individual coaching skills; competency framework and succession planning need structure	Co-develop TAT succession map with HR Head; identify 2 AM-ready candidates by Q3	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Training Roadmap & Competency Framework Design	R3		Delivers effective on-the-job training; formal competency framework design is new territory	Develop TAT Competency Framework for Auditor-to-AM pipeline; pilot Q3	Q3–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Headcount Planning & Workforce Strategy	R4		Demonstrates strong workforce planning aligned to production volume and complexity	Lead annual HC planning for next cycle; present to TAT Director for approval	Annual cycle		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Performance Evaluation & PDMS Oversight	R4		Conducts thorough performance reviews; strong in PDMS administration	Standardize PDMS process across all AM reports; train new AMs	Q2 & Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Recruitment & Retention Strategy	R3		Good at identifying talent; structured retention strategy needs development	Build TAT retention plan with HR; implement 1 key retention initiative by Q3	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Lean / Kaizen / 6S Program Leadership	R4		Leads 6S programs effectively; Kaizen facilitation skills are strong	Lead enterprise Kaizen event this year; document and share outcomes	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Audit System Digitalization & Modernization	R2	X	Aware of digital audit tools; needs to focus more on leading full-scale system digitalization	Lead pilot digitalization of 1 audit system (SOP or OBQ); present roadmap	Q3–Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Quality Cost Reduction Initiatives	R3		Contributes to cost reduction; needs more ownership over program	Own 1-3  quality cost reduction initiative end-to-end; report  results quarterly	Q2–Q4		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Improvement KPI Measurement & Reporting	R3		Tracks KPIs at team level; needs to develop enterprise-level improvement reporting	Build monthly improvement KPI report; present to Director and cross-functional heads	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Annual Budget Development & Management	R3		Understands budget structure;	Co-own next annual budget submission with TAT Director; attend all finance reviews	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Executive Quality Status Reporting	R3		Produces solid team-level reports; executive-level reporting narrative can be further developed	Draft monthly Director report; receive structured feedback on executive communication style	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Trend Analysis & Performance Dashboard for Stakeholders	R3		Strong data skills; stakeholder-facing dashboard design needs practice	Design and own TAT performance dashboard presented to senior leadership monthly	Q2–Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Harvey Nguyen
	Harvey Nguyen	TAT Quality	TAT Manager	Critical Quality Event Escalation & Impact Assessment	R4		Responds swiftly to critical events; escalation communication with business impact framing is solid	Continue current standard; coach AM team on escalation protocols	Ongoing		Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Harvey Nguyen
14472	Nguyen Dang Viet	Components	Production Assistant Manager - Comp.	"Identify inputs for production activities
Xác định đầu vào cho hoạt động sản xuất"	R4		"Demonstrate strong capability in identifying key inputs for production operations
Khả năng xác định đầu vào cho hoạt động sản xuất"	"Regularly review and optimize input assumptions to minimize the risk of shortages or excess inventory
'Thường xuyên rà soát, tối ưu các giả định đầu vào nhằm giảm rủi ro thiếu hụt hoặc tồn kho dư thừa"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Dang Viet
14472	Nguyen Dang Viet	Components	Production Assistant Manager - Comp.	"Develop efficient production processes; allocate manpower, machinery, and materials appropriately to ensure completion of plans
Xây dựng quy trình sản xuất hợp lý, bố trí nhân lực, máy móc và nguyên vật liệu phù hợp để đảm bảo hoàn thành kế hoạch."	R4		"Effectively evaluate and align processes, machinery, and manpower across different production stages
'Đánh giá, sắp xếp tốt các qui trìn, máy móc và nhân lực phù hợp với từng giai đoạn của sản xuất"	"Optimize resource allocation to ensure efficiency and productivity
Tối ưu hóa việc phân bổ nguồn lực nhằm đảm bảo hiệu suất, năng suất"	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Dang Viet
14472	Nguyen Dang Viet	Components	Production Assistant Manager - Comp.	"Ensure production, storage, transportation, and delivery processes are carried out effectively to meet business demands
Đảm bảo quá trình sản xuất, bảo quản, vận chuyển và giao nhận hàng hóa được thực hiện một cách hiệu quả để đáp ứng nhu cầu kinh doanh."	R4		"Proactively identify risks and implement timely solutions to ensure on-time delivery and operational efficiency
Chủ động nhận diện rủi ro và đưa ra giải pháp kịp thời nhằm đảm bảo tiến độ giao hàng và hiệu quả vận hành."	"Develop contingency plans to mitigate impacts on production and delivery operations
Xây dựng phương án dự phòng để giảm thiểu tác động đến sản xuất và giao nhận"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Dang Viet
14472	Nguyen Dang Viet	Components	Production Assistant Manager - Comp.	"Monitor, coordinate, and supervise production progress; promptly handle arising issues.
Theo dõi, điều phối và giám sát tiến độ sản xuất, kịp thời xử lý các vấn đề phát sinh."	R4		"Ensure seamless cross-functional coordination to maintain continuous and efficient production while addressing issues promptly
Đảm bảo sự phối hợp thông suốt giữa các bộ phận để duy trì  sản xuất liên tục và hiệu quả và xử lý kịp thời các vấn đề phát sinh"	Drive effective cross-functional communication to promptly resolve issues and minimize production disruptionsThúc đẩy giao tiếp hiệu quả giữa các phòng ban để xử lý nhanh chóng các vấn đề phát sinh và hạn chế gián đoạn sản xuất	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Nguyen Dang Viet
14472	Nguyen Dang Viet	Components	Production Assistant Manager - Comp.	"Supervise and control all aspects of production activities to maximize the use of resources, machinery, and labor while minimizing waste.
Giám sát và kiểm soát mọi phương diện của hoạt động sản xuất để tận dụng tối đa các nguồn lực, máy móc và lao động, đồng thời giảm thiểu lãng phí."	R3	X	"Drive operational efficiency through process optimization, effective resource allocation, and cost control
Thúc đẩy vận hành hiệu quả thông qua tối ưu quy trình, phân bổ nguồn lực hợp lý và đảm bảo hiệu quả chi phí sản xuất."	"Continuously improve processes and optimize resource utilization to enhance productivity and reduce operational costs
Liên tục cải tiến quy trình và tối ưu sử dụng nguồn lực nhằm nâng cao năng suất và giảm chi phí vận hành."	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nguyen Dang Viet`;
