export const rawWanekIDPTSV_part7 = `16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Build and maintain harmonious and stable employee relations	R4		Maintain a positive work environment, minimize conflicts, and keep employee complaints/disputes at a low level	Proactively collaborate with all departments to build more sustainable employee relations	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Ensure compliance with labor laws and minimize legal risks for the company	R4		Ensure no major violations occur; effectively control risks related to audits and inspections	Proactively assess employee relations risks and ensure timely and effective mitigation	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Lead the handling of complex and sensitive employee relations cases	R4		Resolve issues effectively and in compliance with regulations, minimizing impact on operations and company reputation	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Collaborate in developing, reviewing, and optimizing company labor policies and internal regulations	R3	X	Ensure policies are clear, timely updated, practical, and effectively implemented	Ensure continuous review and timely updates	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Coordinate with the trade union and relevant stakeholders to organize employee engagement activities and events	R4		Organize effective engagement activities, enhance employee engagement, and receive positive feedback from employees	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Manage and control disciplinary actions to ensure fairness and consistency	R4		Ensure fairness, consistency, and transparency in disciplinary actions	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Implement communication initiatives to enhance awareness of employee relations across the organization	R4		Ensure employees understand and comply with policies and regulations; reduce violations caused by lack of awareness	Proactively plan and communicate to employees in a timely manner	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Drive initiatives to improve employee engagement and workplace environment	R3	X	Improve employee satisfaction, reduce turnover, and enhance employee engagement	Proactively develop employee engagement initiatives aligned with the company’s culture and strategic direction	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Analyze data and prepare reports on absenteeism (AB) and turnover (TO)	R3	X	Deliver accurate and timely reports; provide insights and recommend improvement actions	Take a proactive approach to data analysis and ensure all reports are accurate, timely, and compliant with relevant regulations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Build, maintain, and expand relationships with partners and service providers	R4		Maintains excellent, professional relationships with external vendors	Establish formal vendor performance evaluations (scorecards) to sustain quality	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16972	Mai Thi Hoang Bich Tram	Human Resources	Supervisor	Prepare compliance documentation for annual external and internal audits	R4		Achieves high preparation standards; passes all audits successfully	Establish a continuous compliance calendar to sustain readiness	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Build and maintain harmonious and stable employee relations	R4		Maintain a positive work environment, minimize conflicts, and keep employee complaints/disputes at a low level	Proactively collaborate with all departments to build more sustainable employee relations	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Ensure compliance with labor laws and minimize legal risks for the company	R4		Ensure no major violations occur; effectively control risks related to audits and inspections	Proactively assess employee relations risks and ensure timely and effective mitigation	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Lead the handling of complex and sensitive employee relations cases	R4		Resolve issues effectively and in compliance with regulations, minimizing impact on operations and company reputation	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Collaborate in developing, reviewing, and optimizing company labor policies and internal regulations	R3	X	Ensure policies are clear, timely updated, practical, and effectively implemented	Ensure continuous review and timely updates	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Coordinate with the trade union and relevant stakeholders to organize employee engagement activities and events	R4		Organize effective engagement activities, enhance employee engagement, and receive positive feedback from employees	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Manage and control disciplinary actions to ensure fairness and consistency	R4		Ensure fairness, consistency, and transparency in disciplinary actions	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Implement communication initiatives to enhance awareness of employee relations across the organization	R4		Ensure employees understand and comply with policies and regulations; reduce violations caused by lack of awareness	Proactively plan and communicate to employees in a timely manner	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Drive initiatives to improve employee engagement and workplace environment	R3	X	Improve employee satisfaction, reduce turnover, and enhance employee engagement	Proactively develop employee engagement initiatives aligned with the company’s culture and strategic direction	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Analyze data and prepare reports on absenteeism (AB) and turnover (TO)	R3	X	Deliver accurate and timely reports; provide insights and recommend improvement actions	Take a proactive approach to data analysis and ensure all reports are accurate, timely, and compliant with relevant regulations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Build, maintain, and expand relationships with partners and service providers	R4		Maintains excellent, professional relationships with external vendors	Establish formal vendor performance evaluations (scorecards) to sustain quality	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
70355	Do Thi Thanh Nga	Human Resources	Supervisor	Prepare compliance documentation for annual external and internal audits	R4		Achieves high preparation standards; passes all audits successfully	Establish a continuous compliance calendar to sustain readiness	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Elsa Nguyen	Human Resources	HR Head	People Development (Sharpen the Saw)	R4	X	Actively develops direct reports and supports organizational learning	Continue key talent mentoring	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Succession Planning	R3		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Recruitment Plan Development	R3		Strong execution; needs more strategic planning	Build annual recruitment plan	Ongoing	Align with manpower plan	Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Recruitment Execution	R3		Executes hiring well; improve metrics usage	Strengthen recruitment analytics	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Department Follow-up	Business Acumen Framework	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Budget development & management	R3		Building & Planning in HR budgeting and cost control	Support cross-functional budgeting	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Personal Development (Sharpen the Saw)	R4	X	Development activities structured	Create and follow IDP	Q1–Q4	Leadership focus	People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Department Follow-up	Business Acumen Framework	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Executive Presentation Skills	R3	X	Can improve executive delivery style	Receive structured communication feedback	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Talent Assessment & Calibration	R3		Good coaching skills; needs structured talent calibration framework	Co-develop succession map with HR Head; identify high-potentials	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	L&D Framework & Training Roadmap Design	R3		Delivers effective training; formal training roadmap design is in development	Develop competency framework for key pipelines; pilot Q3	Q3–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Headcount & Manpower Strategy Planning	R4		Demonstrates strong workforce planning aligned to business expansion	Lead annual HC planning for next cycle; present for approval	Annual cycle		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Performance Evaluation & PDMS Alignment	R4		Conducts thorough reviews; strong in PDMS administration	Standardize PDMS target-setting across all divisions; train new leads	Q2 & Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Compensation & Benefits Strategy	R3		Good at standard execution; strategic structure design can improve	Co-develop localized C&B framework with corporate; review market alignment	Q3–Q4		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Labor Law & Employee Relations Compliance	R4		Ensures full compliance; leading complex employee disputes is an area of growth	Act as lead representative for critical employee relations audits	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Lean HR & Process Automation	R3	X	Tracks HR metrics manually; process automation in reporting needs development	Lead pilot digitization of 1 HR system (recruitment tracker/onboarding)	Q3–Q4		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Employee Retention & Engagement Strategy	R3		Good at organizing events; structured retention programs are in development	Co-develop division-wide employee retention roadmap with Plant Dir	Q2–Q3		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Culture & Core Values Cascade Leadership	R4		Strong values mindset; actively cascades culture across division	Continue best practices; coach leads on cascading techniques	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Audit Documentation & Compliance Readiness	R4		Maintains detailed compliance records; passes standard checks	Mentor new HR supervisors on audit documentation readiness	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Venus Le
-	Elsa Nguyen	Human Resources	HR Head	Organizational Design & Workforce Strategy	R3		Aligns structure with current goals; predictive organizational mapping can improve	Design 3-year organizational scaling map; present to leadership	Q4		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Venus Le
30200	Mai Thi Loan	Human Resources	Supervisor	Build and maintain harmonious and stable employee relations	R4		Maintain a positive work environment, minimize conflicts, and keep employee complaints/disputes at a low level	Proactively collaborate with all departments to build more sustainable employee relations	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Ensure compliance with labor laws and minimize legal risks for the company	R4		Ensure no major violations occur; effectively control risks related to audits and inspections	Proactively assess employee relations risks and ensure timely and effective mitigation	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Lead the handling of complex and sensitive employee relations cases	R4		Resolve issues effectively and in compliance with regulations, minimizing impact on operations and company reputation	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Collaborate in developing, reviewing, and optimizing company labor policies and internal regulations	R3	X	Ensure policies are clear, timely updated, practical, and effectively implemented	Ensure continuous review and timely updates	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Coordinate with the trade union and relevant stakeholders to organize employee engagement activities and events	R4		Organize effective engagement activities, enhance employee engagement, and receive positive feedback from employees	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Manage and control disciplinary actions to ensure fairness and consistency	R4		Ensure fairness, consistency, and transparency in disciplinary actions	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Implement communication initiatives to enhance awareness of employee relations across the organization	R4		Ensure employees understand and comply with policies and regulations; reduce violations caused by lack of awareness	Proactively plan and communicate to employees in a timely manner	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Drive initiatives to improve employee engagement and workplace environment	R3	X	Improve employee satisfaction, reduce turnover, and enhance employee engagement	Proactively develop employee engagement initiatives aligned with the company’s culture and strategic direction	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Analyze data and prepare reports on absenteeism (AB) and turnover (TO)	R3	X	Deliver accurate and timely reports; provide insights and recommend improvement actions	Take a proactive approach to data analysis and ensure all reports are accurate, timely, and compliant with relevant regulations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Build, maintain, and expand relationships with partners and service providers	R4		Maintains excellent, professional relationships with external vendors	Establish formal vendor performance evaluations (scorecards) to sustain quality	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
30200	Mai Thi Loan	Human Resources	Supervisor	Prepare compliance documentation for annual external and internal audits	R4		Achieves high preparation standards; passes all audits successfully	Establish a continuous compliance calendar to sustain readiness	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Build and maintain harmonious and stable employee relations	R4		Maintain a positive work environment, minimize conflicts, and keep employee complaints/disputes at a low level	Proactively collaborate with all departments to build more sustainable employee relations	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Ensure compliance with labor laws and minimize legal risks for the company	R3	X	Ensure no major violations occur; effectively control risks related to audits and inspections	Proactively stay updated on changes in labor laws and effectively apply them in daily operations	Q2-Q4		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Lead the handling of complex and sensitive employee relations cases	R3	X	Resolve issues effectively and in compliance with regulations, minimizing impact on operations and company reputation	Continuously enhance professional capabilities to effectively handle complex and sensitive employee relations cases	Q2-Q4		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Collaborate in developing, reviewing, and optimizing company labor policies and internal regulations	R3	X	Ensure policies are clear, timely updated, practical, and effectively implemented	Ensure continuous review and timely updates	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Coordinate with the trade union and relevant stakeholders to organize employee engagement activities and events	R4		Organize effective engagement activities, enhance employee engagement, and receive positive feedback from employees	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Manage and control disciplinary actions to ensure fairness and consistency	R4		Ensure fairness, consistency, and transparency in disciplinary actions	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Implement communication initiatives to enhance awareness of employee relations across the organization	R4		Ensure employees understand and comply with policies and regulations; reduce violations caused by lack of awareness	Proactively plan and communicate to employees in a timely manner	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Drive initiatives to improve employee engagement and workplace environment	R4		Improve employee satisfaction, reduce turnover, and enhance employee engagement	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Analyze data and prepare reports on absenteeism (AB) and turnover (TO)	R3	X	Deliver accurate and timely reports; provide insights and recommend improvement actions	Take a proactive approach to data analysis and ensure all reports are accurate, timely, and compliant with relevant regulations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Build, maintain, and expand relationships with partners and service providers	R4		Maintains excellent, professional relationships with external vendors	Establish formal vendor performance evaluations (scorecards) to sustain quality	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Annie Nguyen	Human Resources	Specialist	Prepare compliance documentation for annual external and internal audits	R4		Achieves high preparation standards; passes all audits successfully	Establish a continuous compliance calendar to sustain readiness	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Amber Dinh	EHS	EHS Head	EHS Strategy & Regulatory Compliance	R4		Drives EHS strategy with excellent compliance; keeps division risk‑free	Formulate site‑wide EHS roadmap; present to Division Head for approval	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Safety Audit Program Design & Governance	R4		Maintains robust internal safety audit programs with zero major regulatory findings	Standardize safety audit checklists across all division manufacturing lines	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	KPI & Incident Metics Reporting Dashboard	R4		Tracks and reports TRIR/LTI metrics precisely; presentation has executive clarity	Transition static EHS reports into an interactive Power BI dashboard	Ongoing		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Culture of Safety & Employee Awareness	R4		Drives safety culture effectively; high engagement in safety drill programs	Mentor Lead Supervisors on designing visual EHS awareness campaigns	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Disaster Recovery & Crisis Management Oversight	R4		DR and crisis plans exist and are validated; co‑leads drills with high authority	Lead a joint division‑wide fire and chemical spill simulation drill	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Critical Environmental & Permit Governance	R4		Manages EHS licenses and compliance permits with zero delays or penalties	Coordinate pre‑audit reviews for upcoming major environmental inspection	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Wastewater & Waste Refurbishment Cost controls	R3	X	Tracks waste costs; needs proactive identification of disposal savings	Own 1‑2 wastewater or hazardous‑waste disposal cost‑reduction initiatives	Q2–Q4		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Team Leadership & Professional Development	R3	X	Technically coaches safety officers; needs formal competency pathway for team	Establish a structured EHS competency matrix and 1‑1 mentoring plans	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Cross‑Functional Collaboration (Ops/IE/HR)	R4		Drives alignment with Operations and HR smoothly to implement EHS standards	Co‑host a monthly safety alignment meeting with all Plant Managers	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
-	Amber Dinh	EHS	EHS Head	Executive Presentation & Communication	R3	X	Builds highly technical reports; presentation narrative can be more strategic	Present EHS KPI dashboard to Plant Dir; receive structured feedback on delivery	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Elsa Nguyen
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Develop organizational structure, execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo theo kế hoạch"	R3	X	"Meets requirements but has room to improve in active succession planning
Đáp ứng yêu cầu nhưng cần chủ động hơn trong quy hoạch cán bộ nguồn."	"Actively identify and mentor potential successors to build pipeline strength
Chủ động tìm kiếm và đào tạo nhân sự kế thừa để tăng cường lực lượng dự phòng."	Q3-2026		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Allocate purchasing roles effectively to meet workload peaks
Sắp xếp, phân bổ nhân lực hợp lý đáp ứng khối lượng công việc cao điểm"	R4		"Sắp xếp nhân sự hợp lý theo nhu cầu sản xuất từng thời kỳ."	"Cross-train buyers across different categories to handle sudden peaks
Đào tạo chéo nhân viên mua hàng giữa các nhóm hàng để xử lý cao điểm."	On going		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Monitor, coordinate, and supervise work progress; handle arising issues
Theo dõi, điều phối và giám sát tiến độ công việc, kịp thời xử lý các vấn đề phát sinh."	R4		"Monitors progress closely and resolves operational issues promptly
Theo sát tiến độ và giải quyết nhanh các sự cố phát sinh."	"Standardize incident handling protocols and improve response times
Chuẩn hóa quy trình xử lý sự cố, nâng cao tốc độ phản hồi."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Evaluate team performance and build continuous capability development plans
Đánh giá năng lực đội ngũ, lên kế hoạch phát triển chuyên môn liên tục."	R3	X	"Evaluates team regularly; needs a more structured development framework
Có đánh giá thường xuyên nhưng cần hệ thống hóa khung năng lực chuyên môn"	"Build an internal competency framework and organize structured peer-coaching
Xây dựng khung năng lực nội bộ, tổ chức các buổi kèm cặp chéo trong tổ."	On going		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Guide and supervise compliance with safety and environment guidelines
Hướng dẫn, nhắc nhở EHS hằng ngày và giám sát việc tuân thủ thực hiện"	R4		"Enforces guidelines well; zero safety or workspace violations reported
Thực hiện tốt hướng dẫn EHS, không xảy ra vi phạm tại khu vực."	"Establish a standardized safety check checklist and assign area owners
Chuẩn hóa danh mục kiểm tra an toàn và phân công trách nhiệm rõ ràng."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Conduct research and testing to optimize and improve purchasing processes
Nghiên cứu, thử nghiệm để cải tiến quy trình mua hàng hiệu quả"	R3	X	"Proposes practical ideas; implementation and tracking can be more systematic
Đề xuất nhiều ý tưởng thực tế; cần theo dõi kết quả một cách hệ thống hơn."	"Apply Lean tools to reduce non-value-added steps in purchasing workflows
Áp dụng các công cụ Lean để giảm các bước thừa trong quy trình mua hàng."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Organize and participate in employee engagement and cohesion initiatives
Tổ chức và tham gia các hoạt động gắn kết thành viên trong bộ phận"	R4		"Builds an active, collaborative, and highly supportive environment
Tạo không khí làm việc sôi nổi, đoàn kết và sẵn sàng hỗ trợ nhau."	"Design mini-team challenges or sharing sessions to sustain morale
Tổ chức các buổi chia sẻ nhỏ trong tổ để duy trì tinh thần làm việc tích cực."	On going		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Manage, utilize, and optimize procurement costs
Quản lý, sử dụng và tiết kiệm các khoản chi phí mua hàng hiệu quả"	R3	X	"Tracks spending well; needs proactive identification of purchasing cost reductions
Theo dõi tốt chi tiêu; cần chủ động hơn khi tìm kiếm giải pháp giảm chi phí"	"Complete Lean Six Sigma Green Belt training and apply on 1 cost-saving project
Hoàn thành đào tạo Green Belt, dẫn dắt 1 dự án tiết kiệm chi phí mua hàng."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Prepare compliance documentation for annual external and internal audits
Chuẩn bị hồ sơ phục vụ công tác kiểm toán và rà soát định kỳ hàng năm"	R4		"Achieves high preparation standards; passes all audits successfully
Chuẩn bị hồ sơ chu đáo và hoàn thành xuất sắc các đợt kiểm tra."	"Establish a continuous compliance calendar to sustain readiness
Xây dựng lịch trình tuân thủ liên tục, tránh dồn việc sát ngày kiểm tra."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Build, maintain, and expand relationships with suppliers and service providers
Xây dựng và phát triển mối quan hệ với các nhà cung cấp"	R4		"Maintains excellent, professional relationships with external vendors
Duy trì mối quan hệ hợp tác tốt đẹp và chuyên nghiệp với các nhà cung cấp."	"Establish formal vendor performance evaluations (scorecards) to sustain quality
Chuẩn hóa quy trình đánh giá nhà cung cấp định kỳ để duy trì chất lượng dịch vụ."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
18320	Vu Van Xuan	Procurement	Lead Supervisor	"Analyze material markets and forecast price trends to optimize purchasing
Phân tích thị trường nguyên vật liệu và dự báo xu hướng giá"	R4		"Provides accurate market analysis to support strategic sourcing decisions
Phân tích thị trường tốt, hỗ trợ hiệu quả quyết định mua hàng chiến lược."	"Implement dynamic price tracking models for key commodity categories
Ứng dụng công cụ theo dõi giá động đối với các nhóm hàng chiến lược."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Amber Dinh
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Design master production schedules (MPS) and translate sales orders into plans
Xây dựng kế hoạch sản xuất tổng thể (MPS), chuyển đổi đơn hàng thành kế hoạch"	R4		"Ensures highly accurate schedule alignment with sales demands
Đảm bảo kế hoạch sản xuất chính xác, khớp với nhu cầu đơn hàng."	"Implement automated master-scheduling tools to optimize planning speed
Ứng dụng công cụ lập kế hoạch tự động hóa để tối ưu hóa tiến độ."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Manage and balance production capacity against forecasting demands
Quản lý và cân bằng công suất sản xuất dựa trên dự báo nhu cầu"	R4		"Successfully balances capacity requirements across manufacturing segments
Cân bằng tốt nhu cầu năng lực sản xuất giữa các bộ phận nhà máy."	"Research dynamic capacity simulation models for rapid bottleneck analysis
Nghiên cứu các mô hình mô phỏng công suất động để phân tích nhanh điểm nghẽn."	On going		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Monitor, adjust, and report daily production schedule adherence (PSA)
Theo dõi, điều chỉnh và báo cáo mức độ tuân thủ lịch trình sản xuất hàng ngày."	R4		"Achieves stable schedule adherence; responds swiftly to floor bottlenecks
Duy trì sự ổn định của lịch trình sản xuất, xử lý nhanh các vướng mắc."	"Transition static tracking boards into interactive digital scheduling portals
Chuyển đổi các bảng theo dõi tĩnh sang cổng thông tin lập kế hoạch số trực quan."	On going		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Evaluate team performance and build continuous capability development plans
Đánh giá năng lực đội ngũ, lên kế hoạch phát triển chuyên môn liên tục."	R3	X	"Evaluates team regularly; needs a more structured development framework
Có đánh giá thường xuyên nhưng cần hệ thống hóa khung năng lực chuyên môn"	"Build an internal competency framework and organize structured peer-coaching
Xây dựng khung năng lực nội bộ, tổ chức các buổi kèm cặp chéo trong tổ."	On going		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Develop departmental structure, execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo nhân sự theo mục tiêu"	R3	X	"Meets general requirements; needs to map out strong succession candidates
Đáp ứng yêu cầu chung; cần lập bản đồ nhân sự kế thừa chất lượng cho tổ."	"Establish a formal mentorship pipeline and assign stretch assignments to backups
Xây dựng lộ trình kèm cặp, giao các nhiệm vụ thử thách cho nhân sự dự phòng."	Q3-2026		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Allocate planning and coordination roles effectively to meet workload peaks
Sắp xếp, phân bổ nhân lực hợp lý đáp ứng khối lượng công việc cao điểm"	R4		"Sắp xếp nhân sự hợp lý theo nhu cầu sản xuất từng thời kỳ."	"Cross-train planners across different divisions to handle sudden peaks
Đào tạo chéo nhân viên lập kế hoạch giữa các xưởng để xử lý cao điểm."	On going		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Guide and supervise compliance with safety and environment guidelines
Hướng dẫn, nhắc nhở EHS hằng ngày và giám sát việc tuân thủ thực hiện"	R4		"Enforces guidelines well; zero safety or workspace violations reported
Thực hiện tốt hướng dẫn EHS, không xảy ra vi phạm tại khu vực."	"Establish a standardized safety check checklist and assign area owners
Chuẩn hóa danh mục kiểm tra an toàn và phân công trách nhiệm rõ ràng."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Conduct research and testing to optimize and improve planning processes
Nghiên cứu, thử nghiệm để cải tiến quy trình lập kế hoạch hiệu quả"	R3	X	"Proposes practical ideas; implementation and tracking can be more systematic
Đề xuất nhiều ý tưởng thực tế; cần theo dõi kết quả một cách hệ thống hơn."	"Apply Lean tools to reduce non-value-added steps in planning workflows
Áp dụng các công cụ Lean để giảm các bước thừa trong quy trình lập kế hoạch."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Organize and participate in employee engagement and cohesion initiatives
Tổ chức và tham gia các hoạt động gắn kết thành viên trong bộ phận"	R4		"Builds an active, collaborative, and highly supportive environment
Tạo không khí làm việc sôi nổi, đoàn kết và sẵn sàng hỗ trợ nhau."	"Design mini-team challenges or sharing sessions to sustain morale
Tổ chức các buổi chia sẻ nhỏ trong tổ để duy trì tinh thần làm việc tích cực."	On going		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Manage, utilize, and optimize operational costs within the department
Quản lý, sử dụng và tiết kiệm các khoản chi phí phát sinh hiệu quả"	R3	X	"Tracks spending well; needs proactive identification of planning cost reductions
Theo dõi tốt chi tiêu; cần chủ động hơn khi tìm kiếm giải pháp giảm chi phí"	"Complete Lean Six Sigma Green Belt training and apply on 1 cost-saving project
Hoàn thành đào tạo Green Belt, dẫn dắt 1 dự án tiết kiệm chi phí lập kế hoạch."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	"Prepare compliance documentation for annual external and internal audits
Chuẩn bị hồ sơ phục vụ công tác kiểm toán và rà soát định kỳ hàng năm"	R4		"Achieves high preparation standards; passes all audits successfully
Chuẩn bị hồ sơ chu đáo và hoàn thành xuất sắc các đợt kiểm tra."	"Establish a continuous compliance calendar to sustain readiness
Xây dựng lịch trình tuân thủ liên tục, tránh dồn việc sát ngày kiểm tra."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Daniel Pham
04698	Giap Quang Huy	P&IC	Lead Supervisor	Học hỏi công cụ AI để lập kế hoạch cải thiện hiệu quả công việc, giảm thời gian làm báo cáo thủ công	R2	X	Cải tiến hiệu quả công việc	Học phần mềm Copilot, power BI và phối hợp các bộ phận liên quan triển khai	Q2–Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Daniel Pham
78201	Trinh Ngoc Phien	IT	Lead Supervisor	IT Operations Oversight (Helpdesk, Infra, Apps)	R4		Keeps daily IT operations stable; cross-functional oversight can become more proactive.		Q2–Q3/2026: Define site-level IT operations roadmap	Strong foundation for higher level role	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	IT Service Management Practice	R3	X	Handles service issues effectively; problem management maturity needs improvement.	Strengthen ITSM practices with metrics-driven service improvement and preventive problem management	Q4/2026: Service KPIs & review cadence established		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	IT Budget Tracking & Cost Control	R4		Monitors spending responsibly; forecasting and variance analysis can improve.		Q1		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	Vendor Coordination & SLA Governance	R4		Maintains vendor communication well; SLA tracking can be more data-driven.		On-going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	IT Policy Implementation	R4		Applies existing policies consistently; contribution to policy improvement can be stronger.		Q1/2026 Policy review & enhancement with team		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	User Satisfaction & Service Improvement	R4		Receives generally positive feedback; formal service improvement process is limited.	Introduce structured feedback loops and continuous service improvement plans	Ongoing: Listening the feedback of user satisfaction		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	IT Risk Identification & Escalation	R3	X	Escalates major issues appropriately; risk documentation can be more standardized.	Introduce structured feedback loops and continuous service improvement plans	Q3/2026: Risk register established		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	Cross-Department Communication	R4		Communicates clearly with users and peers; management-facing updates can be more strategic.	Continue acting as site IT representative in leadership and cross‑functional discussions	On-going	Operating at HoD communication level	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	Team Supervision & Performance Coaching	R3	X	Provides operational guidance effectively; structured KPI coaching can improve.	Develop successor roles and shift from task execution to leadership through others	Q4/2026: Identify and develop successor roles		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	Digital Transformation Support	R4	X	Supports transformation initiatives well; should contribute more proactive improvement ideas.	Lead at least one cross‑functional digital or AI initiative end‑to‑end with measurable business impact.	Q2–Q4/2026: Deliver transformation outcomes	High visibility opportunity	Business Acumen	Business Acumen	Department Follow-up	Business Acumen Framework	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	IT Asset Lifecycle Management	R4		Manages assets responsibly; lifecycle visibility and refresh planning can be improved.		Q1/2026	Stable and consistent.	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	License & Access Administration	R4		Handles provisioning accurately; periodic review and optimization should be tightened.		On-going	Operationally strong	Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Tom Nguyen
78201	Trinh Ngoc Phien	IT	Lead Supervisor	IT SOP & Documentation Governance	R4		Maintains operating procedures adequately; consistency and ownership need strengthening.		Q2/2026		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Coordinate production materials
Điều phối nguyên vật liệu sản xuất"	R4		"Successfully meets all material requirements on the production floor
Đáp ứng đầy đủ, kịp thời nguyên vật liệu phục vụ sản xuất."	"Establish visual inventory controls (Kanban) to optimize floor storage
Áp dụng các biện pháp kiểm soát trực quan (Kanban) để tối ưu lưu trữ tại xưởng."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Monitor, coordinate, and supervise work progress; handle arising issues
Theo dõi, điều phối và giám sát tiến độ công việc, kịp thời xử lý các vấn đề phát sinh"	R4		"Resolves daily operational bottlenecks efficiently
Xử lý nhanh chóng các điểm nghẽn trong vận hành hàng ngày."	"Standardize daily problem-solving checklists for team leaders
Chuẩn hóa danh mục giải quyết vấn đề hàng ngày cho Team leader."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Ensure output quality matches standards
Đảm bảo chất lượng đầu ra phù hợp tiêu chuẩn"	R4		"Maintains defect rates below targets; strong quality mindset
Kiểm soát tốt tỉ lệ lỗi dưới mức cho phép, ý thức chất lượng cao."	"Strengthen self-inspection steps and process quality controls
Tăng cường tự kiểm tra và kiểm soát chất lượng tại nguồn."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Evaluate team performance and build continuous development plans
Đánh giá hiệu quả công việc của đội nhóm, lên kế hoạch phát triển liên tục"	R3	X	"Evaluates team regularly; needs a more systematic training framework
Có đánh giá thường xuyên nhưng cần hệ thống hóa khung đào tạo kỹ năng."	"Build an internal skill matrix and organize structured peer-learning sessions
Xây dựng ma trận kỹ năng nội bộ, tổ chức các buổi học tập chéo giữa các tổ."	On going		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Develop organizational structure, execute recruitment and training plans
Xây dựng sơ đồ tổ chức, tuyển dụng và đào tạo theo kế hoạch"	R3	X	"Meets general requirements; needs to proactively identify back-ups for key roles
Đáp ứng yêu cầu chung; cần chủ động quy hoạch nhân sự dự phòng cho các vị trí then chốt."	"Establish a formal succession pipeline and mentor high-potential members
Xây dựng lộ trình kế thừa rõ ràng, kèm cặp trực tiếp các nhân sự tiềm năng."	Q3-2026		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Allocate workforce effectively to meet operational needs
Tổ chức sắp xếp nhân lực làm việc phù hợp đáp ứng nhu cầu công việc"	R4		"Sắp xếp nhân sự hợp lý, đảm bảo cân bằng chuyền tốt."	"Develop multi-skilled workers (cross-training) to improve floor flexibility
Đào tạo công nhân đa năng để nâng cao tính linh hoạt của dây chuyền."	On going		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Guide and supervise compliance with daily safety (EHS) and fire safety regulations
Hướng dẫn, nhắc nhở ATLĐ, ATPCCN hằng ngày và giám sát việc tuân thủ thực hiện"	R4		"Maintains excellent safety records; team shows high safety awareness
Duy trì hồ sơ an toàn tốt, đội ngũ có ý thức tuân thủ cao."	"Implement daily safety discussions (toolbox talks) to sustain awareness
Duy trì họp nhanh đầu giờ về an toàn để nhắc nhở thường xuyên."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Conduct research and testing to optimize and improve work processes
Nghiên cứu, thử nghiệm để cải tiến quy trình làm việc hiệu quả và tối ưu"	R3	X	"Suggests improvements; needs to follow up systematically on execution results
Có đề xuất cải tiến nhưng cần theo dõi sát kết quả thực tế một cách hệ thống."	"Learn and apply Kaizen / 5S tools to standardize improvements
Học hỏi và áp dụng các công cụ Kaizen / 5S để chuẩn hóa quy trình cải tiến."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Organize and participate in employee engagement activities
Tổ chức và tham gia các hoạt động gắn kết NLĐ"	R4		"Creates an enthusiastic, cohesive, and collaborative team atmosphere
Tạo không khí làm việc sôi nổi, đoàn kết và sẵn sàng hỗ trợ nhau."	"Design mini-challenges on the floor to drive team spirit and productivity
Tổ chức các phong trào thi đua nhỏ tại xưởng để thúc đẩy tinh thần đồng đội."	On going		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Manage, utilize, and optimize operational costs
Quản lý, sử dụng và tiết kiệm các khoản chi phí phát sinh"	R3	X	"Manages direct material waste well; indirect spending control can be optimized
Kiểm soát hao hụt vật tư tốt; cần tối ưu hóa thêm các chi phí gián tiếp khác."	"Train team on waste identification and cost-saving habits
Đào tạo đội ngũ nhận diện lãng phí và rèn luyện thói quen tiết kiệm."	On going		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Prepare for annual external compliance audits (environmental, fire safety)
Chuẩn bị cho công tác kiểm tra Vệ sinh môi trường và PCCC hằng năm"	R4		"Maintains ready compliance; passes all inspections with ease
Luôn trong trạng thái sẵn sàng, vượt qua các đợt kiểm tra thuận lợi."	"Establish a continuous checklist and assign clear area-owners
Chuẩn hóa danh mục kiểm tra liên tục, phân công trách nhiệm rõ ràng theo khu vực."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	"Build, maintain, and expand relationships with partners and service providers
Xây dựng và phát triển mối quan hệ với các đối tác"	R4		"Works collaboratively with supporting sections (Maintenance, QA, Warehouse)
Hợp tác rất tốt với các bộ phận hỗ trợ (Bảo trì, QA, Kho)."	"Set up weekly alignment meetings to resolve cross-department bottlenecks
Duy trì họp giao ban định kỳ để xử lý nhanh các vướng mắc liên bộ phận."	On going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	Học hỏi công cụ AI để lập kế hoạch cải thiện hiệu quả công việc, giảm thời gian làm báo cáo thủ công	R2	X	Cải tiến hiệu quả công việc	Học phần mềm Copilot, power BI và phối hợp các bộ phận liên quan triển khai	Q2–Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	Evaluate and improve the efficiency of the training system	R4		Establish and coordinate to organize and monitor standard training programs.	Optimize training delivery and assessment methods.	Ongoing		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	Organize, and monitor standard training programs	R4		Effectively coordinate and deploy standard training courses to target audiences.	Maintain proper documentation and tracking.	Ongoing		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Nhat Huynh
17436	Dinh Thi Hong Van	UPH Assembly WNK2	Specialist	Follow up after training to evaluate the effectiveness and application of knowledge	R3	X	Monitor progress and support trainees after training; can improve systematic post‑training evaluation.	Design formal follow‑up procedures and impact assessment tools.	Ongoing		Functional	Training Capability	Department Follow-up	Training Capability Follow-up	Department / Functional SME	Nhat Huynh
`;
