export const rawWanekIDPTSV_part3 = `23679	Danny Cao	IT	Manager	Business Requirement Governance	R4		Captures requirements clearly; standards for documentation and traceability can improve.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	Process Analysis & Optimization	R4		Strong at mapping current processes; benefit quantification needs to be more consistent.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	Stakeholder Engagement & Alignment	R4		Builds productive relationships; can further strengthen alignment across competing priorities.	Create stakeholder map and clear communication plan; lead alignment sessions for key projects	Q1: Map & plan | Q2: Run workshops | Q3–Q4: Improve feedback (≥80%)	Need better alignment across teams; support needed for conflict resolution	Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Jonathan To
23679	Danny Cao	IT	Manager	Project Prioritization & Backlog Governance	R4	X	Backlog is managed effectively; prioritization criteria need to be more transparent.	Define clear prioritization rules; standardize backlog process and improve transparency	Q1: Define criteria | Q2: Apply process | Q3: Track via dashboard	Backlog works but not transparent; need alignment with business owners	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	ERP/System Enhancement Planning	R4	X	Supports enhancements well; long-term enhancement roadmap needs more ownership.	Together with US team, Build roadmap; assign clear ownership; align with business goals	Q2: Draft roadmap | Q3: Finalize | Q4: Track progress	Need stronger ownership and long-term planning	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	Change Impact Assessment	R2	X	Identifies system impacts accurately; downstream business impact analysis can go deeper.	do more, learn more related system (ERP, Manufacturing, Distribution)	Q2: Draft roadmap | Q3: Finalize | Q4: Track progress	Need stronger ownership and long-term planning	Business Acumen	Business Acumen	Department Follow-up	Business Acumen Framework	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	User Acceptance Testing Governance	R3		Coordinates UAT effectively; issue tracking and closure metrics can be more disciplined				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	Data Analysis & Reporting Governance	R3		Provides reliable reporting support; analytical insight generation can be expanded.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	Team Coaching & Analyst Development	R2	X	Supports team members well; competency development should be more structured.	Create skill framework; run monthly coaching; build team development plans		Team support is good but not structured yet	Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Jonathan To
23679	Danny Cao	IT	Manager	Master Data & Process Governance	R2		Understands master data dependencies; governance routines need stronger consistency.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	KPI Definition & Business Reporting Alignment	R2		Understands reporting needs; KPI alignment with business outcomes needs more rigor.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	Change Management & User Enablement	R4		Supports user readiness activities; training and communication planning can be more proactive.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
23679	Danny Cao	IT	Manager	Executive Communication & Portfolio Reporting	R4		Shares project status clearly; executive-level summaries should be more concise and insight-driven.				Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Jonathan To
56340	Leo Le	IT	Assistant Manager	Application Development Roadmap Alignment	R4		Delivers assigned development work well; long-term product and architecture planning can improve.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
56340	Leo Le	IT	Assistant Manager	System Architecture & Code Quality Governance	R3		Applies sound technical judgment; coding standards and design review can be more consistent.	Release for team/sub handle, monitoring only			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
56340	Leo Le	IT	Assistant Manager	DevOps & Release Management	R3		Handles releases reliably; automation and rollback planning should be strengthened.	Release for team/sub handle, monitoring only			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
56340	Leo Le	IT	Assistant Manager	System Stability & Incident Resolution	R4		Resolves issues quickly; root cause documentation and preventive actions can improve.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
56340	Leo Le	IT	Assistant Manager	Supervise and control all aspects of production activities to maximize the use of resources, machinery, and labor while minimizing waste.	R3	X	"Drive operational efficiency through process optimization, effective resource allocation, and cost control
Thúc đẩy vận hành hiệu quả thông qua tối ưu quy trình, phân bổ nguồn lực hợp lý và đảm bảo hiệu quả chi phí sản xuất."	"Continuously improve processes and optimize resource utilization to enhance productivity and reduce operational costs
Liên tục cải tiến quy trình và tối ưu sử dụng nguồn lực nhằm nâng cao năng suất và giảm chi phí vận hành."	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Ensure necessary raw materials for production are always available in the company.	R4		"Proactively collaborate with Procurement and Supply Chain teams to prevent shortages and mitigate supply risks
Chủ động phối hợp với bộ phận mua hàng và chuỗi cung ứng để phòng ngừa thiếu hụt và giảm thiểu rủi ro nguồn cung"	"Anticipate supply risks and implement contingency plans such as alternative sourcing and safety stock strategies
Dự báo các rủi ro nguồn cung và triển khai các phương án dự phòng như nhà cung cấp thay thế hoặc tồn kho an toàn"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Establish product quality standards and regulations.	R4		"Regularly review and update quality standards to drive continuous improvement and maintain product consistency
Thường xuyên rà soát, cập nhật tiêu chuẩn chất lượng nhằm thúc đẩy cải tiến liên tục và duy trì độ ổn định của sản phẩm"	"Foster a culture of continuous improvement by integrating feedback, evaluation results, and operational data into quality enhancement initiatives
Thường xuyên rà soát, cập nhật tiêu chuẩn chất lượng nhằm thúc đẩy cải tiến liên tục và duy trì độ ổn định của sản phẩm"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Conduct quality inspections at each stage of production to ensure output meets required standards	R4		"Proactively identify defects early in the production process and implement corrective actions to prevent recurrence, ensuring stable quality
Chủ động phát hiện lỗi sớm trong quá trình sản xuất và triển khai hành động khắc phục để ngăn ngừa tái diễn, đảm bảo chất lượng ổn định"	"Strengthen in-process quality control to minimize defects and ensure timely corrective actions to prevent recurrence
Tăng cường kiểm soát chất lượng trong quá trình nhằm giảm thiểu sai lỗi hoặc triển khai các hành động khắc phục kịp thời nhằm ngăn ngừa tái diễn."	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Regularly update and improve processes to enhance product quality.	R4		"Continuously seek improvement opportunities and implement effective solutions to enhance product quality
Chủ động tìm kiếm cơ hội cải tiến và triển khai các giải pháp hiệu quả để nâng cao chất lượng một cách liên tục."	"Encourage and lead continuous improvement initiatives to enhance overall quality performance
Khuyến khích và dẫn dắt các hoạt động cải tiến liên tục nhằm nâng cao hiệu quả chất lượng tổng thể."	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Manage and evaluate product quality within the company.	R4		"Effectively manage and evaluate product quality to ensure alignment with company standards and customer expectations
Quản lý và đánh giá chất lượng sản phẩm một cách hiệu quả, đảm bảo luôn phù hợp với tiêu chuẩn công ty và kỳ vọng của khách hàng"	"Leverage data analysis and customer feedback to drive continuous improvement
Ứng dụng phân tích dữ liệu và phản hồi từ khách hàng để thúc đẩy cải tiến liên tục"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Manage and optimize costs related to materials, raw materials, labor, and machinery in the production process.	R3	X	"Ensure effective control of key operational areas, including:
1/Control raw and auxiliary materials received in accordance with BOM
2/Control materials issued from the MRO warehouse
3/Plan and manage production schedules and overtime effectively
4/Conduct equipment inspection, preventive maintenance, and servicing
5/Ensure efficient usage and cost-saving of materials and supplies"	"Implement appropriate control and maintenance measures to ensure operational stability, efficiency, and cost optimization
Triển khai các biện pháp kiểm soát và bảo trì phù hợp nhằm đảm bảo tính ổn định, hiệu quả và tối ưu chi phí."	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Minimize waste and defects to reduce product costs.	R4		"Drive continuous improvement initiatives to optimize processes, reduce waste, and enhance cost competitiveness
Thúc đẩy các hoạt động cải tiến liên tục để tối ưu quy trình, giảm tổn thất và nâng cao năng lực cạnh tranh về chi phí."	"Lead improvement projects focused on enhancing efficiency, reducing waste, and delivering sustainable value
Dẫn dắt các dự án cải tiến tập trung vào nâng cao hiệu quả, giảm lãng phí và tạo ra giá trị bền vững"	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Control production costs to ensure products are manufactured at the lowest possible cost while maximizing profit	R3	X	"Monitor and analyze cost drivers to ensure effective cost control and identify production optimization opportunities, including:
1/Rework
2/Rejects / scrap
3/Material usage in compliance with BOM
4/SOP adherence in operations
5/Maintenance and servicing costs
6/Utilities (electricity and water)
7/Overtime costs
8/Headcount
Waste management"	"Regularly review cost structure and implement improvement initiatives to achieve cost savings
Thường xuyên đánh giá cơ cấu chi phí và triển khai các giải pháp cải tiến nhằm đạt được hiệu quả tiết kiệm"	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Use electricity and water efficiently.	R4		"Ensure effective control and efficient utilization of electricity and water consumption
Kiểm soát việc sử dụng nguồn năng lượng điện nước  hợp lý"	"Optimize energy utilization
Tối ưu hóa việc sử dụng nguồn năng lượng"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Conduct research and testing to improve the quality and features of existing products	R4		Phối hợp chặt chẽ với các bộ phận liên quan để triển khai các cải tiến phù hợp với nhu cầu khách hàng và thị trường	"Drive innovation initiatives and continuous improvement programs
Thúc đẩy các hoạt động đổi mới và các chương trình cải tiến liên tục"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Carry out R&D activities to improve company products by modifying or innovating part or all of the products.	R4		"Identify opportunities for product upgrades and drive changes in design, materials, or features to enhance value and competitiveness
Nhận diện cơ hội nâng cấp sản phẩm và thúc đẩy thay đổi về thiết kế, nguyên vật liệu hoặc tính năng nhằm gia tăng giá trị và tính cạnh tranh"	"Lead cross-functional collaboration to effectively implement improvement initiatives while ensuring cost efficiency
Dẫn dắt các hoạt động phối hợp liên phòng ban để triển khai hiệu quả các cải tiến nhằm đảm bảo chi phí hợp lý"	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Closely coordinate with the R&D department to introduce new products into production.	R4		"Ensure new product implementation meets quality, timeline, and cost objectives
Đảm bảo sản phẩm mới được triển khai đúng chất lượng, tiến độ và mục tiêu chi phí"	"Maintain effective cross-functional collaboration to manage the transition of products from development to mass production with maximum efficiency
Duy trỉ việc phối hợp với các bộ phận liên quan để quản lý quá trình đưa sản phẩm từ phát triển vào sản xuất hàng loạt đạt hiệu quả cao nhất"	Ongoing		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Guide and supervise compliance with safety measures in production.	R4		"Proactively identify unsafe behaviors or conditions and implement corrective actions to maintain a safe working environment
Chủ động phát hiện các hành vi hoặc điều kiện không an toàn và triển khai hành động khắc phục nhằm duy trì môi trường làm việc an toàn"	"Promote a strong safety culture by enhancing awareness, accountability, and continuous improvement in safety practices
'Thúc đẩy văn hóa an toàn thông qua việc nâng cao nhận thức, trách nhiệm và cải tiến liên tục trong thực hành an toàn"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
56340	Leo Le	IT	Assistant Manager	Prepare for annual environmental sanitation inspections by authorities.	R4		"Coordinate with relevant departments to ensure audit and inspection activities are properly prepared and executed in compliance with regulations
Phối hợp các bộ phận liên quan để đảm bảo các hạng mục kiểm tra được chuẩn bị và thực hiện đúng qui định"	"Monitor execution and drive accountability to ensure full compliance throughout inspection processes
Theo dõi quá trình thực hiện và thúc đẩy trách nhiệm nhằm đảm bảo tuân thủ đầy đủ trong suốt quá trình kiểm tra"	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Nhat Huynh
78493	Willy Pham	IT	Assistant Manager	IT Operations Oversight (Helpdesk, Infra, Apps)	R4		Keeps daily IT operations stable; cross-functional oversight can become more proactive.		Q2–Q3/2026: Define site-level IT operations roadmap	Strong foundation for higher level role	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	IT Service Management Practice	R3	X	Handles service issues effectively; problem management maturity needs improvement.	Strengthen ITSM practices with metrics-driven service improvement and preventive problem management	Q4/2026: Service KPIs & review cadence established		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	IT Budget Tracking & Cost Control	R4		Monitors spending responsibly; forecasting and variance analysis can improve.		Q1		Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	Vendor Coordination & SLA Governance	R4		Maintains vendor communication well; SLA tracking can be more data-driven.		On-going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	IT Policy Implementation	R4		Applies existing policies consistently; contribution to policy improvement can be stronger.		Q1/2026 Policy review & enhancement with team		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	User Satisfaction & Service Improvement	R4		Receives generally positive feedback; formal service improvement process is limited.	Introduce structured feedback loops and continuous service improvement plans	Ongoing: Listening the feedback of user satisfaction		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	IT Risk Identification & Escalation	R3	X	Escalates major issues appropriately; risk documentation can be more standardized.	Introduce structured feedback loops and continuous service improvement plans	Q3/2026: Risk register established		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	Cross-Department Communication	R4		Communicates clearly with users and peers; management-facing updates can be more strategic.	Continue acting as site IT representative in leadership and cross‑functional discussions	On-going	Operating at HoD communication level	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	Team Supervision & Performance Coaching	R3	X	Provides operational guidance effectively; structured KPI coaching can improve.	Develop successor roles and shift from task execution to leadership through others	Q4/2026: Identify and develop successor roles		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Jonathan To
78493	Willy Pham	IT	Assistant Manager	Digital Transformation Support	R4	X	Supports transformation initiatives well; should contribute more proactive improvement ideas.	Lead at least one cross‑functional digital or AI initiative end‑to‑end with measurable business impact.	Q2–Q4/2026: Deliver transformation outcomes	High visibility opportunity	Business Acumen	Business Acumen	Department Follow-up	Business Acumen Framework	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	IT Asset Lifecycle Management	R4		Manages assets responsibly; lifecycle visibility and refresh planning can be improved.		Q1/2026	Stable and consistent.	Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	License & Access Administration	R4		Handles provisioning accurately; periodic review and optimization should be tightened.		On-going	Operationally strong	Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Jonathan To
78493	Willy Pham	IT	Assistant Manager	IT SOP & Documentation Governance	R4		Maintains operating procedures adequately; consistency and ownership need strengthening.		Q2/2026		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	Audit & Compliance Coordination	R4		Supports audit preparation well; evidence organization can be more efficient.		Q1/2026		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
78493	Willy Pham	IT	Assistant Manager	Continuous Improvement & Automation Support	R4	X	Open to automation opportunities; needs to lead more improvement initiatives independently.	Drive continuous improvement projects and automation roadmap	On-going		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	IT Infrastructure Strategy & Roadmap	R4		Understands current infrastructure landscape well; needs stronger long-term roadmap alignment with business priorities.	Implement as roadmap that defined beginning the year	Q1, Q2, Q3, Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Cybersecurity Governance & Policy Development	R4		Solid control awareness; should deepen policy ownership and governance structure.	Revise policies to support the company’s growth and align with IT industry developments.	Q1		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Risk Assessment & Vulnerability Management	R4		Manages scanning and remediation effectively; risk reporting can be more executive-ready.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Cloud & On-Prem Architecture Management	R4	X	Technically capable across hybrid environments; cost and scalability planning can improve.	Learn more about cloud service and will ready  for any opportunity	Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Disaster Recovery & Business Continuity Planning	R2	X	Supports DR activities well; testing cadence and documentation should be more structured.	Need to be audit, SOP, and step by step when issue happen	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Incident Response Leadership	R2	X	Responds to incidents effectively; post-incident review and communication can be strengthened.	Will do correctly on Service now and use AI, reports to prevent the issue	Q2, Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Vendor & MSP Management	R2	X	Works well with vendors and partners; negotiation and performance scorecards need more rigor.	Need to get more vendors then we can have multiple options, saving cost	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Infrastructure Budget Planning & Control	R4		Tracks operational costs responsibly; capital planning needs broader forward visibility.	Contiue planning for IT bubget in the future			Functional	Finance / Cost Management	Department Follow-up	Finance / Cost Management Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Compliance & Audit Management	R4		Understands compliance requirements; needs more experience leading audits end-to-end.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Team Development & Technical Mentoring	R4	X	Provides strong technical guidance; should delegate development opportunities more intentionally.	Work more closely with team to guide and orientation, develop them	Whole year		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Capacity Planning & Performance Management	R3		Monitors system usage well; forecasting future capacity demand should be more proactive.	Monitors systems, and prevent the issue before it happen	Whole year		Functional	Workforce Planning	Department Follow-up	Workforce / Ramp Planning Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Identity & Access Management Oversight	R4		Applies access controls consistently; role-based access review process can be tighter.	Continue to audit and maintain the security as policy and request	Whole year		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Network & Endpoint Security Operations	R3		Maintains secure operations effectively; endpoint standardization can be improved.	Make sure all devices will update to date, and all client will be monitor and audit	Q1, Q2, Q3, Q4		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Infrastructure Documentation & Standardization	R4		Documentation exists for key systems; standards are not yet consistently maintained.	Network dgiagram will be updated and correct if have any change, and SOP to check and fix the issue. Any change will be recorded	Whole year		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
24867	Chivas Cao	Cut&Sew WNK3	Manager	Executive Reporting & Crisis Communication	R3		Communicates clearly during operational issues; executive summaries should be more concise and strategic.	All plan, improvement will be updated to BOD	Whole year		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Jonathan To
13405	Lucian Nguyen	IT	Manager	AI Strategy Alignment with Business Goals	N/A		Recognizes valuable AI opportunities; prioritization based on business impact can be sharper.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	AI Use Case Identification & Feasibility Analysis	N/A		Generates strong ideas; evaluation framework for feasibility and ROI needs more consistency.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Model Development & Deployment Governance	N/A		Technically capable in model delivery; governance for deployment is still maturing.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Data Governance & AI Ethics Oversight	N/A		Aware of responsible AI concerns; formal controls and ownership should be strengthened.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Cross-Functional Collaboration	N/A		Engages stakeholders well; influence across business units can be expanded further.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	AI Project Portfolio Management	N/A		Manages individual initiatives effectively; portfolio-level sequencing needs stronger discipline.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Vendor & AI Platform Evaluation	N/A		Assesses technical solutions well; commercial and risk evaluation can improve.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	AI Talent Development & Capability Building	N/A		Supports team learning actively; skill development roadmap should be more structured.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Performance Monitoring of AI Models	N/A		Tracks model outcomes adequately; automated monitoring and drift management need enhancement.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Innovation & Emerging Technology Scanning	N/A		Stays current on AI trends; needs stronger filtering for practical business value.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	AI Financial Planning & Business Case Development	N/A		Can estimate initiative value; cost-benefit justification should be more standardized.				Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Data Platform Collaboration & Readiness	N/A		Works effectively with data teams; upstream data readiness requirements can be better defined.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	AI Risk Management & Responsible AI Controls	N/A		Identifies key risks; control design and escalation pathways need more structure.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Change Management & User Adoption for AI Solutions	N/A		Supports adoption discussions well; user enablement planning should start earlier.				Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Jonathan To
13405	Lucian Nguyen	IT	Manager	Executive Communication & AI Thought Leadership	N/A		Explains technical concepts clearly; executive messaging should focus more on outcomes and decisions.				Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Jonathan To
18500	Tuan Nguyen	Human Resources	Specialist	Manage overall administrative operations	R4		Ensure internal procedures, documents, records, and files are properly maintained, operated, and effectively controlled	Maintain proper organization and documentation filing systems	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
18500	Tuan Nguyen	Human Resources	Specialist	Manage and monitor the quality of administrative services	R3	X	Ensure internal services meet standards, quality requirements, and are continuously improved	Proactively assess and address issues promptly and effectively	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
18500	Tuan Nguyen	Human Resources	Specialist	Manage and supervise service quality of external vendors and service providers	R3	X	Ensure all services meet standards, quality requirements, and are continuously improved	Collaborate closely with partners to ensure service quality meets commitments	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
18500	Tuan Nguyen	Human Resources	Specialist	Implement policies and procedures related to contractors and suppliers	R4		Ensure third parties clearly understand and comply with company regulations	Conduct regular inspections and evaluations for continuous improvement	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
18500	Tuan Nguyen	Human Resources	Specialist	Support occupational safety and fire prevention & fighting (PCCC) activities	R4		Coordinate the implementation of safety measures, conduct periodic inspections, monitor, and report on safety status	Maintain ongoing coordination with relevant departments	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
18500	Tuan Nguyen	Human Resources	Specialist	Handle incidents related to security and order (ANTT)	R4		Promptly handle security issues, internal incidents, or policy violations	Take initiative in handling situations in a timely manner	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
18500	Tuan Nguyen	Human Resources	Specialist	Manage and operate company medical services	R4		Implement employee healthcare and wellness programs	Ensure more efficient and effective operations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
18500	Tuan Nguyen	Human Resources	Specialist	Prepare reports and analyze HR-related data	R3	X	Consolidate and analyze HR, medical, and administrative data to support management decision-making	Ensure timely compliance with regulations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Manage overall administrative operations	R4		Ensure internal procedures, documents, records, and files are properly maintained, operated, and effectively controlled	Maintain proper organization and documentation filing systems	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Manage and monitor the quality of administrative services	R3	X	Ensure internal services meet standards, quality requirements, and are continuously improved	Proactively assess and address issues promptly and effectively	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Manage and supervise service quality of external vendors and service providers	R3	X	Ensure all services meet standards, quality requirements, and are continuously improved	Collaborate closely with partners to ensure service quality meets commitments	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Implement policies and procedures related to contractors and suppliers	R4		Ensure third parties clearly understand and comply with company regulations	Conduct regular inspections and evaluations for continuous improvement	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Support occupational safety and fire prevention & fighting activities	R4		Coordinate the implementation of safety measures, conduct periodic inspections, monitor, and report on safety status	Maintain ongoing coordination with relevant departments	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Handle incidents related to security	R4		Promptly handle security issues, internal incidents, or policy violations	Take initiative in handling situations in a timely manner	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Manage and operate company medical services	R4		Implement employee healthcare and wellness programs	Ensure more efficient and effective operations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
16860	Quyen Lam	Human Resources	Specialist	Prepare reports and analyze HR-related data	R4		Proactively consolidate data and prepare reports in compliance with regulations	Ensure consistent execution	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Build and maintain harmonious and stable employee relations	R4		Maintain a positive work environment, minimize conflicts, and keep employee complaints/disputes at a low level	Proactively collaborate with all departments to build more sustainable employee relations	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Ensure compliance with labor laws and minimize legal risks for the company	R4		Ensure no major violations occur; effectively control risks related to audits and inspections	Proactively assess employee relations risks and ensure timely and effective mitigation	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Lead the handling of complex and sensitive employee relations cases	R4		Resolve issues effectively and in compliance with regulations, minimizing impact on operations and company reputation	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Collaborate in developing, reviewing, and optimizing company labor policies and internal regulations	R3	X	Ensure policies are clear, timely updated, practical, and effectively implemented	Ensure continuous review and timely updates	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Coordinate with the trade union and relevant stakeholders to organize employee engagement activities and events	R4		Organize effective engagement activities, enhance employee engagement, and receive positive feedback from employees	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Manage and control disciplinary actions to ensure fairness and consistency	R4		Ensure fairness, consistency, and transparency in disciplinary actions	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Implement communication initiatives to enhance awareness of employee relations across the organization	R4		Ensure employees understand and comply with policies and regulations; reduce violations caused by lack of awareness	Proactively plan and communicate to employees in a timely manner	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Drive initiatives to improve employee engagement and workplace environment	R3	X	Improve employee satisfaction, reduce turnover, and enhance employee engagement	Proactively develop employee engagement initiatives aligned with the company’s culture and strategic direction	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
51461	Hana Truong	Human Resources	Team leader	Analyze data and prepare reports on absenteeism (AB) and turnover (TO)	R3	X	Deliver accurate and timely reports; provide insights and recommend improvement actions	Take a proactive approach to data analysis and ensure all reports are accurate, timely, and compliant with relevant regulations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Build and maintain harmonious and stable employee relations	R4		Maintain a positive work environment, minimize conflicts, and keep employee complaints/disputes at a low level	Proactively collaborate with all departments to build more sustainable employee relations	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Ensure compliance with labor laws and minimize legal risks for the company	R3	X	Ensure no major violations occur; effectively control risks related to audits and inspections	Proactively stay updated on changes in labor laws and effectively apply them in daily operations	Q2-Q4		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Lead the handling of complex and sensitive employee relations cases	R3	X	Resolve issues effectively and in compliance with regulations, minimizing impact on operations and company reputation	Continuously enhance professional capabilities to effectively handle complex and sensitive employee relations cases	Q2-Q4		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Collaborate in developing, reviewing, and optimizing company labor policies and internal regulations	R3	X	Ensure policies are clear, timely updated, practical, and effectively implemented	Ensure continuous review and timely updates	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Coordinate with the trade union and relevant stakeholders to organize employee engagement activities and events	R4		Organize effective engagement activities, enhance employee engagement, and receive positive feedback from employees	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Manage and control disciplinary actions to ensure fairness and consistency	R4		Ensure fairness, consistency, and transparency in disciplinary actions	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Implement communication initiatives to enhance awareness of employee relations across the organization	R4		Ensure employees understand and comply with policies and regulations; reduce violations caused by lack of awareness	Proactively plan and communicate to employees in a timely manner	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Drive initiatives to improve employee engagement and workplace environment	R4		Improve employee satisfaction, reduce turnover, and enhance employee engagement	Maintain and promote	Ongoing		Functional	Employee Relations	Department Follow-up	Employee Relations Follow-up	HRBP / Department	Karen Nguyen
-	Ginta Doan	Human Resources	Specialist	Analyze data and prepare reports on absenteeism (AB) and turnover (TO)	R3	X	Deliver accurate and timely reports; provide insights and recommend improvement actions	Take a proactive approach to data analysis and ensure all reports are accurate, timely, and compliant with relevant regulations	Ongoing		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Karen Nguyen
`;
