export const rawWanekIDPTSV_part6 = `Emp Code	Person Name	Department	Critical Role	Job Duty	R Rating	Top Opp.	Comments	Way Forward	Timeline	Notes	Training Category	Competency Focus	Action	Proposed Program	Program Owner	Source Owner
20170	Tom Nguyen	Planning & Inventory Control	Manager	Weekly/Monthly/Quarterly Report or Dashboard reflection	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Problem Solving	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Effective Communications	R3		Communicates clearly but still have more rooms to keep improvement when communicate to upper level both verbal and written	Coach team on communication: Short sentences, clear logic, No operational details unless asked, may need some story telling			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Decision Making	R4						Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Critical Thinking	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Stakeholder Management	R3	X	Good now but need for upper level	More confident when having meeting with other BODs. Build stronger connetion/trust with BOD			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Cross Functional Management	R3						Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Customer Satisfaction & On-time Shipment (ensure plans meet customer commitment)	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Tom Nguyen
20170	Tom Nguyen	Planning & Inventory Control	Manager	Power BI/SQL Dashboard, power automate Ownership: Elimination of manual reporting for the team + Applying AI in Daily Work	R4						Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Tom Nguyen
	Dominic Duong	Planning & Inventory Control	Manager	Ramp Plan Development/Capacity Planning	R4						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Material Requirements Planning (MRP)	R4						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Master Production Schedule (MPS)	R4						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Scenario Planning (Whatif Scenario)	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Coordinate with US team	R2						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Supply Chain Collaboration	R2						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Drive for globalization tasks	R1		Millennium is not in scope currently				Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Inventory Accuracy	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Recording Transaction	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	WIP Control & Cycle Count Performance (plan/monitor; improve inventory accuracy)	R3	X	More systematic. Keep staying on top of all the things	More systematic. Keep staying on top of all the things			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Overseeing the entire execution	R3	X	Keep staying on top of all the things	"1) Improving thru current tasks and build experience.
2) A.Kelvin/KT to help as needed"			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Production schedule optimization	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	System enhancement (AS400, Mapics, Helix, etc)	R1						Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Ramp Plan Execution & Tracking (execute ramp actions; track actual vs plan; adjust)	R3						Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Day-to-day Production Constraints Resolution (identify, communicate, remove blockers)	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Drive for process improvement	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Drive for Innovation Ideas	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Operational Knowlegde & understanding (Business Sense)	R2						Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Overall Busines Acumen from Market/Industry	R2						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Balances productivity, cost, safety and morale to achieve positive results in all areas	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Direct the planning team and resolve day to day production constraints	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Disaster Recovery Planning	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Promoting a Teamwork environment	R3		Willing to do but need to be trained thru professional course	Coaching/Mentoring the next level staffs			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Maintaining and Developing a Culture around our Core and Growth Values	R3	X					People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Coaching and Mentoring	R2	X	"Willing but lacks structured coaching skills

Dominic inputs: Having only a basic understanding of mentoring and coaching. It would be helpful to have structured training and clear guidance to effectively apply these tools in practice."	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Employee Relations Improvement	R3	X	Need to expan for bigger scope/group	Need to expan for bigger scope/group			Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Monitoring departmental/team performance measures	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Succession Planning	R2		Willing but lacks structured skills and train successor	Attend Succession Planning training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Personal Professional Development Plan	R2	X	Willing but lacks structured skills and train successor	"1) Attend Succession Planning training; practice
2) KT/a.Kelvin to provide more help on this"			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Hire and train new team player	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Build the high performing team	R3						Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Department Compliance	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Weekly/Monthly/Quarterly Report or Dashboard reflection	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Problem Solving	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Effective Communications	R3		Communicates clearly but still have more rooms to keep improvement such as sense of sensitive, etc.	Coach team on communication: Short sentences, Clear logic, No operational details unless asked, may need some story telling			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Decision Making	R3						Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Critical Thinking	R3						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Stakeholder Management	R3	X	Good now but need for upper level	More confident when having meeting with other BODs. Build stronger connetion/trust with BOD			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Cross Functional Management	R3	X					Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Customer Satisfaction & On-time Shipment (ensure plans meet customer commitment)	R4						Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Dominic Duong
	Dominic Duong	Planning & Inventory Control	Manager	Power BI/SQL Dashboard, power automate Ownership: Elimination of manual reporting for the team + Applying AI in Daily Work	R2						Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Dominic Duong
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Ramp Plan Development	R2	X	Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Ramp Plan Execution & Shipment Delivery	R3		Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Succession Planning	R4		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Personal Development (Sharpen the Saw)	R2		Development activities not fully structured	Create and follow IDP			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Timely Decision Making	R2	X	Makes sound and timely decision	Maintain decision frameworks			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Building and Promoting a Company Culture	R2	X	Actively drives culture initiatives	Scale culture programs	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Promoting a Teamwork environment	R2		Encourages collaboration across teams	Lead cross-functional projects	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Effective Communications	R3	X	Communicates clearly and effectively	Coach team on communication			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Coaching and Mentoring	R4		Willing but lacks structured coaching skills	Attend coaching training; practice			People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Hoang Bich Tram
44775	Mai Thi Hoang Bich Tram	Cut&Sew WNK3	Production Lead Supervisor - C&S	Quality Control & Issue Solving	R4	X	Monitoring processes, identifying root cause, and implementing effective corrective and preventive actions	Maintains consistent quality and resolves issues in a timely manner			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Thi Hoang Bich Tram
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Ramp Plan Execution & Shipment Delivery	R4		Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Succession Planning	R4	X	Strong workforce planning and allocation	Coach others on resource planning	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Personal Development (Sharpen the Saw)	R3	X	Actively supports people development	Expand development initiatives	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Timely Decision Making	R3	X	Confident in HR budgeting and cost control	Support cross-functional budgeting	Q3		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Building and Promoting a Company Culture	R2		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Promoting a Teamwork environment	R2		Development activities not fully structured	Create and follow IDP	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Effective Communications	R2	X	Strong understanding of business operations	Mentor junior HR staff	Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Coaching and Mentoring	R3		Makes sound and timely decision	Maintain decision frameworks	Q3		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Do Thi Thanh Nga
28258	Do Thi Thanh Nga	Cut&Sew WNK3	Production Lead Supervisor - C&S	Quality Control & Issue Solving	R3	X	Actively drives culture initiatives	Scale culture programs	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Do Thi Thanh Nga
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Ramp Plan Execution & Shipment Delivery	R4		Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Succession Planning	R4	X	Strong workforce planning and allocation	Coach others on resource planning	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Personal Development (Sharpen the Saw)	R4	X	Actively supports people development	Expand development initiatives	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Timely Decision Making	R2	X	Confident in HR budgeting and cost control	Support cross-functional budgeting			Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Building and Promoting a Company Culture	R3		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Promoting a Teamwork environment	R2		Development activities not fully structured	Create and follow IDP	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Effective Communications	R2	X	Strong understanding of business operations	Mentor junior HR staff			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Coaching and Mentoring	R4		Makes sound and timely decision	Maintain decision frameworks	Q3		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Elsa Nguyen
01404	Elsa Nguyen	Cut&Sew WNK3	QP Lead Supervisor - C&S	Quality Control & Issue Solving	R2	X	Actively drives culture initiatives	Scale culture programs			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Elsa Nguyen
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Ramp Plan Execution & Shipment Delivery	R4		Executes ramp plans consistently and effectively to ensure on-time shipment	Maintain execution discipline	Q2		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Succession Planning	R4	X	Strong workforce planning and allocation	Coach others on resource planning	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Personal Development (Sharpen the Saw)	R3	X	Actively supports people development	Expand development initiatives	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Timely Decision Making	R3	X	Confident in HR budgeting and cost control	Support cross-functional budgeting	Q3		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Building and Promoting a Company Culture	R2		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Promoting a Teamwork environment	R2		Development activities not fully structured	Create and follow IDP	Q2		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Effective Communications	R2	X	Strong understanding of business operations	Mentor junior HR staff	Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Coaching and Mentoring	R3		Makes sound and timely decision	Maintain decision frameworks	Q3		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Mai Thi Loan
06788	Mai Thi Loan	Cut&Sew WNK3	Production Lead Supervisor - C&S	Quality Control & Issue Solving	R3	X	Actively drives culture initiatives	Scale culture programs	Q2		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Mai Thi Loan
43877	Annie Nguyen	Human Resources	Communication Supervisor	Ramp Plan Development	R4		Fully capable; independently develops effective ramp plans	Continue best practices and share knowledge	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Ramp Plan Execution	R4		Executes ramp plans consistently and effectively	Maintain execution discipline	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Resource Management (Human)	R4		Strong workforce planning and allocation	Coach others on resource planning	Ongoing		Functional	Workforce Planning	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Resource Development (Human)	R4		Actively supports people development	Expand development initiatives	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Budget development & management	R4		Confident in HR budgeting and cost control	Support cross-functional budgeting	Annual cycle		Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Succession Planning	R3		Good understanding; limited end-to-end ownership	Co-lead succession planning with HR Head	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Recruitment Plan Development	R3	X	Strong execution; needs more strategic planning	Build annual recruitment plan	Q2–Q3		Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Recruitment Execution	R3		"Effectively translates hiring needs into ""trendy"" content to attract candidates."	Leverage digital platforms to amplify employer branding and hiring targets	Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	HR Market Analysis	R3		Effectively analyzes labor market trends	Share insights with leadership	Ongoing		Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Personal Development (Sharpen the Saw)	R3		Development activities not fully structured	Create and follow IDP	Q1–Q4		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Operational Knowlegde & understanding (Business Sense)	R4		Strong understanding of business operations	Mentor junior HR staff	Ongoing		Business Acumen	Business Acumen	Department Follow-up	Business Acumen & Decision Making	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Decision making	R4		Makes sound and timely decision	Maintain decision frameworks	Ongoing		Leadership	Leadership Skills	Add to Training Plan	Servant Leadership	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Building and Promoting a Company Culture	R4		Actively drives culture initiatives	Scale culture programs	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Promoting a Teamwork environment	R4		Encourages collaboration across teams	Lead cross-functional projects	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Maintaining and Developing a Culture around our Core and Growth Values	R4		Values embedded in daily HR practices	Reinforce through HR processes	Ongoing		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Effective Communications	R4		Communicates clearly and effectively	Coach team on communication	Ongoing		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Coaching and Mentoring	R2	X	Willing but lacks structured coaching skills	Attend coaching training; practice	Q2–Q3		People Development	Coaching Skills	Add to Training Plan	Train the Trainer / Coaching Program	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Employee Relations Improvement	R4		Bridges management and staff gaps via effective internal channels.	Boost engagement through social platforms and interactive content and videos.	Ongoing		Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Internal Comms Strategy Development	R2	X	Capable of building annual roadmaps; needs more focus on data-driven ROI.	Attend advanced workshops on communication impact measurement.	Q2–Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Engagement Event Orchestration	R4		Creatively organizes events with high employee participation rates.	Establish a standardized Event Playbook for the organization.			Functional	Employee Relations	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Multi-channel Management	R2	X	Effectively manages Social, Email, and Intranet; content is consistent.	Experiment with new formats (Internal Podcasts, Short-form Videos).	Q2–Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Content Creation & Storytelling	R4		Strong writing skills; transforms dry info into inspiring stories.	Mentor junior staff on creative copywriting and visual storytelling.			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Leadership Communication Support	R4		Good at drafting messages; needs to be more proactive in style consulting.	Become a strategic advisor for senior management on internal messaging.			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Employer Branding (Internal)	R4		Successfully promotes core values through internal activities.	Collaborate with Recruitment to align internal & external branding.			Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Crisis Communication Management	R2	X	Handles sensitive internal issues calmly and professionally.	Develop a detailed internal crisis communication response script.	Q2–Q3		Soft Skill	Communication Skills	Add to Training Plan	Communication & Presentation	L&D + HRBP	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Employee Feedback & Surveying	R2		Regularly conducts surveys to gauge employee sentiment.	Analyze survey data deeply to propose workplace improvements.			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Cross-departmental Collaboration	R4		Works seamlessly with HR and other functional departments.	Lead cross-functional communication projects for major changes.			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Budget Management for Comms	R4		Manages event budgets strictly; demonstrates good cost optimization.	Propose sponsorship or partnership models for larger-scale events.			Functional	Finance / Cost Management	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Trend Analysis	R2	X	Effectively adopts digital trends to keep internal content modern and engaging.	"Deploy AI tools and short-form videos to boost 
reach among younger workers."	Q2–Q3		Digital	AI & Automation	Add to Training Plan	AI for Everyone; Power Automate; Power BI	L&D + IT/Automation SME	Annie Nguyen
43877	Annie Nguyen	Human Resources	Communication Supervisor	Site Coordination	R4		Ensures consistent branding and messaging across all factory sites.	"Standardize workflows to bridge geographical 
gaps and improve synergy."			Functional	Process & Compliance	Department Follow-up	Process Improvement / Compliance Follow-up	Department / Functional SME	Annie Nguyen`;
